/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* GENERATED by dev/tune_fixed.py (atan, n = 4, r = 20) -- do not
   edit directly; retune or re-emit with
       python3 dev/tune_fixed.py atan 4 --pin 20 --emit */

#include "flint.h"
#include "longlong.h"
#include "mpn_extras.h"
#include "fixed.h"
#include "hand_mulhi.inc"

#if FLINT_BITS == 64

/* atan, n = 4, r = 20: 5 levels, widths [3, 3, 2, 2, 1] */
static void
_fixed_atan_series_4(nn_ptr res, nn_srcptr x)
{
    ulong z[4], V[4], T[4], P[4], Z[2];
    ulong v, w1, w0, h, l;
    slong i;

    (void) v; (void) w1; (void) w0; (void) h; (void) l;
    (void) i; (void) Z; (void) V; (void) T; (void) P;

    flint_mpn_sqrhigh(z, x, 4);

    v = UWORD(0x1745d1745d1745d1);

    /* V_3 = c - z V_4   (2 x 1 limbs) */
    _fixed_mulhi_2x1(&h, &l, z[3], z[2], v);
    sub_ddmmss(w1, w0, UWORD(0x1c71c71c71c71c71), UWORD(0xc71c71c71c71c71c), h, l);

    /* V_2 = c - z V_3   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[3], z[2], w1, w0);
    sub_ddmmss(w1, w0, UWORD(0x2492492492492492), UWORD(0x4924924924924924), h, l);

    /* V_1 = c - z V_2   (3 x 2 limbs) */
    P[0] = UWORD(0);
    P[1] = w0; P[2] = w1;
    flint_mpn_mulhigh_n(T, z + 1, P, 3);
    P[0] = UWORD(0x3333333333333333);
    P[1] = UWORD(0x3333333333333333);
    P[2] = UWORD(0x3333333333333333);
    NN_SUB_3(V, P, T);

    /* V_0 = c - z V_1   (3 x 3 limbs) */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    flint_mpn_mulhigh_n(T, z + 1, P, 3);
    P[0] = UWORD(0x5555555555555555);
    P[1] = UWORD(0x5555555555555555);
    P[2] = UWORD(0x5555555555555555);
    NN_SUB_3(V, P, T);

    /* atan = x - x^3 V_0 */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    flint_mpn_mulhigh_n(T, z, x, 4);
    flint_mpn_mulhigh_n(V, T, P, 4);
    NN_SUB_4(res, x, V);
}

void
fixed_atan_opt_4(nn_ptr res, nn_srcptr x)
{
    const int r = 20;
    ulong x0, x1, x2, x3;
    ulong y0, y1, y2, y3;
    ulong a0, a1, a2, a3;
    ulong e0, e1, e2, e3;
    ulong v0, v1, v2, v3;
    ulong w0, w1, w2, w3;
    ulong bw, m, h, lt;
    ulong S[5], nd[8], t[4], q[4];
    slong i, nc;
    int nz;


    nn_srcptr tab;
    tab = _fixed_atans_tab(4, r, &nc);

    x0 = 0;
    x1 = 0;
    x2 = 0;
    x3 = 0;
    y0 = x[0];
    y1 = x[1];
    y2 = x[2];
    y3 = x[3];
    a0 = 0;
    a1 = 0;
    a2 = 0;
    a3 = 0;

#define AP(ii) (tab + (ii) * nc + (nc - 4))

    /* window 0 */
    {
        nn_srcptr Ap;

        /* boundary step i = 1 */
        Ap = AP(1);
        v0 = MPN_RIGHT_SHIFT_LOW(x1, x0, 1);
        v1 = MPN_RIGHT_SHIFT_LOW(x2, x1, 1);
        v2 = MPN_RIGHT_SHIFT_LOW(x3, x2, 1);
        v3 = MPN_RIGHT_SHIFT_LOW(UWORD(1), x3, 1);
        w0 = MPN_RIGHT_SHIFT_LOW(y1, y0, 1);
        w1 = MPN_RIGHT_SHIFT_LOW(y2, y1, 1);
        w2 = MPN_RIGHT_SHIFT_LOW(y3, y2, 1);
        w3 = MPN_RIGHT_SHIFT_LOW(UWORD(0), y3, 1);
        sub_dddddmmmmmsssss(bw, e3, e2, e1, e0,
            UWORD(0), y3, y2, y1, y0,
            UWORD(0), v3, v2, v1, v0);
        m = ~bw;                /* accept iff no borrow */
        add_ssssaaaaaaaa(x3, x2, x1, x0,
            x3, x2, x1, x0,
            (w3) & m, (w2) & m, (w1) & m, (w0) & m);
        add_ssssaaaaaaaa(a3, a2, a1, a0,
            a3, a2, a1, a0,
            Ap[3] & m, Ap[2] & m, Ap[1] & m, Ap[0] & m);
        y0 = (y0 & bw) | (e0 & m);
        y1 = (y1 & bw) | (e1 & m);
        y2 = (y2 & bw) | (e2 & m);
        y3 = (y3 & bw) | (e3 & m);

        h = y3;

        for (i = 2; i <= 20; i++)
        {
            int b = (int) (i - 0);

            lt = MPN_RIGHT_SHIFT_LOW(UWORD(1), x3, b);
            if (h < lt)
                continue;    /* certain reject */

            Ap = AP(i);
            v0 = MPN_RIGHT_SHIFT_LOW(x1, x0, b);
            v1 = MPN_RIGHT_SHIFT_LOW(x2, x1, b);
            v2 = MPN_RIGHT_SHIFT_LOW(x3, x2, b);
            v3 = lt;
            w0 = MPN_RIGHT_SHIFT_LOW(y1, y0, b);
            w1 = MPN_RIGHT_SHIFT_LOW(y2, y1, b);
            w2 = MPN_RIGHT_SHIFT_LOW(y3, y2, b);
            w3 = MPN_RIGHT_SHIFT_LOW(UWORD(0), y3, b);
            sub_dddddmmmmmsssss(bw, e3, e2, e1, e0,
                UWORD(0), y3, y2, y1, y0,
                UWORD(0), v3, v2, v1, v0);
            m = ~bw;                /* accept iff no borrow */
            add_ssssaaaaaaaa(x3, x2, x1, x0,
                x3, x2, x1, x0,
                (w3) & m, (w2) & m, (w1) & m, (w0) & m);
            add_ssssaaaaaaaa(a3, a2, a1, a0,
                a3, a2, a1, a0,
                Ap[3] & m, Ap[2] & m, Ap[1] & m, Ap[0] & m);
            y0 = (y0 & bw) | (e0 & m);
            y1 = (y1 & bw) | (e1 & m);
            y2 = (y2 & bw) | (e2 & m);
            y3 = (y3 & bw) | (e3 & m);
            h = y3;
        }
    }

    /* the step at i = r restores Y < trunc(X >> r) <= X 2^-r;
       entering it Y < X 2^-(r-1), so two passes suffice */
    for (nz = 0; nz < 2; nz++)
    {
        nn_srcptr Ap = AP((slong) r);
        const int b = 20;

        lt = MPN_RIGHT_SHIFT_LOW(UWORD(1), x3, b);
        v0 = MPN_RIGHT_SHIFT_LOW(x1, x0, b);
        v1 = MPN_RIGHT_SHIFT_LOW(x2, x1, b);
        v2 = MPN_RIGHT_SHIFT_LOW(x3, x2, b);
        v3 = lt;
        w0 = MPN_RIGHT_SHIFT_LOW(y1, y0, b);
        w1 = MPN_RIGHT_SHIFT_LOW(y2, y1, b);
        w2 = MPN_RIGHT_SHIFT_LOW(y3, y2, b);
        w3 = MPN_RIGHT_SHIFT_LOW(UWORD(0), y3, b);
        sub_dddddmmmmmsssss(bw, e3, e2, e1, e0,
            UWORD(0), y3, y2, y1, y0,
            UWORD(0), v3, v2, v1, v0);
        m = ~bw;                /* accept iff no borrow */
        add_ssssaaaaaaaa(x3, x2, x1, x0,
            x3, x2, x1, x0,
            (w3) & m, (w2) & m, (w1) & m, (w0) & m);
        add_ssssaaaaaaaa(a3, a2, a1, a0,
            a3, a2, a1, a0,
            Ap[3] & m, Ap[2] & m, Ap[1] & m, Ap[0] & m);
        y0 = (y0 & bw) | (e0 & m);
        y1 = (y1 & bw) | (e1 & m);
        y2 = (y2 & bw) | (e2 & m);
        y3 = (y3 & bw) | (e3 & m);
    }

#undef AP

    /* t = Y 2^(FLINT_BITS 4) / X */
    S[0] = x0;
    S[1] = x1;
    S[2] = x2;
    S[3] = x3;
    S[4] = 1;
    nz = (y0 != 0) | (y1 != 0) | (y2 != 0) | (y3 != 0);
    if (nz)
    {
        nd[0] = 0;
        nd[1] = 0;
        nd[2] = 0;
        nd[3] = 0;
        nd[4] = y0;
        nd[5] = y1;
        nd[6] = y2;
        nd[7] = y3;
        mpn_tdiv_qr(t, nd, 0, nd, 8, S, 5);
    }
    else
    {
        t[0] = 0;
        t[1] = 0;
        t[2] = 0;
        t[3] = 0;
    }

    _fixed_atan_series_4(q, t);

    add_ssssaaaaaaaa(a3, a2, a1, a0,
        a3, a2, a1, a0,
        q[3], q[2], q[1], q[0]);
    res[0] = a0;
    res[1] = a1;
    res[2] = a2;
    res[3] = a3;
}


#endif /* FLINT_BITS == 64 */
