/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* GENERATED by dev/tune_fixed.py (atan, n = 1, r = 4) -- do not
   edit directly; retune or re-emit with
       python3 dev/tune_fixed.py atan 1 --pin 4 --emit */

#include "flint.h"
#include "longlong.h"
#include "mpn_extras.h"
#include "fixed.h"
#include "impl.h"
#include "hand_mulhi.inc"

#if FLINT_BITS == 64

/* atan, n = 1, r = 4: 7 levels, widths [1, 1, 1, 1, 1, 1, 1] */
static void
_fixed_atan_series_1(nn_ptr res, nn_srcptr x)
{
    ulong z[1], V[1], T[1], P[1], Z[2];
    ulong v, w1, w0, h, l;
    slong i;

    (void) v; (void) w1; (void) w0; (void) h; (void) l;
    (void) i; (void) Z; (void) V; (void) T; (void) P;

    z[0] = n_mulhi(x[0], x[0]);

    v = UWORD(0x1111111111111111);

    /* V_5 = c - z V_6   (1 x 1 limbs) */
    v = n_mulhi(z[0], v);
    v = UWORD(0x13b13b13b13b13b1) - v;

    /* V_4 = c - z V_5   (1 x 1 limbs) */
    v = n_mulhi(z[0], v);
    v = UWORD(0x1745d1745d1745d1) - v;

    /* V_3 = c - z V_4   (1 x 1 limbs) */
    v = n_mulhi(z[0], v);
    v = UWORD(0x1c71c71c71c71c71) - v;

    /* V_2 = c - z V_3   (1 x 1 limbs) */
    v = n_mulhi(z[0], v);
    v = UWORD(0x2492492492492492) - v;

    /* V_1 = c - z V_2   (1 x 1 limbs) */
    v = n_mulhi(z[0], v);
    v = UWORD(0x3333333333333333) - v;

    /* V_0 = c - z V_1   (1 x 1 limbs) */
    v = n_mulhi(z[0], v);
    v = UWORD(0x5555555555555555) - v;

    /* atan = x - x^3 V_0 */
    P[0] = v;
    T[0] = n_mulhi(z[0], x[0]);
    V[0] = n_mulhi(T[0], P[0]);
    res[0] = x[0] - V[0];
}

void
fixed_atan_opt_1(nn_ptr res, nn_srcptr x)
{
    const int r = 4;
    ulong x0;
    ulong y0;
    ulong a0;
    ulong e0;
    ulong v0;
    ulong w0;
    ulong bw, m, h, lt;
    ulong S[2], nd[2], t[1], q[1];
    slong i, nc;
    int nz;


    _fixed_atans_ensure(1, r);
    nc = _fixed_atans_n;

    x0 = 0;
    y0 = x[0];
    a0 = 0;

#define AP(ii) (_fixed_atans + (ii) * nc + (nc - 1))

    /* window 0 */
    {
        nn_srcptr Ap;

        /* boundary step i = 1 */
        Ap = AP(1);
        v0 = MPN_RIGHT_SHIFT_LOW(UWORD(1), x0, 1);
        w0 = MPN_RIGHT_SHIFT_LOW(UWORD(0), y0, 1);
        sub_ddmmss(bw, e0,
            UWORD(0), y0,
            UWORD(0), v0);
        m = ~bw;                /* accept iff no borrow */
        x0 += (w0) & m;
        a0 += Ap[0] & m;
        y0 = (y0 & bw) | (e0 & m);

        h = y0;

        for (i = 2; i <= 4; i++)
        {
            int b = (int) (i - 0);

            lt = MPN_RIGHT_SHIFT_LOW(UWORD(1), x0, b);
            if (h < lt)
                continue;    /* certain reject */

            Ap = AP(i);
            v0 = lt;
            w0 = MPN_RIGHT_SHIFT_LOW(UWORD(0), y0, b);
            sub_ddmmss(bw, e0,
                UWORD(0), y0,
                UWORD(0), v0);
            m = ~bw;                /* accept iff no borrow */
            x0 += (w0) & m;
            a0 += Ap[0] & m;
            y0 = (y0 & bw) | (e0 & m);
            h = y0;
        }
    }

    /* the step at i = r restores Y < trunc(X >> r) <= X 2^-r;
       entering it Y < X 2^-(r-1), so two passes suffice */
    for (nz = 0; nz < 2; nz++)
    {
        nn_srcptr Ap = AP((slong) r);
        const int b = 4;

        lt = MPN_RIGHT_SHIFT_LOW(UWORD(1), x0, b);
        v0 = lt;
        w0 = MPN_RIGHT_SHIFT_LOW(UWORD(0), y0, b);
        sub_ddmmss(bw, e0,
            UWORD(0), y0,
            UWORD(0), v0);
        m = ~bw;                /* accept iff no borrow */
        x0 += (w0) & m;
        a0 += Ap[0] & m;
        y0 = (y0 & bw) | (e0 & m);
    }

#undef AP

    /* t = Y 2^(FLINT_BITS 1) / X */
    S[0] = x0;
    S[1] = 1;
    nz = (y0 != 0);
    if (nz)
    {
        nd[0] = 0;
        nd[1] = y0;
        mpn_tdiv_qr(t, nd, 0, nd, 2, S, 2);
    }
    else
    {
        t[0] = 0;
    }

    _fixed_atan_series_1(q, t);

    a0 += q[0];
    res[0] = a0;
}


#endif /* FLINT_BITS == 64 */
