/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* GENERATED by dev/tune_fixed.py (atan, n = 7, r = 19) -- do not
   edit directly; retune or re-emit with
       python3 dev/tune_fixed.py atan 7 --pin 19 --emit */

#include "flint.h"
#include "longlong.h"
#include "mpn_extras.h"
#include "fixed.h"
#include "impl.h"
#include "hand_mulhi.inc"

#if FLINT_BITS == 64

/* atan, n = 7, r = 19: 11 levels, widths [7, 6, 5, 5, 4, 4, 3, 2, 2, 1, 1] */
static void
_fixed_atan_series_7(nn_ptr res, nn_srcptr x)
{
    ulong z[7], V[7], T[7], P[7], Z[2];
    ulong v, w1, w0, h, l;
    slong i;

    (void) v; (void) w1; (void) w0; (void) h; (void) l;
    (void) i; (void) Z; (void) V; (void) T; (void) P;

    flint_mpn_sqrhigh(z, x, 7);

    v = UWORD(0x0b21642c8590b216);

    /* V_9 = c - z V_10   (1 x 1 limbs) */
    v = n_mulhi(z[6], v);
    v = UWORD(0x0c30c30c30c30c30) - v;

    /* V_8 = c - z V_9   (2 x 1 limbs) */
    _fixed_mulhi_2x1(&h, &l, z[6], z[5], v);
    sub_ddmmss(w1, w0, UWORD(0x0d79435e50d79435), UWORD(0xe50d79435e50d794), h, l);

    /* V_7 = c - z V_8   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[6], z[5], w1, w0);
    sub_ddmmss(w1, w0, UWORD(0x0f0f0f0f0f0f0f0f), UWORD(0x0f0f0f0f0f0f0f0f), h, l);

    /* V_6 = c - z V_7   (3 x 2 limbs) */
    P[0] = UWORD(0);
    P[1] = w0; P[2] = w1;
    flint_mpn_mulhigh_n(T, z + 4, P, 3);
    P[0] = UWORD(0x1111111111111111);
    P[1] = UWORD(0x1111111111111111);
    P[2] = UWORD(0x1111111111111111);
    NN_SUB_3(V, P, T);

    /* V_5 = c - z V_6   (4 x 3 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    flint_mpn_mulhigh_n(T, z + 3, P, 4);
    P[0] = UWORD(0x13b13b13b13b13b1);
    P[1] = UWORD(0xb13b13b13b13b13b);
    P[2] = UWORD(0x3b13b13b13b13b13);
    P[3] = UWORD(0x13b13b13b13b13b1);
    NN_SUB_4(V, P, T);

    /* V_4 = c - z V_5   (4 x 4 limbs) */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    P[3] = V[3];
    flint_mpn_mulhigh_n(T, z + 3, P, 4);
    P[0] = UWORD(0x5d1745d1745d1745);
    P[1] = UWORD(0x45d1745d1745d174);
    P[2] = UWORD(0x745d1745d1745d17);
    P[3] = UWORD(0x1745d1745d1745d1);
    NN_SUB_4(V, P, T);

    /* V_3 = c - z V_4   (5 x 4 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    P[4] = V[3];
    flint_mpn_mulhigh_n(T, z + 2, P, 5);
    P[0] = UWORD(0xc71c71c71c71c71c);
    P[1] = UWORD(0x1c71c71c71c71c71);
    P[2] = UWORD(0x71c71c71c71c71c7);
    P[3] = UWORD(0xc71c71c71c71c71c);
    P[4] = UWORD(0x1c71c71c71c71c71);
    NN_SUB_5(V, P, T);

    /* V_2 = c - z V_3   (5 x 5 limbs) */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    P[3] = V[3];
    P[4] = V[4];
    flint_mpn_mulhigh_n(T, z + 2, P, 5);
    P[0] = UWORD(0x4924924924924924);
    P[1] = UWORD(0x2492492492492492);
    P[2] = UWORD(0x9249249249249249);
    P[3] = UWORD(0x4924924924924924);
    P[4] = UWORD(0x2492492492492492);
    NN_SUB_5(V, P, T);

    /* V_1 = c - z V_2   (6 x 5 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    P[4] = V[3];
    P[5] = V[4];
    flint_mpn_mulhigh_n(T, z + 1, P, 6);
    P[0] = UWORD(0x3333333333333333);
    P[1] = UWORD(0x3333333333333333);
    P[2] = UWORD(0x3333333333333333);
    P[3] = UWORD(0x3333333333333333);
    P[4] = UWORD(0x3333333333333333);
    P[5] = UWORD(0x3333333333333333);
    NN_SUB_6(V, P, T);

    /* V_0 = c - z V_1   (7 x 6 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    P[4] = V[3];
    P[5] = V[4];
    P[6] = V[5];
    flint_mpn_mulhigh_n(T, z + 0, P, 7);
    P[0] = UWORD(0x5555555555555555);
    P[1] = UWORD(0x5555555555555555);
    P[2] = UWORD(0x5555555555555555);
    P[3] = UWORD(0x5555555555555555);
    P[4] = UWORD(0x5555555555555555);
    P[5] = UWORD(0x5555555555555555);
    P[6] = UWORD(0x5555555555555555);
    NN_SUB_7(V, P, T);

    /* atan = x - x^3 V_0 */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    P[3] = V[3];
    P[4] = V[4];
    P[5] = V[5];
    P[6] = V[6];
    flint_mpn_mulhigh_n(T, z, x, 7);
    flint_mpn_mulhigh_n(V, T, P, 7);
    NN_SUB_7(res, x, V);
}

void
fixed_atan_opt_7(nn_ptr res, nn_srcptr x)
{
    const int r = 19;
    ulong x0, x1, x2, x3, x4, x5, x6;
    ulong y0, y1, y2, y3, y4, y5, y6;
    ulong a0, a1, a2, a3, a4, a5, a6;
    ulong e0, e1, e2, e3, e4, e5, e6;
    ulong v0, v1, v2, v3, v4, v5, v6;
    ulong w0, w1, w2, w3, w4, w5, w6;
    ulong bw, m, h, lt;
    ulong S[8], nd[14], t[7], q[7];
    slong i, nc;
    int nz;


    _fixed_atans_ensure(7, r);
    nc = _fixed_atans_n;

    x0 = 0;
    x1 = 0;
    x2 = 0;
    x3 = 0;
    x4 = 0;
    x5 = 0;
    x6 = 0;
    y0 = x[0];
    y1 = x[1];
    y2 = x[2];
    y3 = x[3];
    y4 = x[4];
    y5 = x[5];
    y6 = x[6];
    a0 = 0;
    a1 = 0;
    a2 = 0;
    a3 = 0;
    a4 = 0;
    a5 = 0;
    a6 = 0;

#define AP(ii) (_fixed_atans + (ii) * nc + (nc - 7))

    /* window 0 */
    {
        nn_srcptr Ap;

        /* boundary step i = 1 */
        Ap = AP(1);
        v0 = MPN_RIGHT_SHIFT_LOW(x1, x0, 1);
        v1 = MPN_RIGHT_SHIFT_LOW(x2, x1, 1);
        v2 = MPN_RIGHT_SHIFT_LOW(x3, x2, 1);
        v3 = MPN_RIGHT_SHIFT_LOW(x4, x3, 1);
        v4 = MPN_RIGHT_SHIFT_LOW(x5, x4, 1);
        v5 = MPN_RIGHT_SHIFT_LOW(x6, x5, 1);
        v6 = MPN_RIGHT_SHIFT_LOW(UWORD(1), x6, 1);
        w0 = MPN_RIGHT_SHIFT_LOW(y1, y0, 1);
        w1 = MPN_RIGHT_SHIFT_LOW(y2, y1, 1);
        w2 = MPN_RIGHT_SHIFT_LOW(y3, y2, 1);
        w3 = MPN_RIGHT_SHIFT_LOW(y4, y3, 1);
        w4 = MPN_RIGHT_SHIFT_LOW(y5, y4, 1);
        w5 = MPN_RIGHT_SHIFT_LOW(y6, y5, 1);
        w6 = MPN_RIGHT_SHIFT_LOW(UWORD(0), y6, 1);
        sub_ddddddddmmmmmmmmssssssss(bw, e6, e5, e4, e3, e2, e1, e0,
            UWORD(0), y6, y5, y4, y3, y2, y1, y0,
            UWORD(0), v6, v5, v4, v3, v2, v1, v0);
        m = ~bw;                /* accept iff no borrow */
        add_sssssssaaaaaaaaaaaaaa(x6, x5, x4, x3, x2, x1, x0,
            x6, x5, x4, x3, x2, x1, x0,
            (w6) & m, (w5) & m, (w4) & m, (w3) & m, (w2) & m, (w1) & m, (w0) & m);
        add_sssssssaaaaaaaaaaaaaa(a6, a5, a4, a3, a2, a1, a0,
            a6, a5, a4, a3, a2, a1, a0,
            Ap[6] & m, Ap[5] & m, Ap[4] & m, Ap[3] & m, Ap[2] & m, Ap[1] & m, Ap[0] & m);
        y0 = (y0 & bw) | (e0 & m);
        y1 = (y1 & bw) | (e1 & m);
        y2 = (y2 & bw) | (e2 & m);
        y3 = (y3 & bw) | (e3 & m);
        y4 = (y4 & bw) | (e4 & m);
        y5 = (y5 & bw) | (e5 & m);
        y6 = (y6 & bw) | (e6 & m);

        h = y6;

        for (i = 2; i <= 19; i++)
        {
            int b = (int) (i - 0);

            lt = MPN_RIGHT_SHIFT_LOW(UWORD(1), x6, b);
            if (h < lt)
                continue;    /* certain reject */

            Ap = AP(i);
            v0 = MPN_RIGHT_SHIFT_LOW(x1, x0, b);
            v1 = MPN_RIGHT_SHIFT_LOW(x2, x1, b);
            v2 = MPN_RIGHT_SHIFT_LOW(x3, x2, b);
            v3 = MPN_RIGHT_SHIFT_LOW(x4, x3, b);
            v4 = MPN_RIGHT_SHIFT_LOW(x5, x4, b);
            v5 = MPN_RIGHT_SHIFT_LOW(x6, x5, b);
            v6 = lt;
            w0 = MPN_RIGHT_SHIFT_LOW(y1, y0, b);
            w1 = MPN_RIGHT_SHIFT_LOW(y2, y1, b);
            w2 = MPN_RIGHT_SHIFT_LOW(y3, y2, b);
            w3 = MPN_RIGHT_SHIFT_LOW(y4, y3, b);
            w4 = MPN_RIGHT_SHIFT_LOW(y5, y4, b);
            w5 = MPN_RIGHT_SHIFT_LOW(y6, y5, b);
            w6 = MPN_RIGHT_SHIFT_LOW(UWORD(0), y6, b);
            sub_ddddddddmmmmmmmmssssssss(bw, e6, e5, e4, e3, e2, e1, e0,
                UWORD(0), y6, y5, y4, y3, y2, y1, y0,
                UWORD(0), v6, v5, v4, v3, v2, v1, v0);
            m = ~bw;                /* accept iff no borrow */
            add_sssssssaaaaaaaaaaaaaa(x6, x5, x4, x3, x2, x1, x0,
                x6, x5, x4, x3, x2, x1, x0,
                (w6) & m, (w5) & m, (w4) & m, (w3) & m, (w2) & m, (w1) & m, (w0) & m);
            add_sssssssaaaaaaaaaaaaaa(a6, a5, a4, a3, a2, a1, a0,
                a6, a5, a4, a3, a2, a1, a0,
                Ap[6] & m, Ap[5] & m, Ap[4] & m, Ap[3] & m, Ap[2] & m, Ap[1] & m, Ap[0] & m);
            y0 = (y0 & bw) | (e0 & m);
            y1 = (y1 & bw) | (e1 & m);
            y2 = (y2 & bw) | (e2 & m);
            y3 = (y3 & bw) | (e3 & m);
            y4 = (y4 & bw) | (e4 & m);
            y5 = (y5 & bw) | (e5 & m);
            y6 = (y6 & bw) | (e6 & m);
            h = y6;
        }
    }

    /* the step at i = r restores Y < trunc(X >> r) <= X 2^-r;
       entering it Y < X 2^-(r-1), so two passes suffice */
    for (nz = 0; nz < 2; nz++)
    {
        nn_srcptr Ap = AP((slong) r);
        const int b = 19;

        lt = MPN_RIGHT_SHIFT_LOW(UWORD(1), x6, b);
        v0 = MPN_RIGHT_SHIFT_LOW(x1, x0, b);
        v1 = MPN_RIGHT_SHIFT_LOW(x2, x1, b);
        v2 = MPN_RIGHT_SHIFT_LOW(x3, x2, b);
        v3 = MPN_RIGHT_SHIFT_LOW(x4, x3, b);
        v4 = MPN_RIGHT_SHIFT_LOW(x5, x4, b);
        v5 = MPN_RIGHT_SHIFT_LOW(x6, x5, b);
        v6 = lt;
        w0 = MPN_RIGHT_SHIFT_LOW(y1, y0, b);
        w1 = MPN_RIGHT_SHIFT_LOW(y2, y1, b);
        w2 = MPN_RIGHT_SHIFT_LOW(y3, y2, b);
        w3 = MPN_RIGHT_SHIFT_LOW(y4, y3, b);
        w4 = MPN_RIGHT_SHIFT_LOW(y5, y4, b);
        w5 = MPN_RIGHT_SHIFT_LOW(y6, y5, b);
        w6 = MPN_RIGHT_SHIFT_LOW(UWORD(0), y6, b);
        sub_ddddddddmmmmmmmmssssssss(bw, e6, e5, e4, e3, e2, e1, e0,
            UWORD(0), y6, y5, y4, y3, y2, y1, y0,
            UWORD(0), v6, v5, v4, v3, v2, v1, v0);
        m = ~bw;                /* accept iff no borrow */
        add_sssssssaaaaaaaaaaaaaa(x6, x5, x4, x3, x2, x1, x0,
            x6, x5, x4, x3, x2, x1, x0,
            (w6) & m, (w5) & m, (w4) & m, (w3) & m, (w2) & m, (w1) & m, (w0) & m);
        add_sssssssaaaaaaaaaaaaaa(a6, a5, a4, a3, a2, a1, a0,
            a6, a5, a4, a3, a2, a1, a0,
            Ap[6] & m, Ap[5] & m, Ap[4] & m, Ap[3] & m, Ap[2] & m, Ap[1] & m, Ap[0] & m);
        y0 = (y0 & bw) | (e0 & m);
        y1 = (y1 & bw) | (e1 & m);
        y2 = (y2 & bw) | (e2 & m);
        y3 = (y3 & bw) | (e3 & m);
        y4 = (y4 & bw) | (e4 & m);
        y5 = (y5 & bw) | (e5 & m);
        y6 = (y6 & bw) | (e6 & m);
    }

#undef AP

    /* t = Y 2^(FLINT_BITS 7) / X */
    S[0] = x0;
    S[1] = x1;
    S[2] = x2;
    S[3] = x3;
    S[4] = x4;
    S[5] = x5;
    S[6] = x6;
    S[7] = 1;
    nz = (y0 != 0) | (y1 != 0) | (y2 != 0) | (y3 != 0) | (y4 != 0) | (y5 != 0) | (y6 != 0);
    if (nz)
    {
        nd[0] = 0;
        nd[1] = 0;
        nd[2] = 0;
        nd[3] = 0;
        nd[4] = 0;
        nd[5] = 0;
        nd[6] = 0;
        nd[7] = y0;
        nd[8] = y1;
        nd[9] = y2;
        nd[10] = y3;
        nd[11] = y4;
        nd[12] = y5;
        nd[13] = y6;
        mpn_tdiv_qr(t, nd, 0, nd, 14, S, 8);
    }
    else
    {
        t[0] = 0;
        t[1] = 0;
        t[2] = 0;
        t[3] = 0;
        t[4] = 0;
        t[5] = 0;
        t[6] = 0;
    }

    _fixed_atan_series_7(q, t);

    add_sssssssaaaaaaaaaaaaaa(a6, a5, a4, a3, a2, a1, a0,
        a6, a5, a4, a3, a2, a1, a0,
        q[6], q[5], q[4], q[3], q[2], q[1], q[0]);
    res[0] = a0;
    res[1] = a1;
    res[2] = a2;
    res[3] = a3;
    res[4] = a4;
    res[5] = a5;
    res[6] = a6;
}


#endif /* FLINT_BITS == 64 */
