/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

#include "flint.h"
#include "mpn_extras.h"
#include "fixed.h"

/* quotient length from which the argument-reduction division runs
   through fixed_div_newton instead of mpn_tdiv_qr; set from
   in-context measurements (tight-loop benchmarks favor Newton much
   earlier, but embedded in the evaluation it loses until the FFT
   range, see dev/notes) */
#ifndef FIXED_RED_DIV_NEWTON_CUTOFF
#define FIXED_RED_DIV_NEWTON_CUTOFF 60
#endif

/* atan(t) for t in [0, 1) by greedy vectoring (the trigonometric
   analog of the fixed_log1p_bitwise_rs reduction): the vector
   (X, Y) = (1, t) is rotated towards the real axis by the factors
   (1 - i 2^-i), i = 1..r, applying a factor -- i.e.
   (X, Y) <- (X + Y 2^-i, Y - X 2^-i), two shifts and two
   add/subtracts on the old values -- whenever it keeps Y >= 0, that
   is whenever Y >= X 2^-i.  This is a greedy on the angle
   atan(Y/X) with steps atan(2^-i); concavity of atan gives
   atan(2^-(i-1)) < 2 atan(2^-i), so each factor is used at most
   once, one extra conditional step at i = r absorbs the truncation
   creep, and afterwards atan(Y/X) < atan(2^-r) < 2^-r.  The angle
   is scale invariant, so the growth of |Z| (bounded by
   prod sqrt(1 + 4^-i) < 1.1644, keeping X in [1, 2) with its units
   limb fixed at 1) needs no compensation.

   Decisions run one FLINT_BITS window at a time on a single-limb
   model as in log: h is Y's window limb and
   lt = MPN_RIGHT_SHIFT_LOW(X[n], X[n-1], i mod FLINT_BITS) the
   window limb of X >> i, computable from X's top two limbs alone;
   accepted factors update Y immediately, so the model resyncs
   exactly and the ambiguity band degenerates to h == lt.  As in
   log, the residual obeys only Y < X 2^-i < 2^(1-i), so a stray bit
   above the window forces a certain accept.

   The used indices are recorded and the tabulated angles
   A_i = atan(2^-i) -- the same table the rotation reduction of
   sin/cos uses (there against x/2) -- are simply summed afterwards;
   the total is below sum_{i>=1} A_i ~ 0.8980 < 1, so an n-limb
   accumulator suffices and no rescaling is needed.  The residual
   needs ONE division t' = Y/X < 2^-r, meeting the atan series
   contract.

   Error accounting (output ulp 2^(-FLINT_BITS n)): at most r + 1
   table entries, each short by < 1 ulp; each accepted
   factor truncates X and Y by < 1 ulp each, perturbing the residual
   angle by < 2 ulp per accept; the halving, the division floor and
   the series error (<= 15 ulp two-sided) are constants.  Total
   below FIXED_ATAN_BITWISE_RS_MAX_ERR(n, r) = 4 r + 64. */

#define ATANS_A(i) (tab + (i) * nc)

/* smallest n at which each reduction parameter becomes optimal
   (generated by src/fixed/tune/tune-bitwise-r.c with nmax deep enough
   to reach the r = 768 end of the ladder; x86-64 defaults) */
static const int _fixed_atan_bitwise_rs_r_tab[] =
    {32, 64, 128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768};
static const short _fixed_atan_bitwise_rs_n_tab[] =
    {1, 18, 75, 100, 188, 416, 533, 534, 536, 606, 689, 980, 1483};

int
fixed_atan_bitwise_rs_default_r(slong n)
{
    slong j;

#if FLINT_BITS == 64
    /* the compile-time constants of the specialized per-size files:
       keep in sync with the dev/tune_fixed.py --pin values that
       emitted them */
    static const int opt_r[] = {0, 4, 6, 22, 20, 18, 20, 19};
    if (n <= 7)
        return opt_r[n];
#endif

    for (j = 0; j + 1 < (slong) (sizeof(_fixed_atan_bitwise_rs_n_tab) / sizeof(short))
            && n >= _fixed_atan_bitwise_rs_n_tab[j + 1]; j++)
        ;
    return _fixed_atan_bitwise_rs_r_tab[j];
}

#if FLINT_BITS == 64
#endif

void
fixed_atan_bitwise_rs(nn_ptr res, nn_srcptr x, slong n, int r)
{
#if FLINT_BITS == 64
    int r0;
#endif
    slong i, c, wn, nc, num, j, qr, ds;
    nn_ptr X, Y, vx, vy, acc, t, y, nd;
    slong * used;
    TMP_INIT;

    FLINT_ASSERT(n >= 1);
    FLINT_ASSERT(r == 0 || r >= 32);
    /* n = 1 is unsupported on 32-bit limbs: the clamp below would
       drop r under the r >= 32 contract of the residual series */
    FLINT_ASSERT(FLINT_BITS == 64 || n >= 2);

#if FLINT_BITS == 64
    r0 = r;
#endif

    if (r == 0)
        r = fixed_atan_bitwise_rs_default_r(n);

    /* the residual series contract is r >= 32 */
    r = FLINT_MAX(r, 32);
    r = FLINT_MIN((slong) r, FLINT_BITS * n - 16);

#if FLINT_BITS == 64
    /* fully specialized per-size implementations (atan_opt_<n>.c,
       emitted and tuned by dev/tune_fixed.py): with r = 0 the caller
       has left the reduction parameter to us, and the whole call
       collapses to straight-line code with a compile-time r and the
       series built for it */
    if (r0 == 0 && n <= 7)
    {
        static void (* const tab[])(nn_ptr, nn_srcptr) = {
            NULL, fixed_atan_opt_1, fixed_atan_opt_2, fixed_atan_opt_3,
            fixed_atan_opt_4, fixed_atan_opt_5, fixed_atan_opt_6,
            fixed_atan_opt_7
        };
        tab[n](res, x);
        return;
    }
#endif

    wn = n + 1;

    nn_srcptr tab;
    tab = _fixed_atans_tab(n, r, &nc);

    TMP_START;
    X = TMP_ALLOC((wn + n + wn + wn + wn + n + n + 2 * n + 2)
        * sizeof(ulong));
    Y = X + wn;
    vx = Y + n;
    vy = vx + wn;
    acc = vy + wn;
    t = acc + wn;
    nd = t + n + n;
    used = TMP_ALLOC(FIXED_BITWISE_REDUCE_USED_ALLOC(r) * sizeof(slong));

    /* X = 1, Y = t */
    flint_mpn_zero(X, n);
    X[n] = 1;
    flint_mpn_copyi(Y, x, n);
    num = 0;

/* materialize v = trunc(X >> ii) into vx (the leading unit of X
   lands inside the fraction for b == 0 boundaries) and
   trunc(Y >> ii) into vy, both as n-limb fractions */
#define MAKE_V(ii) \
    do { \
        slong q_ = (ii) / FLINT_BITS, b_ = (ii) - q_ * FLINT_BITS; \
        flint_mpn_zero(vx, n); \
        flint_mpn_zero(vy, n); \
        if (b_ != 0) \
        { \
            mpn_rshift(vx, X + q_, wn - q_, (int) b_); \
            if (n - q_ > 0) \
                mpn_rshift(vy, Y + q_, n - q_, (int) b_); \
        } \
        else \
        { \
            flint_mpn_copyi(vx, X + q_, wn - q_); \
            if (n - q_ > 0) \
                flint_mpn_copyi(vy, Y + q_, n - q_); \
        } \
    } while (0)

/* accept factor ii (v's already made): X += vy, Y -= vx */
#define APPLY(ii) \
    do { \
        mpn_add(X, X, wn, vy, n); \
        mpn_sub_n(Y, Y, vx, n); \
        used[num++] = (ii); \
    } while (0)

/* exact compare-accept: Y >= trunc(X >> ii)? */
#define EXACT_STEP(ii) \
    do { \
        MAKE_V(ii); \
        if (mpn_cmp(Y, vx, n) >= 0) \
            APPLY(ii); \
    } while (0)

    for (c = 0; FLINT_BITS * c <= r; c++)
    {
        slong i0 = (c == 0) ? 1 : FLINT_BITS * c;
        slong i1 = FLINT_MIN((slong) r, FLINT_BITS * (c + 1) - 1);
        ulong h;

        /* i0 <= r always: for c = 0 because r >= 32, and for
           c >= 1 by the loop condition */
        EXACT_STEP(i0);

        h = Y[n - 1 - c];

        for (i = i0 + 1; i <= i1; i++)
        {
            slong b = i - FLINT_BITS * c;
            ulong lt;

            /* stray bit above the window: certain accept, since
               then Y >= 2^(1 - i) b-shifted > X 2^-i */
            if (c > 0 && Y[n - c] != 0)
            {
                MAKE_V(i);
                APPLY(i);
                h = Y[n - 1 - c];
                continue;
            }

            lt = MPN_RIGHT_SHIFT_LOW(X[n], X[n - 1], (int) b);

            if (h > lt)
            {
                MAKE_V(i);
                APPLY(i);
                h = Y[n - 1 - c];
            }
            else if (h == lt)
            {
                EXACT_STEP(i);
                h = Y[n - 1 - c];
            }
            /* else certain reject */
        }
    }

    /* extra steps at i = r absorb the truncation creep, restoring
       Y < trunc(X >> r) <= X 2^-r, i.e. the residual angle below
       atan(2^-r): the series contract.  X grows with each accepted
       factor, so the comparison is recomputed each time. */
    for (;;)
    {
        slong num_before = num;

        EXACT_STEP(r);
        if (num == num_before)
            break;
    }

#undef MAKE_V
#undef APPLY
#undef EXACT_STEP

    /* sum the table entries: the total is below 0.898 < 1, so no
       carry limb is needed */
    flint_mpn_zero(acc, n);
    for (j = 0; j < num; j++)
        mpn_add_n(acc, acc, ATANS_A(used[j]) + (nc - n), n);

    /* t' = Y / X < 2^-r: one division, X in [1, 2) with the top
       limb X[n] = 1 */
    qr = 0;
    while (qr < n && Y[n - 1 - qr] == 0)
        qr++;
    ds = 2 * n - qr;
    flint_mpn_zero(t, n);
    if (ds >= wn && qr < n)
    {
        flint_mpn_zero(nd, n);
        flint_mpn_copyi(nd + n, Y, n - qr);
        if (ds - wn + 1 < FIXED_RED_DIV_NEWTON_CUTOFF)
        {
            mpn_tdiv_qr(t, nd, 0, nd, ds, X, wn);
        }
        else
        {
            /* Same quotient by Karp-Markstein division: numerator
               and divisor read as fractions (the numerator's n low
               limbs are zero, so pass only its significant top
               part), quotient computed with k + 1 fraction limbs, k
               the quotient length.  Truncating the two guard limbs
               leaves t within 1 + eps ulps of the floored quotient
               (eps = 4 B^(-1) / a' < 2^-62), which the series
               argument budget absorbs like the tdiv floor. */
            slong k = ds - wn + 1;
            nn_ptr q = TMP_ALLOC((k + 4) * sizeof(ulong));
            fixed_div_newton(q, nd + n, ds - n, X, wn, k + 1);
            flint_mpn_copyi(t, q + 2, k);
        }
    }

    /* res = acc + atan(t') (the series does not support aliased
       output) */
    y = t + n;
    fixed_atan_rs(y, t, n);
    mpn_add_n(res, acc, y, n);

    TMP_END;
}
