/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* GENERATED by dev/tune_fixed.py (atan, n = 2, r = 6) -- do not
   edit directly; retune or re-emit with
       python3 dev/tune_fixed.py atan 2 --pin 6 --emit */

#include "flint.h"
#include "longlong.h"
#include "mpn_extras.h"
#include "fixed.h"
#include "impl.h"
#include "hand_mulhi.inc"

#if FLINT_BITS == 64

/* atan, n = 2, r = 6: 9 levels, widths [2, 2, 2, 2, 1, 1, 1, 1, 1] */
static void
_fixed_atan_series_2(nn_ptr res, nn_srcptr x)
{
    ulong z[2], V[2], T[2], P[2], Z[2];
    ulong v, w1, w0, h, l;
    slong i;

    (void) v; (void) w1; (void) w0; (void) h; (void) l;
    (void) i; (void) Z; (void) V; (void) T; (void) P;

    _fixed_sqrhi_2x2(&z[1], &z[0], x[1], x[0]);

    v = UWORD(0x0d79435e50d79435);

    /* V_7 = c - z V_8   (1 x 1 limbs) */
    v = n_mulhi(z[1], v);
    v = UWORD(0x0f0f0f0f0f0f0f0f) - v;

    /* V_6 = c - z V_7   (1 x 1 limbs) */
    v = n_mulhi(z[1], v);
    v = UWORD(0x1111111111111111) - v;

    /* V_5 = c - z V_6   (1 x 1 limbs) */
    v = n_mulhi(z[1], v);
    v = UWORD(0x13b13b13b13b13b1) - v;

    /* V_4 = c - z V_5   (1 x 1 limbs) */
    v = n_mulhi(z[1], v);
    v = UWORD(0x1745d1745d1745d1) - v;

    /* V_3 = c - z V_4   (2 x 1 limbs) */
    _fixed_mulhi_2x1(&h, &l, z[1], z[0], v);
    sub_ddmmss(w1, w0, UWORD(0x1c71c71c71c71c71), UWORD(0xc71c71c71c71c71c), h, l);

    /* V_2 = c - z V_3   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[1], z[0], w1, w0);
    sub_ddmmss(w1, w0, UWORD(0x2492492492492492), UWORD(0x4924924924924924), h, l);

    /* V_1 = c - z V_2   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[1], z[0], w1, w0);
    sub_ddmmss(w1, w0, UWORD(0x3333333333333333), UWORD(0x3333333333333333), h, l);

    /* V_0 = c - z V_1   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[1], z[0], w1, w0);
    sub_ddmmss(w1, w0, UWORD(0x5555555555555555), UWORD(0x5555555555555555), h, l);

    /* atan = x - x^3 V_0 */
    P[0] = w0; P[1] = w1;
    _fixed_mulhi_2x2_sloppy(&T[1], &T[0], z[1], z[0], x[1], x[0]);
    _fixed_mulhi_2x2_sloppy(&V[1], &V[0], T[1], T[0], P[1], P[0]);
    NN_SUB_2(res, x, V);
}

void
fixed_atan_opt_2(nn_ptr res, nn_srcptr x)
{
    const int r = 6;
    ulong x0, x1;
    ulong y0, y1;
    ulong a0, a1;
    ulong e0, e1;
    ulong v0, v1;
    ulong w0, w1;
    ulong bw, m, h, lt;
    ulong S[3], nd[4], t[2], q[2];
    slong i, nc;
    int nz;


    _fixed_atans_ensure(2, r);
    nc = _fixed_atans_n;

    x0 = 0;
    x1 = 0;
    y0 = x[0];
    y1 = x[1];
    a0 = 0;
    a1 = 0;

#define AP(ii) (_fixed_atans + (ii) * nc + (nc - 2))

    /* window 0 */
    {
        nn_srcptr Ap;

        /* boundary step i = 1 */
        Ap = AP(1);
        v0 = MPN_RIGHT_SHIFT_LOW(x1, x0, 1);
        v1 = MPN_RIGHT_SHIFT_LOW(UWORD(1), x1, 1);
        w0 = MPN_RIGHT_SHIFT_LOW(y1, y0, 1);
        w1 = MPN_RIGHT_SHIFT_LOW(UWORD(0), y1, 1);
        sub_dddmmmsss(bw, e1, e0,
            UWORD(0), y1, y0,
            UWORD(0), v1, v0);
        m = ~bw;                /* accept iff no borrow */
        add_ssaaaa(x1, x0,
            x1, x0,
            (w1) & m, (w0) & m);
        add_ssaaaa(a1, a0,
            a1, a0,
            Ap[1] & m, Ap[0] & m);
        y0 = (y0 & bw) | (e0 & m);
        y1 = (y1 & bw) | (e1 & m);

        h = y1;

        for (i = 2; i <= 6; i++)
        {
            int b = (int) (i - 0);

            lt = MPN_RIGHT_SHIFT_LOW(UWORD(1), x1, b);
            if (h < lt)
                continue;    /* certain reject */

            Ap = AP(i);
            v0 = MPN_RIGHT_SHIFT_LOW(x1, x0, b);
            v1 = lt;
            w0 = MPN_RIGHT_SHIFT_LOW(y1, y0, b);
            w1 = MPN_RIGHT_SHIFT_LOW(UWORD(0), y1, b);
            sub_dddmmmsss(bw, e1, e0,
                UWORD(0), y1, y0,
                UWORD(0), v1, v0);
            m = ~bw;                /* accept iff no borrow */
            add_ssaaaa(x1, x0,
                x1, x0,
                (w1) & m, (w0) & m);
            add_ssaaaa(a1, a0,
                a1, a0,
                Ap[1] & m, Ap[0] & m);
            y0 = (y0 & bw) | (e0 & m);
            y1 = (y1 & bw) | (e1 & m);
            h = y1;
        }
    }

    /* the step at i = r restores Y < trunc(X >> r) <= X 2^-r;
       entering it Y < X 2^-(r-1), so two passes suffice */
    for (nz = 0; nz < 2; nz++)
    {
        nn_srcptr Ap = AP((slong) r);
        const int b = 6;

        lt = MPN_RIGHT_SHIFT_LOW(UWORD(1), x1, b);
        v0 = MPN_RIGHT_SHIFT_LOW(x1, x0, b);
        v1 = lt;
        w0 = MPN_RIGHT_SHIFT_LOW(y1, y0, b);
        w1 = MPN_RIGHT_SHIFT_LOW(UWORD(0), y1, b);
        sub_dddmmmsss(bw, e1, e0,
            UWORD(0), y1, y0,
            UWORD(0), v1, v0);
        m = ~bw;                /* accept iff no borrow */
        add_ssaaaa(x1, x0,
            x1, x0,
            (w1) & m, (w0) & m);
        add_ssaaaa(a1, a0,
            a1, a0,
            Ap[1] & m, Ap[0] & m);
        y0 = (y0 & bw) | (e0 & m);
        y1 = (y1 & bw) | (e1 & m);
    }

#undef AP

    /* t = Y 2^(FLINT_BITS 2) / X */
    S[0] = x0;
    S[1] = x1;
    S[2] = 1;
    nz = (y0 != 0) | (y1 != 0);
    if (nz)
    {
        nd[0] = 0;
        nd[1] = 0;
        nd[2] = y0;
        nd[3] = y1;
        mpn_tdiv_qr(t, nd, 0, nd, 4, S, 3);
    }
    else
    {
        t[0] = 0;
        t[1] = 0;
    }

    _fixed_atan_series_2(q, t);

    add_ssaaaa(a1, a0,
        a1, a0,
        q[1], q[0]);
    res[0] = a0;
    res[1] = a1;
}


#endif /* FLINT_BITS == 64 */
