/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* GENERATED by dev/tune_fixed.py (exp, n = 1, r = 12) -- do not
   edit directly; retune or re-emit with
       python3 dev/tune_fixed.py exp 1 --pin 12 --emit */

#include "flint.h"
#include "longlong.h"
#include "mpn_extras.h"
#include "fixed.h"
#include "impl.h"
#include "hand_mulhi.inc"

#if FLINT_BITS == 64

#ifndef FIXED_EXP_E2
#define FIXED_EXP_E2 UWORD(0x8000000000000000)
#define FIXED_EXP_E3 UWORD(0x2aaaaaaaaaaaaaaa)
#define FIXED_EXP_E4 UWORD(0x0aaaaaaaaaaaaaaa)
#define FIXED_EXP_E5 UWORD(0x0222222222222222)
#define FIXED_EXP_E6 UWORD(0x005b05b05b05b05b)
#define FIXED_EXP_E7 UWORD(0x000d00d00d00d00d)
#define FIXED_EXP_D2_HI UWORD(0x8000000000000000)
#define FIXED_EXP_D2_LO UWORD(0x0000000000000000)
#define FIXED_EXP_D3_HI UWORD(0x2aaaaaaaaaaaaaaa)
#define FIXED_EXP_D3_LO UWORD(0xaaaaaaaaaaaaaaaa)
#define FIXED_EXP_G8  UWORD(0x0001a01a01a01a01)
#define FIXED_EXP_G9  UWORD(0x00002e3bc74aad8e)
#define FIXED_EXP_G10 UWORD(0x0000049f93edde27)
#define FIXED_EXP_H4_HI UWORD(0x0aaaaaaaaaaaaaaa)
#define FIXED_EXP_H4_LO UWORD(0xaaaaaaaaaaaaaaaa)
#define FIXED_EXP_H5_HI UWORD(0x0222222222222222)
#define FIXED_EXP_H5_LO UWORD(0x2222222222222222)
#define FIXED_EXP_H6_HI UWORD(0x005b05b05b05b05b)
#define FIXED_EXP_H6_LO UWORD(0x05b05b05b05b05b0)
#define FIXED_EXP_H7_HI UWORD(0x000d00d00d00d00d)
#define FIXED_EXP_H7_LO UWORD(0x00d00d00d00d00d0)
#endif
/* exp(x), x < 2^-12, one fraction limb.  N = 4 terms: the dropped
   x^5/5! is about 2^-67, below the 2^-64 output ulp.  Written as
   1 + x + x^2 (C2 + x C3 + x^2 C4), reusing x^2 so that the two small
   terms are formed independently rather than in a serial chain. */
static void
_fixed_exp_series_1(nn_ptr res, nn_srcptr x)
{
    ulong X = x[0], x2, p, h, l;

    x2 = n_mulhi(X, X);
    p = FIXED_EXP_E2 + n_mulhi(X, FIXED_EXP_E3)
                     + n_mulhi(x2, FIXED_EXP_E4);
    p = n_mulhi(x2, p);

    add_ssaaaa(h, l, UWORD(0), X, UWORD(0), p);
    res[0] = l;
    res[1] = 1 + h;
}
void
fixed_exp_opt_1(nn_ptr res, nn_srcptr x)
{
    const int r = 12;
    slong i, j, num, bj, nc;
    ulong t0, bw, h, e;
    ulong d0;
    ulong y0, y1;
    ulong s0, s1;
    ulong ts[1], ys[3], sh[2];
    slong used[1 * FLINT_BITS + 2];


    _fixed_exp_logs_ensure(1, r);
    nc = _fixed_exp_logs_n;

    t0 = x[0];

/* exact compare-subtract of L_ii, recording the index */
#define STEP(ii) \
    do { \
        nn_srcptr Lq = _fixed_exp_logs + (ii) * nc + (nc - 1); \
        sub_ddmmss(bw, d0, \
            UWORD(0), t0, \
            UWORD(0), Lq[0]); \
        t0 = (t0 & bw) | (d0 & ~bw); \
        used[num] = (ii); \
        num += (bw == 0); \
    } while (0)

/* apply the pending recorded subtractions */
#define FLUSH() \
    for (; bj < num; bj++) \
    { \
        nn_srcptr Lq = _fixed_exp_logs + used[bj] * nc + (nc - 1); \
        t0 -= Lq[0]; \
    }

    num = 0;
    bj = 0;

    for (i = 0; i <= r; i++)
        STEP(i);
    bj = num;
    (void) h; (void) e;

    FLUSH();

    /* one extra subtraction restores t < L_r < 2^-r */
    STEP(r);

#undef STEP
#undef FLUSH

    /* exp of the reduced argument */
    ts[0] = t0;
    _fixed_exp_series_1(ys, ts);
    y0 = ys[0];
    y1 = ys[1];

    j = 0;

    if (num > 0 && used[0] == 0)
    {
        add_ssaaaa(y1, y0,
            y1, y0, y1, y0);
        j = 1;
    }

    for (; j < num && used[j] < FLINT_BITS; j++)
    {
        int b = (int) used[j];

        s0 = MPN_RIGHT_SHIFT_LOW(y1, y0, b);
        s1 = y1 >> b;
        add_ssaaaa(y1, y0,
            y1, y0, s1, s0);
    }

    ys[0] = y0;
    ys[1] = y1;

    /* rare factors with i >= FLINT_BITS */
    if (j < num)
        _fixed_exp_recon(ys, sh, 2, used, j, num);

    res[0] = ys[0];
    res[1] = ys[1];
}


#endif /* FLINT_BITS == 64 */
