/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* GENERATED by dev/tune_fixed.py (exp, n = 7, r = 32) -- do not
   edit directly; retune or re-emit with
       python3 dev/tune_fixed.py exp 7 --pin 32 --emit */

#include "flint.h"
#include "longlong.h"
#include "mpn_extras.h"
#include "fixed.h"
#include "hand_mulhi.inc"

#if FLINT_BITS == 64

/* n = 7, r = 32: N = 13 terms; level widths V2:6 V3:6 V4:5 V5:5 V6:4 V7:4 V8:3 V9:3 V10:2 V11:2 V12:1 */
static void
_fixed_exp_series_7(nn_ptr res, nn_srcptr x)
{
    ulong v, w1, w0, h, l, cy;
    ulong A[7], B[7], T[7], x2[7];
    ulong X2 = x[6], X1 = x[5];

    (void) v; (void) w1; (void) w0; (void) h; (void) l;

    v = UWORD(0x00000008f76c77fc);

    /* V_11 = C_11 + x V_12  (2 x 1) */
    _fixed_mulhi_2x1(&h, &l, X2, X1, v);
    add_ssaaaa(w1, w0, UWORD(0x0000006b99159fd5), UWORD(0x138e3f9d1f92e0df), h, l);

    /* V_10 = C_10 + x V_11  (2 x 2) */
    _fixed_mulhi_2x2_sloppy(&h, &l, X2, X1, w1, w0);
    add_ssaaaa(w1, w0, UWORD(0x0000049f93edde27), UWORD(0xd71cbbc05b4fa999), h, l);

    /* V_9 = C_9 + x V_10  (3 x 2) */
    _fixed_mulhi_3x2(&A[2], &A[1], &A[0], x[6], x[5], x[4],
        w1, w0);
    B[0] = UWORD(0xe3bc74aad8e671f5);
    B[1] = UWORD(0x671f5583911ca002);
    B[2] = UWORD(0x00002e3bc74aad8e);
    mpn_add_n(A, A, B, 3);

    /* V_8 = C_8 + x V_9  (3 x 3) */
    flint_mpn_mulhigh_n(T, x + 4, A, 3);
    B[0] = UWORD(0x01a01a01a01a01a0);
    B[1] = UWORD(0xa01a01a01a01a01a);
    B[2] = UWORD(0x0001a01a01a01a01);
    mpn_add_n(A, T, B, 3);

    /* V_7 = C_7 + x V_8  (4 x 3) */
    B[0] = UWORD(0);
    B[1] = A[0];
    B[2] = A[1];
    B[3] = A[2];
    flint_mpn_mulhigh_n(T, x + 3, B, 4);
    B[0] = UWORD(0xd00d00d00d00d00d);
    B[1] = UWORD(0x0d00d00d00d00d00);
    B[2] = UWORD(0x00d00d00d00d00d0);
    B[3] = UWORD(0x000d00d00d00d00d);
    mpn_add_n(A, T, B, 4);

    /* V_6 = C_6 + x V_7  (4 x 4) */
    flint_mpn_mulhigh_n(T, x + 3, A, 4);
    B[0] = UWORD(0xb05b05b05b05b05b);
    B[1] = UWORD(0x5b05b05b05b05b05);
    B[2] = UWORD(0x05b05b05b05b05b0);
    B[3] = UWORD(0x005b05b05b05b05b);
    mpn_add_n(A, T, B, 4);

    /* V_5 = C_5 + x V_6  (5 x 4) */
    B[0] = UWORD(0);
    B[1] = A[0];
    B[2] = A[1];
    B[3] = A[2];
    B[4] = A[3];
    flint_mpn_mulhigh_n(T, x + 2, B, 5);
    B[0] = UWORD(0x2222222222222222);
    B[1] = UWORD(0x2222222222222222);
    B[2] = UWORD(0x2222222222222222);
    B[3] = UWORD(0x2222222222222222);
    B[4] = UWORD(0x0222222222222222);
    mpn_add_n(A, T, B, 5);

    /* V_4 = C_4 + x V_5  (5 x 5) */
    flint_mpn_mulhigh_n(T, x + 2, A, 5);
    B[0] = UWORD(0xaaaaaaaaaaaaaaaa);
    B[1] = UWORD(0xaaaaaaaaaaaaaaaa);
    B[2] = UWORD(0xaaaaaaaaaaaaaaaa);
    B[3] = UWORD(0xaaaaaaaaaaaaaaaa);
    B[4] = UWORD(0x0aaaaaaaaaaaaaaa);
    mpn_add_n(A, T, B, 5);

    /* V_3 = C_3 + x V_4  (6 x 5) */
    B[0] = UWORD(0);
    B[1] = A[0];
    B[2] = A[1];
    B[3] = A[2];
    B[4] = A[3];
    B[5] = A[4];
    flint_mpn_mulhigh_n(T, x + 1, B, 6);
    B[0] = UWORD(0xaaaaaaaaaaaaaaaa);
    B[1] = UWORD(0xaaaaaaaaaaaaaaaa);
    B[2] = UWORD(0xaaaaaaaaaaaaaaaa);
    B[3] = UWORD(0xaaaaaaaaaaaaaaaa);
    B[4] = UWORD(0xaaaaaaaaaaaaaaaa);
    B[5] = UWORD(0x2aaaaaaaaaaaaaaa);
    mpn_add_n(A, T, B, 6);

    /* V_2 = C_2 + x V_3  (6 x 6) */
    flint_mpn_mulhigh_n(T, x + 1, A, 6);
    B[0] = UWORD(0x0000000000000000);
    B[1] = UWORD(0x0000000000000000);
    B[2] = UWORD(0x0000000000000000);
    B[3] = UWORD(0x0000000000000000);
    B[4] = UWORD(0x0000000000000000);
    B[5] = UWORD(0x8000000000000000);
    mpn_add_n(A, T, B, 6);

    /* x^2 V_2 */
    B[0] = UWORD(0);
    B[1] = A[0];
    B[2] = A[1];
    B[3] = A[2];
    B[4] = A[3];
    B[5] = A[4];
    B[6] = A[5];
    flint_mpn_sqrhigh(x2, x, 7);
    flint_mpn_mulhigh_n(T, x2, B, 7);
    cy = mpn_add_n(res, x, T, 7);
    res[7] = 1 + cy;
}

void
fixed_exp_opt_7(nn_ptr res, nn_srcptr x)
{
    const int r = 32;
    slong i, j, num, bj, nc;
    ulong t0, t1, t2, t3, t4, t5, t6, bw, h, e;
    ulong d0, d1, d2, d3, d4, d5, d6;
    ulong y0, y1, y2, y3, y4, y5, y6, y7;
    ulong s0, s1, s2, s3, s4, s5, s6, s7;
    ulong ts[7], ys[9], sh[8];
    slong used[7 * FLINT_BITS + 2];


    nn_srcptr tab;
    tab = _fixed_exp_logs_tab(7, r, &nc);

    t0 = x[0];
    t1 = x[1];
    t2 = x[2];
    t3 = x[3];
    t4 = x[4];
    t5 = x[5];
    t6 = x[6];

/* exact compare-subtract of L_ii, recording the index */
#define STEP(ii) \
    do { \
        nn_srcptr Lq = tab + (ii) * nc + (nc - 7); \
        sub_ddddddddmmmmmmmmssssssss(bw, d6, d5, d4, d3, d2, d1, d0, \
            UWORD(0), t6, t5, t4, t3, t2, t1, t0, \
            UWORD(0), Lq[6], Lq[5], Lq[4], Lq[3], Lq[2], Lq[1], Lq[0]); \
        t0 = (t0 & bw) | (d0 & ~bw); \
        t1 = (t1 & bw) | (d1 & ~bw); \
        t2 = (t2 & bw) | (d2 & ~bw); \
        t3 = (t3 & bw) | (d3 & ~bw); \
        t4 = (t4 & bw) | (d4 & ~bw); \
        t5 = (t5 & bw) | (d5 & ~bw); \
        t6 = (t6 & bw) | (d6 & ~bw); \
        used[num] = (ii); \
        num += (bw == 0); \
    } while (0)

/* apply the pending recorded subtractions */
#define FLUSH() \
    for (; bj < num; bj++) \
    { \
        nn_srcptr Lq = tab + used[bj] * nc + (nc - 7); \
        sub_dddddddmmmmmmmsssssss(t6, t5, t4, t3, t2, t1, t0, \
            t6, t5, t4, t3, t2, t1, t0, \
            Lq[6], Lq[5], Lq[4], Lq[3], Lq[2], Lq[1], Lq[0]); \
    }

    num = 0;
    bj = 0;

/* one reduction window: decisions on the single-limb model
   hreg, exact steps at the boundary and inside the ambiguity
   band (see _fixed_exp_reduce) */
#define WINDOW(cc, hreg) \
    do { \
        { \
            slong i1 = FLINT_MIN((slong) r, \
                FLINT_BITS * ((cc) + 1) - 1); \
            nn_srcptr lp; \
            FLUSH(); \
            STEP(FLINT_BITS * (cc)); \
            bj = num; \
            h = hreg; \
            e = 0; \
            lp = tab + (FLINT_BITS * (cc) + 1) * nc \
                + (nc - 1 - (cc)); \
            for (i = FLINT_BITS * (cc) + 1; i <= i1; i++, lp += nc) \
            { \
                ulong lt = lp[0]; \
                if (h - lt + e <= 2 * e) \
                { \
                    FLUSH(); \
                    STEP(i); \
                    bj = num; \
                    h = hreg; \
                    e = 0; \
                } \
                else \
                { \
                    ulong sub = (h > lt); \
                    h -= (lt + 1) & (-sub); \
                    used[num] = i; \
                    num += sub; \
                    e += sub; \
                } \
            } \
        } \
    } while (0)

    WINDOW(0, t6);

#undef WINDOW

    FLUSH();

    /* one extra subtraction restores t < L_r < 2^-r */
    STEP(r);

#undef STEP
#undef FLUSH

    /* exp of the reduced argument */
    ts[0] = t0;
    ts[1] = t1;
    ts[2] = t2;
    ts[3] = t3;
    ts[4] = t4;
    ts[5] = t5;
    ts[6] = t6;
    _fixed_exp_series_7(ys, ts);
    y0 = ys[0];
    y1 = ys[1];
    y2 = ys[2];
    y3 = ys[3];
    y4 = ys[4];
    y5 = ys[5];
    y6 = ys[6];
    y7 = ys[7];

    j = 0;

    if (num > 0 && used[0] == 0)
    {
        add_ssssssssaaaaaaaaaaaaaaaa(y7, y6, y5, y4, y3, y2, y1, y0,
            y7, y6, y5, y4, y3, y2, y1, y0, y7, y6, y5, y4, y3, y2, y1, y0);
        j = 1;
    }

    for (; j < num && used[j] < FLINT_BITS; j++)
    {
        int b = (int) used[j];

        s0 = MPN_RIGHT_SHIFT_LOW(y1, y0, b);
        s1 = MPN_RIGHT_SHIFT_LOW(y2, y1, b);
        s2 = MPN_RIGHT_SHIFT_LOW(y3, y2, b);
        s3 = MPN_RIGHT_SHIFT_LOW(y4, y3, b);
        s4 = MPN_RIGHT_SHIFT_LOW(y5, y4, b);
        s5 = MPN_RIGHT_SHIFT_LOW(y6, y5, b);
        s6 = MPN_RIGHT_SHIFT_LOW(y7, y6, b);
        s7 = y7 >> b;
        add_ssssssssaaaaaaaaaaaaaaaa(y7, y6, y5, y4, y3, y2, y1, y0,
            y7, y6, y5, y4, y3, y2, y1, y0, s7, s6, s5, s4, s3, s2, s1, s0);
    }

    ys[0] = y0;
    ys[1] = y1;
    ys[2] = y2;
    ys[3] = y3;
    ys[4] = y4;
    ys[5] = y5;
    ys[6] = y6;
    ys[7] = y7;

    /* rare factors with i >= FLINT_BITS */
    if (j < num)
        _fixed_exp_recon(ys, sh, 8, used, j, num);

    res[0] = ys[0];
    res[1] = ys[1];
    res[2] = ys[2];
    res[3] = ys[3];
    res[4] = ys[4];
    res[5] = ys[5];
    res[6] = ys[6];
    res[7] = ys[7];
}


#endif /* FLINT_BITS == 64 */
