/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

#include "flint.h"
#include "mpn_extras.h"
#include "fixed.h"

/* quotient length from which the argument-reduction division runs
   through fixed_div_newton instead of mpn_tdiv_qr; set from
   in-context measurements (tight-loop benchmarks favor Newton much
   earlier, but embedded in the evaluation it loses until the FFT
   range, see dev/notes) */
#ifndef FIXED_RED_DIV_NEWTON_CUTOFF
#define FIXED_RED_DIV_NEWTON_CUTOFF 60
#endif

/* log(1 + x) by the dual of the bitwise exp reduction (the L-mode
   BKM recurrence): greedily multiply P (starting from 1) by factors
   1 + 2^-i, i = 1..r, while P (1 + 2^-i) <= X = 1 + x.  This greedy
   is exactly the exp reduction applied to log(X/P), so each factor
   is used at most once (L_{i-1} < 2 L_i), one extra conditional step
   at i = r absorbs the truncation creep, and afterwards
   X/P in [1, 1 + 2^-r).  The same cached table of
   L_i = log(1 + 2^-i) serves both directions.

   The residual is obtained by fusing the normalization with the
   atanh transformation: log(X/P) = 2 atanh((X - P)/(X + P)), where
   the numerator is the deficit D = X - P (maintained exactly through
   the reduction) and the single division by S = X + P in [2, 4)
   yields t = D/S < 2^-r, meeting the atanh series contract directly;
   the odd atanh series needs half the terms of log(1 + u).  Finally
   log X = sum of used L_i + 2 atanh(t).

   Decisions run one FLINT_BITS window at a time on a single-limb
   model, as in exp: h is the deficit's window limb and
   lt = MPN_RIGHT_SHIFT_LOW(P[n], P[n-1], i mod FLINT_BITS) is the
   window limb of P >> i, computable from P's top two limbs alone
   (independently of the window, since P < 2).  Because accepted
   factors update D immediately, the model resyncs exactly after
   every accept, so the ambiguity band degenerates to the single
   value h == lt; rejected steps (about half) cost a handful of
   register operations.

   P grows gradually: multiplying by 1 + 2^-i moves the exact least
   significant bit down by i, so the significant fraction length of P
   is the sum of the accepted i divided by FLINT_BITS, capped at n
   limbs (only past that cap does P get truncated at all).  All
   accept-side operations (the shift, the additions into P and the
   subtraction from D, and the table additions into the accumulator)
   run on the significant slices with a carry/borrow ripple across
   the remaining limbs.

   Error accounting (output ulp 2^(-FLINT_BITS n), all one-sided
   sources): at most r + 2 table entries are added, each short of the
   true logarithm by < 2 ulp; each accepted factor truncates P by
   < 1 ulp, entering the result as log(Pi/P) < (r + 2) ulp in total;
   the division floors once; the doubled atanh error contributes
   <= 30 ulp.  Total < 3 (r + 2) + 40, bounded by
   FIXED_LOG1P_BITWISE_RS_MAX_ERR(n, r) = 3 r + 64. */

#define LOGS_L(i) (tab + (i) * nc)

#if FLINT_BITS == 64


#endif /* FLINT_BITS == 64 */

/* smallest n at which each reduction parameter becomes optimal
   (generated by src/fixed/tune/tune-bitwise-r.c with nmax deep enough
   to reach the r = 768 end of the ladder; x86-64 defaults) */
static const int _fixed_log1p_bitwise_rs_r_tab[] =
    {32, 64, 128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768};
static const short _fixed_log1p_bitwise_rs_n_tab[] =
    {1, 17, 53, 96, 179, 255, 306, 540, 542, 821, 952, 972, 1004};

int
fixed_log1p_bitwise_rs_default_r(slong n)
{
    slong j;

#if FLINT_BITS == 64
    /* the compile-time constants of the specialized per-size files:
       keep in sync with the dev/tune_fixed.py --pin values that
       emitted them */
    static const int opt_r[] = {0, 16, 16, 10, 26, 31, 30, 25};
    if (n <= 7)
        return opt_r[n];
#endif

    for (j = 0; j + 1 < (slong) (sizeof(_fixed_log1p_bitwise_rs_n_tab) / sizeof(short))
            && n >= _fixed_log1p_bitwise_rs_n_tab[j + 1]; j++)
        ;
    return _fixed_log1p_bitwise_rs_r_tab[j];
}

void
fixed_log1p_bitwise_rs(nn_ptr res, nn_srcptr x, slong n, int r)
{
#if FLINT_BITS == 64
    int r0;
#endif
    slong i, c, wn, nc, pl, lsb_bits, qr, ds;
    nn_ptr P, D, acc, sh, t, nd;
    TMP_INIT;

    FLINT_ASSERT(n >= 1);
    FLINT_ASSERT(r == 0 || r >= 32);
    /* n = 1 is unsupported on 32-bit limbs: the clamp below would
       drop r under the r >= 32 contract of the residual series */
    FLINT_ASSERT(FLINT_BITS == 64 || n >= 2);

#if FLINT_BITS == 64
    r0 = r;
#endif

    if (r == 0)
        r = fixed_log1p_bitwise_rs_default_r(n);

    /* r < 32 (a shorter reduction with a slightly longer series) is
       available in the register implementations below, whose inline
       atanh evaluations only need t < 2^-16; the general path uses
       fixed_atanh_rs and hence at least r = 32 */
#if FLINT_BITS == 64
    /* fully specialized per-size implementations (log1p_opt_<n>.c,
       emitted and tuned by dev/tune_fixed.py; n = 1 and 2 are the
       hand-written register paths, carried over by the tuner) */
    if (r0 == 0 && n <= 7)
    {
        static void (* const tab[])(nn_ptr, nn_srcptr) = {
            NULL, fixed_log1p_opt_1, fixed_log1p_opt_2,
            fixed_log1p_opt_3, fixed_log1p_opt_4, fixed_log1p_opt_5,
            fixed_log1p_opt_6, fixed_log1p_opt_7
        };
        tab[n](res, x);
        return;
    }
#endif /* FLINT_BITS == 64 */

    r = FLINT_MAX(r, 32);
    r = FLINT_MIN((slong) r, FLINT_BITS * n - 16);

    wn = n + 1;

    nn_srcptr tab;
    tab = _fixed_exp_logs_tab(n, r, &nc);

    TMP_START;
    P = TMP_ALLOC((wn + wn + n + n + n + 2 * n + 2) * sizeof(ulong));
    sh = P + wn;
    D = sh + wn;
    acc = D + n;
    t = acc + n;
    nd = t + n;

    /* P = 1, deficit D = X - P = x, accumulator = 0 */
    flint_mpn_zero(P, n);
    P[n] = 1;
    flint_mpn_copyi(D, x, n);
    flint_mpn_zero(acc, n);
    pl = 0;             /* significant fraction limbs of P */
    lsb_bits = 0;       /* depth of P's exact lowest fraction bit */

/* materialize v = trunc(P >> ii) into sh as (P >> b) (limb offset q
   applied at use); z_ = index below which (P >> b) is exactly zero */
#define MAKE_SH(ii, q_, b_, z_) \
    do { \
        (q_) = (ii) / FLINT_BITS; \
        (b_) = (ii) - (q_) * FLINT_BITS; \
        (z_) = FLINT_MAX(0, n - pl - 1); \
        if ((b_) != 0) \
            mpn_rshift(sh + (z_), P + (z_), wn - (z_), b_); \
        else \
            flint_mpn_copyi(sh + (z_), P + (z_), wn - (z_)); \
    } while (0)

/* accept factor 1 + 2^-ii, with sh already holding P >> b:
   D -= v, P += v, acc += L_ii, on the significant slices */
#define APPLY(ii, q_, b_, z_) \
    do { \
        slong len_ = FLINT_MIN(n, wn - (q_)); \
        slong j0_ = FLINT_MAX(0, (z_) - (q_)); \
        ulong cy_; \
        if (j0_ < len_) \
        { \
            cy_ = mpn_sub_n(D + j0_, D + j0_, sh + (q_) + j0_, \
                len_ - j0_); \
            if (cy_ != 0) \
                mpn_sub_1(D, D, j0_, cy_); \
            cy_ = mpn_add_n(P + j0_, P + j0_, sh + (q_) + j0_, \
                len_ - j0_); \
            if (cy_ != 0) \
                mpn_add_1(P + len_, P + len_, wn - len_, cy_); \
        } \
        cy_ = mpn_add(acc, acc, n, LOGS_L(ii) + (nc - n), n - (q_)); \
        (void) cy_;                 /* acc < log 2 < 1 */ \
        lsb_bits += (ii); \
        pl = FLINT_MIN(n, (lsb_bits + FLINT_BITS - 1) / FLINT_BITS); \
    } while (0)

/* exact compare-accept of factor ii */
#define EXACT_STEP(ii) \
    do { \
        slong q_, b_, z_, len_, j0_, k_; \
        int ge_; \
        MAKE_SH(ii, q_, b_, z_); \
        len_ = FLINT_MIN(n, wn - q_); \
        j0_ = FLINT_MAX(0, z_ - q_); \
        /* v's limbs are sh[q_ + j] for j0_ <= j < len_, zero \
           elsewhere on the n-limb grid; note sh[n] = P[n] >> b_ \
           is nonzero only for b_ = 0, in which case v's top limb \
           n - q_ is included in len_ */ \
        ge_ = 0; \
        for (k_ = n - 1; k_ >= len_; k_--) \
            if (D[k_] != 0) \
            { \
                ge_ = 1;            /* D has a higher limb set */ \
                break; \
            } \
        if (!ge_ && j0_ < len_) \
        { \
            int c_ = mpn_cmp(D + j0_, sh + q_ + j0_, len_ - j0_); \
            /* on tie, D's lower limbs are >= v's (which are zero) */ \
            ge_ = (c_ >= 0); \
        } \
        else if (!ge_) \
            ge_ = 1;                /* v truncates to zero: cannot \
                                       happen for i <= r (clamped) */ \
        if (ge_) \
            APPLY(ii, q_, b_, z_); \
    } while (0)

    for (c = 0; FLINT_BITS * c <= r; c++)
    {
        slong i0 = (c == 0) ? 1 : FLINT_BITS * c;
        slong i1 = FLINT_MIN((slong) r, FLINT_BITS * (c + 1) - 1);
        ulong h;

        if (i0 > (slong) r)
            break;

        /* exact step at the window boundary */
        EXACT_STEP(i0);

        h = D[n - 1 - c];

        for (i = i0 + 1; i <= i1; i++)
        {
            slong b = i - FLINT_BITS * c;
            ulong lt;

            /* unlike exp (where t < L_i < 2^-i), the deficit obeys
               only D < P 2^-i < 2^(1-i): a bit above the window can
               persist, but then v = P >> i < 2^(1-i) <= D is a
               certain accept */
            if (c > 0 && D[n - c] != 0)
            {
                slong q_, b_, z_;
                MAKE_SH(i, q_, b_, z_);
                APPLY(i, q_, b_, z_);
                h = D[n - 1 - c];
                continue;
            }

            lt = MPN_RIGHT_SHIFT_LOW(P[n], P[n - 1], (int) b);

            if (h > lt)
            {
                slong q_, b_, z_;
                MAKE_SH(i, q_, b_, z_);
                APPLY(i, q_, b_, z_);
                h = D[n - 1 - c];
            }
            else if (h == lt)
            {
                /* the lower limbs decide */
                EXACT_STEP(i);
                h = D[n - 1 - c];
            }
            /* else certain reject: D < (h+1) u <= lt u <= P >> i */
        }
    }

    /* the truncated table and P let the residual creep marginally
       above 2^-r; one extra step restores X/P < 1 + 2^-r */
    EXACT_STEP(r);

#undef MAKE_SH
#undef APPLY
#undef EXACT_STEP

    /* t = D / (X + P) < 2^-r: the single division fuses the
       normalization by P with the atanh transformation */
    {
        flint_mpn_copyi(sh, P, wn);
        sh[n] += 1 + mpn_add_n(sh, sh, x, n);   /* S = X + P in [2, 4) */

        qr = 0;
        while (qr < n && D[n - 1 - qr] == 0)
            qr++;
        ds = 2 * n - qr;

        flint_mpn_zero(t, n);
        if (ds >= wn && qr < n)
        {
            flint_mpn_zero(nd, n);
            flint_mpn_copyi(nd + n, D, n - qr);
            /* quotient has ds - wn + 1 = n - qr limbs */
            if (ds - wn + 1 < FIXED_RED_DIV_NEWTON_CUTOFF)
        {
            mpn_tdiv_qr(t, nd, 0, nd, ds, sh, wn);
        }
        else
        {
            /* Same quotient by Karp-Markstein division: numerator
               and divisor read as fractions (the numerator's n low
               limbs are zero, so pass only its significant top
               part), quotient computed with k + 1 fraction limbs, k
               the quotient length.  Truncating the two guard limbs
               leaves t within 1 + eps ulps of the floored quotient
               (eps = 4 B^(-1) / a' < 2^-62), which the series
               argument budget absorbs like the tdiv floor. */
            slong k = ds - wn + 1;
            nn_ptr q = TMP_ALLOC((k + 4) * sizeof(ulong));
            fixed_div_newton(q, nd + n, ds - n, sh, wn, k + 1);
            flint_mpn_copyi(t, q + 2, k);
        }
        }
    }

    /* log X = acc + 2 atanh(t); on 32-bit limbs n = 1 clamps r to
       16 above, where the wider-range atanh applies */
    fixed_atanh_rs(sh, t, n);
    mpn_lshift(sh, sh, n, 1);
    mpn_add_n(res, acc, sh, n);

    TMP_END;
}
