/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* GENERATED by dev/tune_fixed.py (log1p, n = 5, r = 31) -- do not
   edit directly; retune or re-emit with
       python3 dev/tune_fixed.py log1p 5 --pin 31 --emit */

#include "flint.h"
#include "longlong.h"
#include "mpn_extras.h"
#include "fixed.h"
#include "hand_mulhi.inc"

#if FLINT_BITS == 64

/* atanh, n = 5, r = 31: 4 levels, widths [4, 3, 2, 1] */
static void
_fixed_log1p_series_5(nn_ptr res, nn_srcptr x)
{
    ulong z[5], V[5], T[5], P[5], Z[2];
    ulong v, w1, w0, h, l;
    slong i;

    (void) v; (void) w1; (void) w0; (void) h; (void) l;
    (void) i; (void) Z; (void) V; (void) T; (void) P;

    flint_mpn_sqrhigh(z, x, 5);

    v = UWORD(0x1c71c71c71c71c71);

    /* V_2 = c + z V_3   (2 x 1 limbs) */
    _fixed_mulhi_2x1(&h, &l, z[4], z[3], v);
    add_ssaaaa(w1, w0, UWORD(0x2492492492492492), UWORD(0x4924924924924924), h, l);

    /* V_1 = c + z V_2   (3 x 2 limbs) */
    P[0] = UWORD(0);
    P[1] = w0; P[2] = w1;
    flint_mpn_mulhigh_n(T, z + 2, P, 3);
    P[0] = UWORD(0x3333333333333333);
    P[1] = UWORD(0x3333333333333333);
    P[2] = UWORD(0x3333333333333333);
    NN_ADD_3(V, P, T);

    /* V_0 = c + z V_1   (4 x 3 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    flint_mpn_mulhigh_n(T, z + 1, P, 4);
    P[0] = UWORD(0x5555555555555555);
    P[1] = UWORD(0x5555555555555555);
    P[2] = UWORD(0x5555555555555555);
    P[3] = UWORD(0x5555555555555555);
    NN_ADD_4(V, P, T);

    /* atanh = x + x^3 V_0 */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    P[4] = V[3];
    flint_mpn_mulhigh_n(T, z, x, 5);
    flint_mpn_mulhigh_n(V, T, P, 5);
    NN_ADD_5(res, x, V);
}

void
fixed_log1p_opt_5(nn_ptr res, nn_srcptr x)
{
    const int r = 31;
    ulong d0, d1, d2, d3, d4;
    ulong p0, p1, p2, p3, p4;
    ulong a0, a1, a2, a3, a4;
    ulong e0, e1, e2, e3, e4;
    ulong v0, v1, v2, v3, v4;
    ulong bw, m, h, lt;
    ulong S[6], nd[10], t[5], y[5];
    slong i, nc;


    nn_srcptr tab;
    tab = _fixed_exp_logs_tab(5, r, &nc);

    d0 = x[0];
    d1 = x[1];
    d2 = x[2];
    d3 = x[3];
    d4 = x[4];
    p0 = 0;
    p1 = 0;
    p2 = 0;
    p3 = 0;
    p4 = 0;
    a0 = 0;
    a1 = 0;
    a2 = 0;
    a3 = 0;
    a4 = 0;

#define LP(ii) (tab + (ii) * nc + (nc - 5))

    /* window 0 */
    {
        nn_srcptr Lp;

        /* boundary step i = 1 */
        Lp = LP(1);
        v0 = MPN_RIGHT_SHIFT_LOW(p1, p0, 1);
        v1 = MPN_RIGHT_SHIFT_LOW(p2, p1, 1);
        v2 = MPN_RIGHT_SHIFT_LOW(p3, p2, 1);
        v3 = MPN_RIGHT_SHIFT_LOW(p4, p3, 1);
        v4 = MPN_RIGHT_SHIFT_LOW(UWORD(1), p4, 1);
        sub_ddddddmmmmmmssssss(bw, e4, e3, e2, e1, e0,
            UWORD(0), d4, d3, d2, d1, d0,
            UWORD(0), v4, v3, v2, v1, v0);
        m = ~bw;                /* accept iff no borrow */
        d0 = (d0 & bw) | (e0 & m);
        d1 = (d1 & bw) | (e1 & m);
        d2 = (d2 & bw) | (e2 & m);
        d3 = (d3 & bw) | (e3 & m);
        d4 = (d4 & bw) | (e4 & m);
        add_sssssaaaaaaaaaa(p4, p3, p2, p1, p0,
            p4, p3, p2, p1, p0,
            (v4) & m, (v3) & m, (v2) & m, (v1) & m, (v0) & m);
        add_sssssaaaaaaaaaa(a4, a3, a2, a1, a0,
            a4, a3, a2, a1, a0,
            Lp[4] & m, Lp[3] & m, Lp[2] & m, Lp[1] & m, Lp[0] & m);

        h = d4;

        for (i = 2; i <= 31; i++)
        {
            int b = (int) (i - 0);

            lt = MPN_RIGHT_SHIFT_LOW(UWORD(1), p4, b);
            if (h < lt)
                continue;    /* certain reject */

            Lp = LP(i);
            v0 = MPN_RIGHT_SHIFT_LOW(p1, p0, b);
            v1 = MPN_RIGHT_SHIFT_LOW(p2, p1, b);
            v2 = MPN_RIGHT_SHIFT_LOW(p3, p2, b);
            v3 = MPN_RIGHT_SHIFT_LOW(p4, p3, b);
            v4 = lt;
            sub_ddddddmmmmmmssssss(bw, e4, e3, e2, e1, e0,
                UWORD(0), d4, d3, d2, d1, d0,
                UWORD(0), v4, v3, v2, v1, v0);
            m = ~bw;                /* accept iff no borrow */
            d0 = (d0 & bw) | (e0 & m);
            d1 = (d1 & bw) | (e1 & m);
            d2 = (d2 & bw) | (e2 & m);
            d3 = (d3 & bw) | (e3 & m);
            d4 = (d4 & bw) | (e4 & m);
            add_sssssaaaaaaaaaa(p4, p3, p2, p1, p0,
                p4, p3, p2, p1, p0,
                (v4) & m, (v3) & m, (v2) & m, (v1) & m, (v0) & m);
            add_sssssaaaaaaaaaa(a4, a3, a2, a1, a0,
                a4, a3, a2, a1, a0,
                Lp[4] & m, Lp[3] & m, Lp[2] & m, Lp[1] & m, Lp[0] & m);
            h = d4;
        }
    }

    /* one extra step at i = r absorbs the truncation creep */
    {
        nn_srcptr Lp = LP((slong) r);
        const int b = 31;

        v0 = MPN_RIGHT_SHIFT_LOW(p1, p0, b);
        v1 = MPN_RIGHT_SHIFT_LOW(p2, p1, b);
        v2 = MPN_RIGHT_SHIFT_LOW(p3, p2, b);
        v3 = MPN_RIGHT_SHIFT_LOW(p4, p3, b);
        v4 = MPN_RIGHT_SHIFT_LOW(UWORD(1), p4, b);
        sub_ddddddmmmmmmssssss(bw, e4, e3, e2, e1, e0,
            UWORD(0), d4, d3, d2, d1, d0,
            UWORD(0), v4, v3, v2, v1, v0);
        m = ~bw;                /* accept iff no borrow */
        d0 = (d0 & bw) | (e0 & m);
        d1 = (d1 & bw) | (e1 & m);
        d2 = (d2 & bw) | (e2 & m);
        d3 = (d3 & bw) | (e3 & m);
        d4 = (d4 & bw) | (e4 & m);
        add_sssssaaaaaaaaaa(p4, p3, p2, p1, p0,
            p4, p3, p2, p1, p0,
            (v4) & m, (v3) & m, (v2) & m, (v1) & m, (v0) & m);
        add_sssssaaaaaaaaaa(a4, a3, a2, a1, a0,
            a4, a3, a2, a1, a0,
            Lp[4] & m, Lp[3] & m, Lp[2] & m, Lp[1] & m, Lp[0] & m);
    }

#undef LP

    /* t = D 2^(FLINT_BITS 5) / (X + P) */
    add_ssssssaaaaaaaaaaaa(S[5], S[4], S[3], S[2], S[1], S[0],
        UWORD(1), x[4], x[3], x[2], x[1], x[0],
        UWORD(1), p4, p3, p2, p1, p0);
    nd[0] = 0;
    nd[1] = 0;
    nd[2] = 0;
    nd[3] = 0;
    nd[4] = 0;
    nd[5] = d0;
    nd[6] = d1;
    nd[7] = d2;
    nd[8] = d3;
    nd[9] = d4;
    flint_mpn_zero(t, 5);
    if (d4 != 0 || d3 != 0 || d2 != 0 || d1 != 0 || d0 != 0)
        mpn_tdiv_qr(t, nd, 0, nd, 10, S, 6);

    _fixed_log1p_series_5(y, t);

    add_sssssaaaaaaaaaa(res[4], res[3], res[2], res[1], res[0],
        a4, a3, a2, a1, a0,
        (y[4] << 1) | (y[3] >> (FLINT_BITS - 1)), (y[3] << 1) | (y[2] >> (FLINT_BITS - 1)), (y[2] << 1) | (y[1] >> (FLINT_BITS - 1)), (y[1] << 1) | (y[0] >> (FLINT_BITS - 1)), y[0] << 1);
}


#endif /* FLINT_BITS == 64 */
