/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* GENERATED by dev/tune_fixed.py (trig, n = 6, r = 18) -- do not
   edit directly; retune or re-emit with
       python3 dev/tune_fixed.py trig 6 --pin 18 --emit */

#include "flint.h"
#include "longlong.h"
#include "mpn_extras.h"
#include "fixed.h"
#include "hand_mulhi.inc"

#if FLINT_BITS == 64

/* tan, n = 6, r = 18: 9 levels, widths [6, 5, 4, 4, 3, 3, 2, 2, 1] */
static void
_fixed_tan_series_6(nn_ptr res, nn_srcptr x)
{
    ulong z[6], V[6], T[6], P[6], Z[2];
    ulong v, w1, w0, h, l;
    slong i;

    (void) v; (void) w1; (void) w0; (void) h; (void) l;
    (void) i; (void) Z; (void) V; (void) T; (void) P;

    flint_mpn_sqrhigh(z, x, 6);

    v = UWORD(0x000fabebb9a68b32);

    /* V_7 = c + z V_8   (2 x 1 limbs) */
    _fixed_mulhi_2x1(&h, &l, z[5], z[4], v);
    add_ssaaaa(w1, w0, UWORD(0x0026ab049006ce88), UWORD(0xa446cab1f8f9189f), h, l);

    /* V_6 = c + z V_7   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[5], z[4], w1, w0);
    add_ssaaaa(w1, w0, UWORD(0x005f68d914add78a), UWORD(0xda8764d7a2d130cc), h, l);

    /* V_5 = c + z V_6   (3 x 2 limbs) */
    P[0] = UWORD(0);
    P[1] = w0; P[2] = w1;
    flint_mpn_mulhigh_n(T, z + 3, P, 3);
    P[0] = UWORD(0xbc019c9698f878f2);
    P[1] = UWORD(0xafe606d2e4d1e65f);
    P[2] = UWORD(0x00eb69e870abeefd);
    NN_ADD_3(V, P, T);

    /* V_4 = c + z V_5   (3 x 3 limbs) */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    flint_mpn_mulhigh_n(T, z + 3, P, 3);
    P[0] = UWORD(0x286aa3a066807579);
    P[1] = UWORD(0xeb6a3872e9f6403b);
    P[2] = UWORD(0x0244dc6abcd84791);
    NN_ADD_3(V, P, T);

    /* V_3 = c + z V_4   (4 x 3 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    flint_mpn_mulhigh_n(T, z + 2, P, 4);
    P[0] = UWORD(0xe9277605993d220b);
    P[1] = UWORD(0xd220b043e7ccb5ae);
    P[2] = UWORD(0xcb5aee9277605993);
    P[3] = UWORD(0x05993d220b043e7c);
    NN_ADD_4(V, P, T);

    /* V_2 = c + z V_3   (4 x 4 limbs) */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    P[3] = V[3];
    flint_mpn_mulhigh_n(T, z + 2, P, 4);
    P[0] = UWORD(0x0dd0dd0dd0dd0dd0);
    P[1] = UWORD(0xd0dd0dd0dd0dd0dd);
    P[2] = UWORD(0xdd0dd0dd0dd0dd0d);
    P[3] = UWORD(0x0dd0dd0dd0dd0dd0);
    NN_ADD_4(V, P, T);

    /* V_1 = c + z V_2   (5 x 4 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    P[4] = V[3];
    flint_mpn_mulhigh_n(T, z + 1, P, 5);
    P[0] = UWORD(0x2222222222222222);
    P[1] = UWORD(0x2222222222222222);
    P[2] = UWORD(0x2222222222222222);
    P[3] = UWORD(0x2222222222222222);
    P[4] = UWORD(0x2222222222222222);
    NN_ADD_5(V, P, T);

    /* V_0 = c + z V_1   (6 x 5 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    P[4] = V[3];
    P[5] = V[4];
    flint_mpn_mulhigh_n(T, z + 0, P, 6);
    P[0] = UWORD(0x5555555555555555);
    P[1] = UWORD(0x5555555555555555);
    P[2] = UWORD(0x5555555555555555);
    P[3] = UWORD(0x5555555555555555);
    P[4] = UWORD(0x5555555555555555);
    P[5] = UWORD(0x5555555555555555);
    NN_ADD_6(V, P, T);

    /* tan = x + x^3 V_0 */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    P[3] = V[3];
    P[4] = V[4];
    P[5] = V[5];
    flint_mpn_mulhigh_n(T, z, x, 6);
    flint_mpn_mulhigh_n(V, T, P, 6);
    NN_ADD_6(res, x, V);
}

void
_fixed_trig_opt_6(nn_ptr ysin, nn_ptr ycos, nn_ptr ytan,
    nn_srcptr x)
{
    _fixed_tan_halfangle_mid(ysin, ycos, ytan, x, 6, 18,
        _fixed_tan_series_6);
}

void
fixed_sin_cos_opt_6(nn_ptr ysin, nn_ptr ycos, nn_srcptr x)
{
    _fixed_trig_opt_6(ysin, ycos, NULL, x);
}

void
fixed_tan_opt_6(nn_ptr res, nn_srcptr x)
{
    _fixed_trig_opt_6(NULL, NULL, res, x);
}

#endif /* FLINT_BITS == 64 */
