/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* GENERATED by dev/tune_fixed.py (trig, n = 2, r = 5) -- do not
   edit directly; retune or re-emit with
       python3 dev/tune_fixed.py trig 2 --pin 5 --emit */

#include "flint.h"
#include "longlong.h"
#include "mpn_extras.h"
#include "fixed.h"
#include "hand_mulhi.inc"
#include "tan_rotate.inc"

#if FLINT_BITS == 64

/* tan, n = 2, r = 5: 10 levels, widths [2, 2, 2, 2, 2, 1, 1, 1, 1, 1] */
static void
_fixed_tan_series_2(nn_ptr res, nn_srcptr x)
{
    ulong z[2], V[2], T[2], P[2], Z[2];
    ulong v, w1, w0, h, l;
    slong i;

    (void) v; (void) w1; (void) w0; (void) h; (void) l;
    (void) i; (void) Z; (void) V; (void) T; (void) P;

    _fixed_sqrhi_2x2(&z[1], &z[0], x[1], x[0]);

    v = UWORD(0x000659f862bf2beb);

    /* V_8 = c + z V_9   (1 x 1 limbs) */
    v = n_mulhi(z[1], v);
    v = UWORD(0x000fabebb9a68b32) + v;

    /* V_7 = c + z V_8   (1 x 1 limbs) */
    v = n_mulhi(z[1], v);
    v = UWORD(0x0026ab049006ce88) + v;

    /* V_6 = c + z V_7   (1 x 1 limbs) */
    v = n_mulhi(z[1], v);
    v = UWORD(0x005f68d914add78a) + v;

    /* V_5 = c + z V_6   (1 x 1 limbs) */
    v = n_mulhi(z[1], v);
    v = UWORD(0x00eb69e870abeefd) + v;

    /* V_4 = c + z V_5   (2 x 1 limbs) */
    _fixed_mulhi_2x1(&h, &l, z[1], z[0], v);
    add_ssaaaa(w1, w0, UWORD(0x0244dc6abcd84791), UWORD(0xeb6a3872e9f6403b), h, l);

    /* V_3 = c + z V_4   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[1], z[0], w1, w0);
    add_ssaaaa(w1, w0, UWORD(0x05993d220b043e7c), UWORD(0xcb5aee9277605993), h, l);

    /* V_2 = c + z V_3   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[1], z[0], w1, w0);
    add_ssaaaa(w1, w0, UWORD(0x0dd0dd0dd0dd0dd0), UWORD(0xdd0dd0dd0dd0dd0d), h, l);

    /* V_1 = c + z V_2   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[1], z[0], w1, w0);
    add_ssaaaa(w1, w0, UWORD(0x2222222222222222), UWORD(0x2222222222222222), h, l);

    /* V_0 = c + z V_1   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[1], z[0], w1, w0);
    add_ssaaaa(w1, w0, UWORD(0x5555555555555555), UWORD(0x5555555555555555), h, l);

    /* tan = x + x^3 V_0 */
    P[0] = w0; P[1] = w1;
    _fixed_mulhi_2x2_sloppy(&T[1], &T[0], z[1], z[0], x[1], x[0]);
    _fixed_mulhi_2x2_sloppy(&V[1], &V[0], T[1], T[0], P[1], P[0]);
    NN_ADD_2(res, x, V);
}

void
_fixed_trig_opt_2(nn_ptr ysin, nn_ptr ycos, nn_ptr ytan,
    nn_srcptr x)
{
    slong num, nc;
    const int r = 5;
    int c;
    ulong t[2], u[2], wx[3], wy[3];
    ulong T[2], D[3], h[2], A[2], B[2], C[2];
    ulong S[2], N[4], R[3], rem[2], v[2];
    slong * used;
    TMP_INIT;

    nn_srcptr tab;
    tab = _fixed_atans_tab(2, r, &nc);

    TMP_START;
    used = TMP_ALLOC(FIXED_BITWISE_REDUCE_USED_ALLOC(r) * sizeof(slong));

    t[0] = (x[0] >> 1) | (x[1] << (FLINT_BITS - 1));
    t[1] = x[1] >> 1;
    num = _fixed_bitwise_reduce(t, 2, r, 1, tab, nc, used);
    _fixed_tan_rotate_2(wx, wy, used, num);
    _fixed_tan_series_2(u, t);          /* u = tan(t') */

    /* TT = wy + wx u < 0.64 (n limbs) */
    _fixed_mulhi_2x2_sloppy(h + 1, h, wx[1], wx[0], u[1], u[0]);
    if (wx[2])
        NN_ADD_2(h, h, u);
    NN_ADD_2(T, h, wy);
    /* DE = wx - wy u in (0.72, 1.17) */
    _fixed_mulhi_2x2_sloppy(h + 1, h, wy[1], wy[0], u[1], u[0]);
    sub_dddmmmsss(D[2], D[1], D[0],
        wx[2], wx[1], wx[0],
        UWORD(0), h[1], h[0]);

    /* halved together when DE reaches one: DE normalized */
    if (D[2])
    {
        D[0] = (D[0] >> 1) | (D[1] << (FLINT_BITS - 1));
        D[1] >>= 1;
        D[1] |= UWORD(1) << (FLINT_BITS - 1);
        T[0] = (T[0] >> 1) | (T[1] << (FLINT_BITS - 1));
        T[1] >>= 1;
    }

    /* A = TT DE, B = DE^2, C = TT^2 (A unconditionally: proving
       the sin/tan branches imply its initialization is beyond the
       compiler, and a cos-only caller wastes one cheap mulhigh) */
    _fixed_mulhi_2x2_sloppy(A + 1, A, T[1], T[0], D[1], D[0]);
    _fixed_sqrhi_2x2(B + 1, B, D[1], D[0]);
    _fixed_sqrhi_2x2(C + 1, C, T[1], T[0]);

    N[0] = ~UWORD(0);
    N[1] = ~UWORD(0);
    N[2] = ~UWORD(0);
    N[3] = ~UWORD(0) >> 1;

    if (ysin != NULL || ycos != NULL)
    {
        /* S = B + C = DE^2 (1 + t^2), normalized to [0.5, 1):
           c = 2 - e is the doubling shift of sin = 2^(2-e) A R */
        ulong cy;
        add_sssaaaaaa(cy, S[1], S[0],
            UWORD(0), B[1], B[0],
            UWORD(0), C[1], C[0]);
        if (cy)
        {
            S[0] = (S[0] >> 1) | (S[1] << (FLINT_BITS - 1));
            S[1] >>= 1;
            S[1] |= UWORD(1) << (FLINT_BITS - 1);
            c = 1;
        }
        else if (!(S[1] >> (FLINT_BITS - 1)))
        {
            S[1] = (S[1] << 1) | (S[0] >> (FLINT_BITS - 1));
            S[0] = S[0] << 1;
            c = 3;
        }
        else
            c = 2;

        mpn_tdiv_qr(R, rem, 0, N, 4, S, 2);

        if (ysin != NULL)
        {
            _fixed_mulhi_2x2_sloppy(v + 1, v, A[1], A[0], R[1], R[0]);
            ysin[2] = v[1] >> (FLINT_BITS - c);
            ysin[1] = (v[1] << c) | (v[0] >> (FLINT_BITS - c));
            ysin[0] = v[0] << c;
        }
        if (ycos != NULL)
        {
            _fixed_mulhi_2x2_sloppy(v + 1, v, C[1], C[0], R[1], R[0]);
            v[1] = (v[1] << c) | (v[0] >> (FLINT_BITS - c));
            v[0] = v[0] << c;
            if (v[0] == 0 && v[1] == 0)
            {
                ycos[0] = 0;
                ycos[1] = 0;
                ycos[2] = 1;   /* cos exactly one */
            }
            else
            {
                sub_ddmmss(ycos[1], ycos[0],
                    UWORD(0), UWORD(0),
                    v[1], v[0]);
                ycos[2] = 0;
            }
        }
    }

    if (ytan != NULL)
    {
        /* W = B - C = DE^2 (1 - t^2) > 0.175: at most two leading
           zero bits; tan = 2^(2+e) A R < 1.56 */
        sub_ddmmss(S[1], S[0],
            B[1], B[0],
            C[1], C[0]);
        c = flint_clz(S[1]);
        if (c)
        {
            S[1] = (S[1] << c) | (S[0] >> (FLINT_BITS - c));
            S[0] = S[0] << c;
        }
        c += 2;

        mpn_tdiv_qr(R, rem, 0, N, 4, S, 2);

        _fixed_mulhi_2x2_sloppy(v + 1, v, A[1], A[0], R[1], R[0]);
        ytan[2] = v[1] >> (FLINT_BITS - c);
        ytan[1] = (v[1] << c) | (v[0] >> (FLINT_BITS - c));
        ytan[0] = v[0] << c;
    }

    TMP_END;
}


void
fixed_sin_cos_opt_2(nn_ptr ysin, nn_ptr ycos, nn_srcptr x)
{
    _fixed_trig_opt_2(ysin, ycos, NULL, x);
}

void
fixed_tan_opt_2(nn_ptr res, nn_srcptr x)
{
    _fixed_trig_opt_2(NULL, NULL, res, x);
}

#endif /* FLINT_BITS == 64 */
