/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* GENERATED by dev/tune_fixed.py (trig, n = 9, r = 16) -- do not
   edit directly; retune or re-emit with
       python3 dev/tune_fixed.py trig 9 --pin 16 --emit */

#include "flint.h"
#include "longlong.h"
#include "mpn_extras.h"
#include "fixed.h"
#include "hand_mulhi.inc"

#if FLINT_BITS == 64

/* tan, n = 9, r = 16: 16 levels, widths [9, 8, 8, 7, 7, 6, 6, 5, 5, 4, 4, 3, 3, 2, 2, 1] */
static void
_fixed_tan_series_9(nn_ptr res, nn_srcptr x)
{
    ulong z[9], V[9], T[9], P[9], Z[2];
    ulong v, w1, w0, h, l;
    slong i;

    (void) v; (void) w1; (void) w0; (void) h; (void) l;
    (void) i; (void) Z; (void) V; (void) T; (void) P;

    flint_mpn_sqrhigh(z, x, 9);

    v = UWORD(0x00000734a67792b9);

    /* V_14 = c + z V_15   (2 x 1 limbs) */
    _fixed_mulhi_2x1(&h, &l, z[8], z[7], v);
    add_ssaaaa(w1, w0, UWORD(0x000011c77df95c1c), UWORD(0x0d02dc9139620f15), h, l);

    /* V_13 = c + z V_14   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[8], z[7], w1, w0);
    add_ssaaaa(w1, w0, UWORD(0x00002bde5b48e9cb), UWORD(0x6d8f678a051770c3), h, l);

    /* V_12 = c + z V_13   (3 x 2 limbs) */
    P[0] = UWORD(0);
    P[1] = w0; P[2] = w1;
    flint_mpn_mulhigh_n(T, z + 6, P, 3);
    P[0] = UWORD(0x8bae92bc0c18926f);
    P[1] = UWORD(0xa48b446eeacab047);
    P[2] = UWORD(0x00006c3dcb4fb893);
    NN_ADD_3(V, P, T);

    /* V_11 = c + z V_12   (3 x 3 limbs) */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    flint_mpn_mulhigh_n(T, z + 6, P, 3);
    P[0] = UWORD(0xbf1949290cf2324e);
    P[1] = UWORD(0x04ec9d30b0658500);
    P[2] = UWORD(0x00010b132d39a605);
    NN_ADD_3(V, P, T);

    /* V_10 = c + z V_11   (4 x 3 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    flint_mpn_mulhigh_n(T, z + 5, P, 4);
    P[0] = UWORD(0x960357db2f291350);
    P[1] = UWORD(0x422735db56ce2059);
    P[2] = UWORD(0x267cb40b934a18c8);
    P[3] = UWORD(0x000292fb1dd44a4b);
    NN_ADD_4(V, P, T);

    /* V_9 = c + z V_10   (4 x 4 limbs) */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    P[3] = V[3];
    flint_mpn_mulhigh_n(T, z + 5, P, 4);
    P[0] = UWORD(0x0bf1c8ef6fb7af42);
    P[1] = UWORD(0x62054c890ce75954);
    P[2] = UWORD(0x2289eb5bd2bb19f2);
    P[3] = UWORD(0x000659f862bf2beb);
    NN_ADD_4(V, P, T);

    /* V_8 = c + z V_9   (5 x 4 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    P[4] = V[3];
    flint_mpn_mulhigh_n(T, z + 4, P, 5);
    P[0] = UWORD(0x144bb83f7d9223b5);
    P[1] = UWORD(0x2b9c11f13312f31a);
    P[2] = UWORD(0x7719a99cabd2a5a3);
    P[3] = UWORD(0x10d55a913ccb500a);
    P[4] = UWORD(0x000fabebb9a68b32);
    NN_ADD_5(V, P, T);

    /* V_7 = c + z V_8   (5 x 5 limbs) */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    P[3] = V[3];
    P[4] = V[4];
    flint_mpn_mulhigh_n(T, z + 4, P, 5);
    P[0] = UWORD(0xe3d1005c0cc015f6);
    P[1] = UWORD(0x9091157ba30a5acf);
    P[2] = UWORD(0x4263dc8f4ddf6b79);
    P[3] = UWORD(0xa446cab1f8f9189f);
    P[4] = UWORD(0x0026ab049006ce88);
    NN_ADD_5(V, P, T);

    /* V_6 = c + z V_7   (6 x 5 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    P[4] = V[3];
    P[5] = V[4];
    flint_mpn_mulhigh_n(T, z + 3, P, 6);
    P[0] = UWORD(0x890d74672dbac064);
    P[1] = UWORD(0x49555555703d493c);
    P[2] = UWORD(0xfe68b9a80df6602e);
    P[3] = UWORD(0xb8a033a6c8c055d8);
    P[4] = UWORD(0xda8764d7a2d130cc);
    P[5] = UWORD(0x005f68d914add78a);
    NN_ADD_6(V, P, T);

    /* V_5 = c + z V_6   (6 x 6 limbs) */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    P[3] = V[3];
    P[4] = V[4];
    P[5] = V[5];
    flint_mpn_mulhigh_n(T, z + 3, P, 6);
    P[0] = UWORD(0x52acf7c86b1d5d31);
    P[1] = UWORD(0x43fb6730ac9edf4e);
    P[2] = UWORD(0x44d76a98f7d36937);
    P[3] = UWORD(0xbc019c9698f878f2);
    P[4] = UWORD(0xafe606d2e4d1e65f);
    P[5] = UWORD(0x00eb69e870abeefd);
    NN_ADD_6(V, P, T);

    /* V_4 = c + z V_5   (7 x 6 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    P[4] = V[3];
    P[5] = V[4];
    P[6] = V[5];
    flint_mpn_mulhigh_n(T, z + 2, P, 7);
    P[0] = UWORD(0x156782f23c9614e3);
    P[1] = UWORD(0xff8f5bbd5cacef87);
    P[2] = UWORD(0xf8dc83f4b95907db);
    P[3] = UWORD(0xa31c0122d9ce740b);
    P[4] = UWORD(0x286aa3a066807579);
    P[5] = UWORD(0xeb6a3872e9f6403b);
    P[6] = UWORD(0x0244dc6abcd84791);
    NN_ADD_7(V, P, T);

    /* V_3 = c + z V_4   (7 x 7 limbs) */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    P[3] = V[3];
    P[4] = V[4];
    P[5] = V[5];
    P[6] = V[6];
    flint_mpn_mulhigh_n(T, z + 2, P, 7);
    P[0] = UWORD(0xccb5aee927760599);
    P[1] = UWORD(0x605993d220b043e7);
    P[2] = UWORD(0x043e7ccb5aee9277);
    P[3] = UWORD(0xe9277605993d220b);
    P[4] = UWORD(0xd220b043e7ccb5ae);
    P[5] = UWORD(0xcb5aee9277605993);
    P[6] = UWORD(0x05993d220b043e7c);
    NN_ADD_7(V, P, T);

    /* V_2 = c + z V_3   (8 x 7 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    P[4] = V[3];
    P[5] = V[4];
    P[6] = V[5];
    P[7] = V[6];
    flint_mpn_mulhigh_n(T, z + 1, P, 8);
    P[0] = UWORD(0xdd0dd0dd0dd0dd0d);
    P[1] = UWORD(0x0dd0dd0dd0dd0dd0);
    P[2] = UWORD(0xd0dd0dd0dd0dd0dd);
    P[3] = UWORD(0xdd0dd0dd0dd0dd0d);
    P[4] = UWORD(0x0dd0dd0dd0dd0dd0);
    P[5] = UWORD(0xd0dd0dd0dd0dd0dd);
    P[6] = UWORD(0xdd0dd0dd0dd0dd0d);
    P[7] = UWORD(0x0dd0dd0dd0dd0dd0);
    NN_ADD_8(V, P, T);

    /* V_1 = c + z V_2   (8 x 8 limbs) */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    P[3] = V[3];
    P[4] = V[4];
    P[5] = V[5];
    P[6] = V[6];
    P[7] = V[7];
    flint_mpn_mulhigh_n(T, z + 1, P, 8);
    P[0] = UWORD(0x2222222222222222);
    P[1] = UWORD(0x2222222222222222);
    P[2] = UWORD(0x2222222222222222);
    P[3] = UWORD(0x2222222222222222);
    P[4] = UWORD(0x2222222222222222);
    P[5] = UWORD(0x2222222222222222);
    P[6] = UWORD(0x2222222222222222);
    P[7] = UWORD(0x2222222222222222);
    NN_ADD_8(V, P, T);

    /* V_0 = c + z V_1   (9 x 8 limbs) */
    P[0] = UWORD(0);
    P[1] = V[0];
    P[2] = V[1];
    P[3] = V[2];
    P[4] = V[3];
    P[5] = V[4];
    P[6] = V[5];
    P[7] = V[6];
    P[8] = V[7];
    flint_mpn_mulhigh_n(T, z + 0, P, 9);
    P[0] = UWORD(0x5555555555555555);
    P[1] = UWORD(0x5555555555555555);
    P[2] = UWORD(0x5555555555555555);
    P[3] = UWORD(0x5555555555555555);
    P[4] = UWORD(0x5555555555555555);
    P[5] = UWORD(0x5555555555555555);
    P[6] = UWORD(0x5555555555555555);
    P[7] = UWORD(0x5555555555555555);
    P[8] = UWORD(0x5555555555555555);
    mpn_add_n(V, P, T, 9);

    /* tan = x + x^3 V_0 */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    P[3] = V[3];
    P[4] = V[4];
    P[5] = V[5];
    P[6] = V[6];
    P[7] = V[7];
    P[8] = V[8];
    flint_mpn_mulhigh_n(T, z, x, 9);
    flint_mpn_mulhigh_n(V, T, P, 9);
    mpn_add_n(res, x, V, 9);
}

void
_fixed_trig_opt_9(nn_ptr ysin, nn_ptr ycos, nn_ptr ytan,
    nn_srcptr x)
{
    _fixed_tan_halfangle_mid(ysin, ycos, ytan, x, 9, 16,
        _fixed_tan_series_9);
}

void
fixed_sin_cos_opt_9(nn_ptr ysin, nn_ptr ycos, nn_srcptr x)
{
    _fixed_trig_opt_9(ysin, ycos, NULL, x);
}

void
fixed_tan_opt_9(nn_ptr res, nn_srcptr x)
{
    _fixed_trig_opt_9(NULL, NULL, res, x);
}

#endif /* FLINT_BITS == 64 */
