/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* GENERATED by dev/tune_fixed.py (trig, n = 3, r = 9) -- do not
   edit directly; retune or re-emit with
       python3 dev/tune_fixed.py trig 3 --pin 9 --emit */

#include "flint.h"
#include "longlong.h"
#include "mpn_extras.h"
#include "fixed.h"
#include "impl.h"
#include "hand_mulhi.inc"
#include "tan_rotate.inc"

#if FLINT_BITS == 64

/* tan, n = 3, r = 9: 9 levels, widths [3, 3, 2, 2, 2, 2, 1, 1, 1] */
static void
_fixed_tan_series_3(nn_ptr res, nn_srcptr x)
{
    ulong z[3], V[3], T[3], P[3], Z[2];
    ulong v, w1, w0, h, l;
    slong i;

    (void) v; (void) w1; (void) w0; (void) h; (void) l;
    (void) i; (void) Z; (void) V; (void) T; (void) P;

    flint_mpn_sqrhigh(z, x, 3);

    v = UWORD(0x000fabebb9a68b32);

    /* V_7 = c + z V_8   (1 x 1 limbs) */
    v = n_mulhi(z[2], v);
    v = UWORD(0x0026ab049006ce88) + v;

    /* V_6 = c + z V_7   (1 x 1 limbs) */
    v = n_mulhi(z[2], v);
    v = UWORD(0x005f68d914add78a) + v;

    /* V_5 = c + z V_6   (2 x 1 limbs) */
    _fixed_mulhi_2x1(&h, &l, z[2], z[1], v);
    add_ssaaaa(w1, w0, UWORD(0x00eb69e870abeefd), UWORD(0xafe606d2e4d1e65f), h, l);

    /* V_4 = c + z V_5   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[2], z[1], w1, w0);
    add_ssaaaa(w1, w0, UWORD(0x0244dc6abcd84791), UWORD(0xeb6a3872e9f6403b), h, l);

    /* V_3 = c + z V_4   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[2], z[1], w1, w0);
    add_ssaaaa(w1, w0, UWORD(0x05993d220b043e7c), UWORD(0xcb5aee9277605993), h, l);

    /* V_2 = c + z V_3   (2 x 2 limbs) */
    _fixed_mulhi_2x2_sloppy(&h, &l, z[2], z[1], w1, w0);
    add_ssaaaa(w1, w0, UWORD(0x0dd0dd0dd0dd0dd0), UWORD(0xdd0dd0dd0dd0dd0d), h, l);

    /* V_1 = c + z V_2   (3 x 2 limbs) */
    P[0] = UWORD(0);
    P[1] = w0; P[2] = w1;
    flint_mpn_mulhigh_n(T, z + 0, P, 3);
    P[0] = UWORD(0x2222222222222222);
    P[1] = UWORD(0x2222222222222222);
    P[2] = UWORD(0x2222222222222222);
    NN_ADD_3(V, P, T);

    /* V_0 = c + z V_1   (3 x 3 limbs) */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    flint_mpn_mulhigh_n(T, z + 0, P, 3);
    P[0] = UWORD(0x5555555555555555);
    P[1] = UWORD(0x5555555555555555);
    P[2] = UWORD(0x5555555555555555);
    NN_ADD_3(V, P, T);

    /* tan = x + x^3 V_0 */
    P[0] = V[0];
    P[1] = V[1];
    P[2] = V[2];
    flint_mpn_mulhigh_n(T, z, x, 3);
    flint_mpn_mulhigh_n(V, T, P, 3);
    NN_ADD_3(res, x, V);
}

void
_fixed_trig_opt_3(nn_ptr ysin, nn_ptr ycos, nn_ptr ytan,
    nn_srcptr x)
{
    slong num, nc;
    const int r = 9;
    int c;
    ulong t[3], u[3], wx[4], wy[4];
    ulong T[3], D[4], h[3], A[3], B[3], C[3];
    ulong S[3], N[6], R[4], rem[3], v[3];
    slong * used;
    TMP_INIT;

    _fixed_atans_ensure(3, r);
    nc = _fixed_atans_n;

    TMP_START;
    used = TMP_ALLOC(FIXED_BITWISE_REDUCE_USED_ALLOC(r) * sizeof(slong));

    t[0] = (x[0] >> 1) | (x[1] << (FLINT_BITS - 1));
    t[1] = (x[1] >> 1) | (x[2] << (FLINT_BITS - 1));
    t[2] = x[2] >> 1;
    num = _fixed_bitwise_reduce(t, 3, r, 1, _fixed_atans, nc, used);
    _fixed_tan_rotate_3(wx, wy, used, num);
    _fixed_tan_series_3(u, t);          /* u = tan(t') */

    /* TT = wy + wx u < 0.64 (n limbs) */
    flint_mpn_mulhigh_n(h, wx, u, 3);
    if (wx[3])
        NN_ADD_3(h, h, u);
    NN_ADD_3(T, h, wy);
    /* DE = wx - wy u in (0.72, 1.17) */
    flint_mpn_mulhigh_n(h, wy, u, 3);
    sub_ddddmmmmssss(D[3], D[2], D[1], D[0],
        wx[3], wx[2], wx[1], wx[0],
        UWORD(0), h[2], h[1], h[0]);

    /* halved together when DE reaches one: DE normalized */
    if (D[3])
    {
        D[0] = (D[0] >> 1) | (D[1] << (FLINT_BITS - 1));
        D[1] = (D[1] >> 1) | (D[2] << (FLINT_BITS - 1));
        D[2] >>= 1;
        D[2] |= UWORD(1) << (FLINT_BITS - 1);
        T[0] = (T[0] >> 1) | (T[1] << (FLINT_BITS - 1));
        T[1] = (T[1] >> 1) | (T[2] << (FLINT_BITS - 1));
        T[2] >>= 1;
    }

    /* A = TT DE, B = DE^2, C = TT^2 (A unconditionally: proving
       the sin/tan branches imply its initialization is beyond the
       compiler, and a cos-only caller wastes one cheap mulhigh) */
    flint_mpn_mulhigh_n(A, T, D, 3);
    flint_mpn_sqrhigh(B, D, 3);
    flint_mpn_sqrhigh(C, T, 3);

    N[0] = ~UWORD(0);
    N[1] = ~UWORD(0);
    N[2] = ~UWORD(0);
    N[3] = ~UWORD(0);
    N[4] = ~UWORD(0);
    N[5] = ~UWORD(0) >> 1;

    if (ysin != NULL || ycos != NULL)
    {
        /* S = B + C = DE^2 (1 + t^2), normalized to [0.5, 1):
           c = 2 - e is the doubling shift of sin = 2^(2-e) A R */
        ulong cy;
        add_ssssaaaaaaaa(cy, S[2], S[1], S[0],
            UWORD(0), B[2], B[1], B[0],
            UWORD(0), C[2], C[1], C[0]);
        if (cy)
        {
            S[0] = (S[0] >> 1) | (S[1] << (FLINT_BITS - 1));
            S[1] = (S[1] >> 1) | (S[2] << (FLINT_BITS - 1));
            S[2] >>= 1;
            S[2] |= UWORD(1) << (FLINT_BITS - 1);
            c = 1;
        }
        else if (!(S[2] >> (FLINT_BITS - 1)))
        {
            S[2] = (S[2] << 1) | (S[1] >> (FLINT_BITS - 1));
            S[1] = (S[1] << 1) | (S[0] >> (FLINT_BITS - 1));
            S[0] = S[0] << 1;
            c = 3;
        }
        else
            c = 2;

        mpn_tdiv_qr(R, rem, 0, N, 6, S, 3);

        if (ysin != NULL)
        {
            flint_mpn_mulhigh_n(v, A, R, 3);
            ysin[3] = v[2] >> (FLINT_BITS - c);
            ysin[2] = (v[2] << c) | (v[1] >> (FLINT_BITS - c));
            ysin[1] = (v[1] << c) | (v[0] >> (FLINT_BITS - c));
            ysin[0] = v[0] << c;
        }
        if (ycos != NULL)
        {
            flint_mpn_mulhigh_n(v, C, R, 3);
            v[2] = (v[2] << c) | (v[1] >> (FLINT_BITS - c));
            v[1] = (v[1] << c) | (v[0] >> (FLINT_BITS - c));
            v[0] = v[0] << c;
            if (v[0] == 0 && v[1] == 0 && v[2] == 0)
            {
                ycos[0] = 0;
                ycos[1] = 0;
                ycos[2] = 0;
                ycos[3] = 1;   /* cos exactly one */
            }
            else
            {
                sub_dddmmmsss(ycos[2], ycos[1], ycos[0],
                    UWORD(0), UWORD(0), UWORD(0),
                    v[2], v[1], v[0]);
                ycos[3] = 0;
            }
        }
    }

    if (ytan != NULL)
    {
        /* W = B - C = DE^2 (1 - t^2) > 0.175: at most two leading
           zero bits; tan = 2^(2+e) A R < 1.56 */
        sub_dddmmmsss(S[2], S[1], S[0],
            B[2], B[1], B[0],
            C[2], C[1], C[0]);
        c = flint_clz(S[2]);
        if (c)
        {
            S[2] = (S[2] << c) | (S[1] >> (FLINT_BITS - c));
            S[1] = (S[1] << c) | (S[0] >> (FLINT_BITS - c));
            S[0] = S[0] << c;
        }
        c += 2;

        mpn_tdiv_qr(R, rem, 0, N, 6, S, 3);

        flint_mpn_mulhigh_n(v, A, R, 3);
        ytan[3] = v[2] >> (FLINT_BITS - c);
        ytan[2] = (v[2] << c) | (v[1] >> (FLINT_BITS - c));
        ytan[1] = (v[1] << c) | (v[0] >> (FLINT_BITS - c));
        ytan[0] = v[0] << c;
    }

    TMP_END;
}


void
fixed_sin_cos_opt_3(nn_ptr ysin, nn_ptr ycos, nn_srcptr x)
{
    _fixed_trig_opt_3(ysin, ycos, NULL, x);
}

void
fixed_tan_opt_3(nn_ptr res, nn_srcptr x)
{
    _fixed_trig_opt_3(NULL, NULL, res, x);
}

#endif /* FLINT_BITS == 64 */
