#!/usr/bin/env python3
"""Regenerate src/fixed/tan_rotate.inc (run from the top-level FLINT
directory: python3 dev/gen_fixed_tan_rotate.py > src/fixed/tan_rotate.inc).

The rotation W = prod (1 + i 2^-i) of the tangent half-angle
reconstruction, in registers, for the small sizes.

The generic loop materializes wx >> i and wy >> i into scratch buffers
each time round -- zeroing them, then filling them with an mpn_rshift or
a copy, then an mpn_sub and an mpn_add.  None of that is necessary: the
components fit in registers, the shift is a pair of funnel shifts, and
the updates are NN_SUB_k / NN_ADD_k.  The only run-time quantity is the
index, whose limb offset selects one of a handful of emitted cases.

wx carries a unit limb (it falls from 1 towards 0.72 and back up to at
most 1.1645); wy stays below 0.92 and needs none.  Both updates read the
OLD components, so the two shifted vectors are formed first.
"""

NMIN, NMAX = 1, 7


SUB = {2: "sub_ddmmss", 3: "sub_dddmmmsss", 4: "sub_ddddmmmmssss",
       5: "sub_dddddmmmmmsssss", 6: "sub_ddddddmmmmmmssssss",
       7: "sub_dddddddmmmmmmmsssssss",
       8: "sub_ddddddddmmmmmmmmssssssss"}
ADD = {2: "add_ssaaaa", 3: "add_sssaaaaaa", 4: "add_ssssaaaaaaaa",
       5: "add_sssssaaaaaaaaaa", 6: "add_ssssssaaaaaaaaaaaa",
       7: "add_sssssssaaaaaaaaaaaaaa"}


def emit(o, n):
    wn = n + 1
    o("static void")
    o("_fixed_tan_rotate_" + str(n) + "(nn_ptr wxp, nn_ptr wyp,")
    o("    const slong * used, slong num)")
    o("{")
    o("    ulong " + ", ".join("X%d" % k for k in range(wn)) + ";")
    o("    ulong " + ", ".join("Y%d" % k for k in range(n)) + ";")
    o("    ulong " + ", ".join("a%d" % k for k in range(n)) + ";")
    o("    ulong " + ", ".join("b%d" % k for k in range(n)) + ";")
    o("    slong j;")
    o("")
    for k in range(n):
        o("    X%d = 0;" % k)
    o("    X%d = 1;" % n)
    for k in range(n):
        o("    Y%d = 0;" % k)
    o("")
    o("    for (j = 0; j < num; j++)")
    o("    {")
    o("        slong i = used[j], q = i / FLINT_BITS;")
    o("        int b = (int) (i - q * FLINT_BITS);")
    o("")
    o("        switch (q)")
    o("        {")
    for q in range(wn):
        o("        case %d:" % q)
        o("            if (b == 0)")
        o("            {")
        for k in range(n):
            s = "X%d" % (k + q) if k + q <= n else "UWORD(0)"
            o("                a%d = %s;" % (k, s))
        for k in range(n):
            s = "Y%d" % (k + q) if k + q < n else "UWORD(0)"
            o("                b%d = %s;" % (k, s))
        o("            }")
        o("            else")
        o("            {")
        for k in range(n):
            hi = "X%d" % (k + q + 1) if k + q + 1 <= n else "UWORD(0)"
            lo = "X%d" % (k + q) if k + q <= n else "UWORD(0)"
            if hi == "UWORD(0)" and lo == "UWORD(0)":
                o("                a%d = UWORD(0);" % k)
            else:
                o("                a%d = MPN_RIGHT_SHIFT_LOW(%s, %s, b);"
                  % (k, hi, lo))
        for k in range(n):
            hi = "Y%d" % (k + q + 1) if k + q + 1 < n else "UWORD(0)"
            lo = "Y%d" % (k + q) if k + q < n else "UWORD(0)"
            if hi == "UWORD(0)" and lo == "UWORD(0)":
                o("                b%d = UWORD(0);" % k)
            else:
                o("                b%d = MPN_RIGHT_SHIFT_LOW(%s, %s, b);"
                  % (k, hi, lo))
        o("            }")
        o("            break;")
    o("        default:")
    for k in range(n):
        o("            a%d = UWORD(0);" % k)
    for k in range(n):
        o("            b%d = UWORD(0);" % k)
    o("            break;")
    o("        }")
    o("")
    o("        /* (wx, wy) <- (wx - wy 2^-i, wy + wx 2^-i), on the OLD")
    o("           values.  wy stays below 0.92 and needs no unit limb,")
    o("           and cannot carry out. */")
    xs = ", ".join("X%d" % k for k in range(wn - 1, -1, -1))
    bs = ", ".join(["UWORD(0)"] + ["b%d" % k for k in range(n - 1, -1, -1)])
    o("        " + SUB[wn] + "(" + xs + ",")
    o("            " + xs + ",")
    o("            " + bs + ");")
    if n == 1:
        o("        Y0 += a0;")
    else:
        ys = ", ".join("Y%d" % k for k in range(n - 1, -1, -1))
        az = ", ".join("a%d" % k for k in range(n - 1, -1, -1))
        o("        " + ADD[n] + "(" + ys + ",")
        o("            " + ys + ",")
        o("            " + az + ");")
    o("    }")
    o("")
    for k in range(wn):
        o("    wxp[%d] = X%d;" % (k, k))
    for k in range(n):
        o("    wyp[%d] = Y%d;" % (k, k))
    o("    wyp[%d] = 0;" % n)
    o("}")
    o("")


def main():
    out = []
    o = out.append
    o("/* Generated by dev/gen_fixed_tan_rotate.py -- the rotation")
    o("   W = prod (1 + i 2^-i) in registers, for the small sizes.")
    o("   Do not edit by hand. */")
    o("")
    for n in range(NMIN, NMAX + 1):
        emit(o, n)
    o("static void (* const _fixed_tan_rotate_tab[])")
    o("    (nn_ptr, nn_ptr, const slong *, slong) = {")
    o("    NULL,")
    for n in range(NMIN, NMAX + 1):
        o("    _fixed_tan_rotate_%d," % n)
    o("};")
    print("\n".join(out))


if __name__ == "__main__":
    main()
