# Generates src/dfloat/exp_tables.c: constants for the exponential
# function as 5-term double expansions (about 265 bits), with the
# maximum residual of each table recorded.  Run from the root of the
# repository: python3 dev/gen_dfloat_exp_tables.py (needs mpmath).
from mpmath import mp, mpf, exp, log, factorial
mp.prec = 500
K = 5
import math
def ulp(d):
    m, e = math.frexp(d)
    return math.ldexp(1.0, e - 53)
def nearest(v):
    # round to the nearest double, checked
    d = float(v)
    assert abs(v - mpf(d)) <= mpf(ulp(d)) / 2
    return d
def split(v):
    out = []
    for _ in range(K):
        d = nearest(v); out.append(d); v -= mpf(d)
    return out, abs(v)
def emit_table(f, name, vals):
    maxres = mpf(0)
    f.write("const double %s[%d][%d] = {\n" % (name, len(vals), K))
    for v in vals:
        ds, res = split(v)
        maxres = max(maxres, res)
        f.write("    {" + ", ".join(x.hex() for x in ds) + "},\n")
    f.write("};\n")
    return maxres
with open("src/dfloat/exp_tables.c", "w") as f:
    f.write("""/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* GENERATED by dev/gen_dfloat_exp_tables.py -- do not edit.  Each constant is a
   5-term double expansion (nearest rounding term by term); the tail
   beyond the 5 terms is at most _dfloat_exp_tab_err in absolute value
   for every entry. */

#include "fp_contract.h"
#include "dfloat.h"

""")
    res = mpf(0)
    res = max(res, emit_table(f, "_dfloat_exp_T1", [exp(mpf(i)/256) for i in range(-89, 90)]))
    res = max(res, emit_table(f, "_dfloat_exp_T2", [exp(mpf(j)/65536) for j in range(-128, 129)]))
    # expm1: exp(i/256) - 1 and exp(j/65536) - 1 (relative accuracy)
    res = max(res, emit_table(f, "_dfloat_exp_E1", [exp(mpf(i)/256) - 1 for i in range(-89, 90)]))
    res = max(res, emit_table(f, "_dfloat_exp_E2", [exp(mpf(j)/65536) - 1 for j in range(-128, 129)]))
    res = max(res, emit_table(f, "_dfloat_exp_ln2", [log(2)]))
    # log 2 as a 42-bit leading term (so that k L0 is exact for
    # |k| < 2^11) followed by nearest doubles of the remainder
    v = log(2)
    L0 = math.ldexp(round(math.ldexp(1.0, 41) * float(v)) , -41) # 42 significant bits since 1/2 <= log 2 < 1
    assert L0 == float(mpf(L0)) and abs(v - mpf(L0)) <= mpf(2) ** -42
    ln2s = [L0]; v -= mpf(L0)
    for _ in range(5):
        d = nearest(v); ln2s.append(d); v -= mpf(d)
    f.write("\n/* log 2 = L0 + L1 + ... + L5 with L0 having 42 significant bits;\n   the residual after L0..L_i is at most 2^%s for i = 1, 2, 3, 4, 5 */\n" % ", ".join(str(math.ceil(math.log2(abs(float(log(2) - sum(mpf(t) for t in ln2s[:i+1])))))) for i in range(1, 6)))
    f.write("const double _dfloat_exp_ln2_42[6] = {" + ", ".join(x.hex() for x in ln2s) + "};\n")
    res = max(res, emit_table(f, "_dfloat_exp_invfac", [1/factorial(k) for k in range(0, 13)]))

    # trigonometric functions: sin, cos of i/64 (i = 0..50) and of
    # j/2^13 (j = 0..64) as [entry][sin/cos][5 terms]; the Taylor
    # coefficients (-1)^(k//2)/k!; pi/2 with a 33-bit head
    from mpmath import sin, cos, pi
    def emit_table2(f, name, vals):
        maxres = mpf(0)
        f.write("const double %s[%d][2][%d] = {\n" % (name, len(vals), K))
        for (a, b) in vals:
            da, ra = split(a); db, rb = split(b)
            maxres = max(maxres, ra, rb)
            f.write("    {{" + ", ".join(x.hex() for x in da) + "}, {" + ", ".join(x.hex() for x in db) + "}},\n")
        f.write("};\n")
        return maxres
    res = max(res, emit_table2(f, "_dfloat_trig_A", [(sin(mpf(i)/64), cos(mpf(i)/64)) for i in range(0, 51)]))
    res = max(res, emit_table2(f, "_dfloat_trig_B", [(sin(mpf(j)/2**13), cos(mpf(j)/2**13)) for j in range(0, 65)]))
    # the double kernel's table: the nearest doubles of sin(i/64),
    # cos(i/64) for i = -50..50 (index i + 50)
    f.write("const double _dfloat_trig_A1[101][2] = {\n")
    for i in range(-50, 51):
        f.write("    {%s, %s},\n" % (nearest(sin(mpf(i)/64)).hex(), nearest(cos(mpf(i)/64)).hex()))
    f.write("};\n")
    res = max(res, emit_table(f, "_dfloat_trig_coef", [(-1)**(k//2) / factorial(k) for k in range(0, 15)]))
    v = pi / 2
    P0 = math.ldexp(round(math.ldexp(1.0, 32) * float(v)), -32)   # 33 significant bits (1 <= pi/2 < 2)
    assert abs(v - mpf(P0)) <= mpf(2) ** -33
    pi2 = [P0]; v -= mpf(P0)
    for _ in range(5):
        d = nearest(v); pi2.append(d); v -= mpf(d)
    f.write("\n/* pi/2 = P0 + P1 + ... + P5 with P0 having 33 significant bits;\n   the residual after P0..P_i is at most 2^%s for i = 1, 2, 3, 4, 5 */\n" % ", ".join(str(math.ceil(math.log2(abs(float(pi / 2 - sum(mpf(t) for t in pi2[:i+1])))))) for i in range(1, 6)))
    f.write("const double _dfloat_trig_pi2_33[6] = {" + ", ".join(x.hex() for x in pi2) + "};\n")
    # logarithm: two reciprocal tables.  Level 1: c_i = 1 + i/128 for
    # i = -38..-1 (m < 1) and 1 + i/64 for i = 0..27 (m >= 1), so that
    # |m r_i - 1| <= 2^-7 for m in [sqrt(2)/2, sqrt(2)) (index i + 38);
    # level 2: c_j = 1 + j/2^13 for j = -64..64 (index j + 64).  The
    # entries are r = the nearest double of 1/c and L = -log(r) of that
    # rounded r (5 terms), so that log(y) = log(y r) + L exactly.
    from mpmath import atan
    def emit_recip(f, rname, lname, cs):
        f.write("const double %s[%d] = {\n" % (rname, len(cs)))
        rs = []
        for c in cs:
            r = nearest(1 / c); rs.append(r)
            f.write("    %s,\n" % r.hex())
        f.write("};\n")
        return emit_table(f, lname, [-log(mpf(r)) for r in rs])
    # level 1 (128 entries): m = x 2^-e in [M0, 2 M0) with M0 =
    # 0.70703125 (bits 0x3fe6a00000000000), and the index ix = the 7
    # bits below the exponent of bits(x) - bits(M0), so that the entry
    # ix covers the bit offsets [ix 2^45, (ix + 1) 2^45): a range of
    # width 2^-8 in m below 1 (ix <= 74) and 2^-7 above (ix >= 75);
    # r = 1/m_mid rounded, with m_mid the value at the middle offset,
    # except r = 1 (L = 0) for the two entries adjacent to 1 (74, 75),
    # which keeps log x relative near x = 1; |m r - 1| <= 2^-7 always.
    import struct
    M0_BITS = 0x3fe6a00000000000
    def from_bits(b):
        return struct.unpack("<d", struct.pack("<Q", b))[0]
    assert from_bits(M0_BITS) == 0.70703125 and from_bits(M0_BITS + 75 * 2**45) == 1.0
    mids = [mpf(from_bits(M0_BITS + ix * 2**45 + 2**44)) for ix in range(128)]
    mids[74] = mids[75] = mpf(1)
    res = max(res, emit_recip(f, "_dfloat_log_R1", "_dfloat_log_L1", mids))
    res = max(res, emit_recip(f, "_dfloat_log_R2", "_dfloat_log_L2",
        [1 + mpf(j) / 2**13 for j in range(-64, 65)]))
    # log1p(z) = sum_k (-1)^(k+1) z^k / k (index k, entry 0 unused)
    res = max(res, emit_table(f, "_dfloat_log_coef", [mpf(0)] + [mpf((-1)**(k + 1)) / k for k in range(1, 18)]))
    # arctangent: atan(i/64) for i = 0..64, pi/2, and the coefficients
    # (-1)^k / (2k+1) of z^(2k+1) (index k)
    res = max(res, emit_table(f, "_dfloat_atan_C", [atan(mpf(i) / 64) for i in range(0, 65)]))
    res = max(res, emit_table(f, "_dfloat_pi_2", [pi / 2]))
    res = max(res, emit_table(f, "_dfloat_atan_coef", [mpf((-1)**k) / (2 * k + 1) for k in range(0, 16)]))
    # the constants of the generic rings: pi, Euler's constant, Catalan's
    # constant, log 2 (index DFLOAT_CONST_*)
    from mpmath import euler, catalan
    res = max(res, emit_table(f, "_dfloat_const", [pi, +euler, +catalan, log(2)]))
    import math
    e = math.ceil(math.log2(res))
    f.write("\n/* max residual: about 2^%d */\nconst double _dfloat_exp_tab_err = 0x1p%d;\n" % (e, e + 1))
    print("max residual 2^%.2f -> bound 2^%d" % (math.log2(res), e + 1))
