/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* Lazy fields: real forms (trigonometric values, real cyclotomic extensions, realification). */

/* (for recursive mutexes: pthread_mutexattr_settype) */
#define _GNU_SOURCE

#include "gr_tower/lazy_impl.h"

/*
    The tangent normal form of the real trigonometric constants. The
    values at angles in (pi/D) Z (sines, cosines, tangents, and the real
    elements of the cyclotomic fields they generate) lie in Q(zeta_c)^+
    with c = 4D (D odd) or c = 2D (D even), a field generated by
    tau = tan(pi/M) with M = D (D odd), D/2 (D = 2 mod 4) or 2D (4 | D)
    (the smallest M with lcm(M, 4) = c). With w = exp(2 pi i/M) =
    (1 + i tau)^2 / (1 + tau^2), every root of unity of order dividing c
    is i^a w^b, so a real element E(zeta_n) is a polynomial in tau,
    computed in Q[x]/(m) (m the minimal polynomial of tau) with Gaussian
    arithmetic. This is the algebraic counterpart of the half-angle
    substitution used for the real trigonometric functions at other real
    arguments (cos x = (1 - u^2)/(1 + u^2) with u = tan(x/2)).
*/
static ulong
_tan_level(ulong D)
{
    return (D % 2 == 1) ? D : (D % 4 == 2) ? D / 2 : 2 * D;
}

/* (ar + i ai)(br + i bi) modulo m (the results may alias the inputs) */
static void
_gauss_mul(fmpq_poly_t rr, fmpq_poly_t ri, const fmpq_poly_t ar, const fmpq_poly_t ai,
    const fmpq_poly_t br, const fmpq_poly_t bi, const fmpq_poly_t m)
{
    fmpq_poly_t t, u, v;
    fmpq_poly_init(t);
    fmpq_poly_init(u);
    fmpq_poly_init(v);
    fmpq_poly_mul(t, ar, br);
    fmpq_poly_mul(u, ai, bi);
    fmpq_poly_sub(t, t, u);
    fmpq_poly_mul(u, ar, bi);
    fmpq_poly_mul(v, ai, br);
    fmpq_poly_add(u, u, v);
    fmpq_poly_rem(rr, t, m);
    fmpq_poly_rem(ri, u, m);
    fmpq_poly_clear(t);
    fmpq_poly_clear(u);
    fmpq_poly_clear(v);
}

/* (rr + i ri) = (ar + i ai)^e modulo m, by binary powering */
static void
_gauss_pow(fmpq_poly_t rr, fmpq_poly_t ri, const fmpq_poly_t ar, const fmpq_poly_t ai, ulong e, const fmpq_poly_t m)
{
    fmpq_poly_t br, bi;
    fmpq_poly_init(br);
    fmpq_poly_init(bi);
    fmpq_poly_set(br, ar);
    fmpq_poly_set(bi, ai);
    fmpq_poly_one(rr);
    fmpq_poly_zero(ri);
    while (e != 0)
    {
        if (e & 1)
            _gauss_mul(rr, ri, rr, ri, br, bi, m);
        e >>= 1;
        if (e != 0)
            _gauss_mul(br, bi, br, bi, br, bi, m);
    }
    fmpq_poly_clear(br);
    fmpq_poly_clear(bi);
}

/* res = tau = tan(pi/M) (M >= 3): a quadratic one through its square
   root, otherwise the generator tan(pi/M) of a tower (hash-consed) */
int
_gr_tower_lazy_tan_pi_gen(gr_tower_lazy_elem_t res, ulong M, qqbar_t z, gr_ctx_t ctx)
{
    gr_tower_flat_struct * F;
    slong gid;
    int status;

    qqbar_tan_pi(z, 1, M);
    if (qqbar_degree(z) <= 2)
        return _gr_tower_lazy_set_qqbar_structured(res, z, ctx);

    status = _gr_tower_lazy_qqbar_tower(&F, &gid, z, GR_TOWER_TAN_PI, M, NULL, ctx);
    if (status == GR_SUCCESS)
        _gr_tower_lazy_set_gen_d(res, F, gr_tower_gid_order(F->T, gid), ctx);
    return status;
}

/* res = P(t) for P in Q[x] of degree < the degree of t: directly in the
   flat representation when t is a generator, else by Horner */
static int
_gr_tower_lazy_eval_fmpq_poly(gr_tower_lazy_elem_t res, const fmpq_poly_t P, gr_tower_lazy_elem_t t, gr_ctx_t ctx)
{
    const fmpz_mpoly_struct * num, * den;
    slong i, len = fmpq_poly_length(P);
    int status = GR_SUCCESS;

    t = _gr_tower_lazy_flat_view(t);
    num = fmpz_mpoly_q_numref(&t->elem.flat.data);
    den = fmpz_mpoly_q_denref(&t->elem.flat.data);

    if (len <= 1)
    {
        fmpq_t c;
        fmpq_init(c);
        fmpq_poly_get_coeff_fmpq(c, P, 0);
        status = _gr_tower_lazy_set_fmpq(res, c, ctx);
        fmpq_clear(c);
        return status;
    }

    if (fmpz_mpoly_length(num, t->elem.flat.mctx) == 1 && fmpz_mpoly_is_one(den, t->elem.flat.mctx) &&
        fmpz_is_one(num->coeffs) && fmpz_mpoly_total_degree_si(num, t->elem.flat.mctx) == 1)
    {
        /* t is a generator x_v */
        gr_tower_flat_struct * F = t->F;
        fmpz_mpoly_q_t r;
        fmpz_mpoly_t xv, xp;
        fmpz_mpoly_q_init(r, t->elem.flat.mctx);
        fmpz_mpoly_init(xv, t->elem.flat.mctx);
        fmpz_mpoly_init(xp, t->elem.flat.mctx);
        fmpz_mpoly_set(xv, num, t->elem.flat.mctx);
        fmpz_mpoly_one(xp, t->elem.flat.mctx);
        for (i = 0; i < len; i++)
        {
            if (i > 0)
                fmpz_mpoly_mul(xp, xp, xv, t->elem.flat.mctx);
            {
                fmpz_mpoly_t tm;
                fmpz_mpoly_init(tm, t->elem.flat.mctx);
                fmpz_mpoly_scalar_mul_fmpz(tm, xp, P->coeffs + i, t->elem.flat.mctx);
                fmpz_mpoly_add(fmpz_mpoly_q_numref(r), fmpz_mpoly_q_numref(r), tm, t->elem.flat.mctx);
                fmpz_mpoly_clear(tm, t->elem.flat.mctx);
            }
        }
        fmpz_mpoly_set_fmpz(fmpz_mpoly_q_denref(r), P->den, t->elem.flat.mctx);
        fmpz_mpoly_q_canonicalise(r, t->elem.flat.mctx);
        status = gr_tower_flat_reduce(r, F);
        if (status == GR_SUCCESS)
            _gr_tower_lazy_set_flat(res, F, r, t->elem.flat.mctx, ctx);
        fmpz_mpoly_q_clear(r, t->elem.flat.mctx);
        fmpz_mpoly_clear(xv, t->elem.flat.mctx);
        fmpz_mpoly_clear(xp, t->elem.flat.mctx);
        return status;
    }

    {
        /* Horner's rule through the method table (the lock is recursive) */
        gr_ctx_struct * QQ = LAZY(ctx)->base;
        gr_poly_t Q;
        gr_tower_lazy_elem_struct acc;

        gr_poly_init(Q, QQ);
        _gr_tower_lazy_init(&acc, ctx);
        status = gr_poly_set_fmpq_poly(Q, P, QQ);
        if (status == GR_SUCCESS)
            status = gr_poly_evaluate_other(&acc, Q, t, ctx, QQ);
        if (status == GR_SUCCESS)
            _gr_tower_lazy_swap(res, &acc, ctx);
        _gr_tower_lazy_clear(&acc, ctx);
        gr_poly_clear(Q, QQ);
    }
    return status;
}

/* res = E(zeta_n) for E in Q[x] with E(zeta_n) real, in the tangent
   normal form; GR_DOMAIN if the value is not real */
static int
_gr_tower_lazy_real_cyclotomic_ext(gr_tower_lazy_elem_t res, const fmpq_poly_t E_in, ulong n, int normalize, gr_ctx_t ctx)
{
    fmpq_poly_t E, m, gr, gi, br, bi, zr, zi, t;
    fmpq_t c;
    qqbar_t z;
    ulong g = n, D, M, k;
    slong a, b = -1, len = fmpq_poly_length(E_in);
    int status = GR_SUCCESS;

    if (n == 0)
        return GR_DOMAIN;
    /* (the arithmetic on the orders below is in slong) */
    if (n > (UWORD(1) << (FLINT_BITS / 2 - 2)))
        return GR_UNABLE;

    /* the order actually needed (unless the level is imposed, so that
       several values share one generator) */
    for (k = 1; k < (ulong) len && normalize; k++)
        if (!fmpz_is_zero(E_in->coeffs + k))
            g = n_gcd(g, k);
    if (!normalize)
        g = 1;
    n /= g;

    fmpq_poly_init(E);
    fmpq_init(c);
    for (k = 0; k < (ulong) len; k++)
    {
        fmpq_poly_get_coeff_fmpq(c, E_in, k);
        if (!fmpq_is_zero(c))
        {
            fmpq_t d;
            fmpq_init(d);
            fmpq_poly_get_coeff_fmpq(d, E, (k / g) % n);
            fmpq_add(d, d, c);
            fmpq_poly_set_coeff_fmpq(E, (k / g) % n, d);
            fmpq_clear(d);
        }
    }

    fmpq_poly_init(m);
    fmpq_poly_init(gr);
    fmpq_poly_init(gi);
    fmpq_poly_init(br);
    fmpq_poly_init(bi);
    fmpq_poly_init(zr);
    fmpq_poly_init(zi);
    fmpq_poly_init(t);
    qqbar_init(z);

    D = (n % 2 == 1) ? n : n / 2;

    if (D <= 2)
    {
        /* zeta_n in {1, -1, i}: the real part directly */
        fmpq_t s;
        fmpq_init(s);
        for (k = 0; k < (ulong) fmpq_poly_length(E); k++)
        {
            fmpq_poly_get_coeff_fmpq(c, E, k);
            if (n == 1 || (n == 2 && k % 2 == 0) || (n == 4 && k % 4 == 0))
                fmpq_add(s, s, c);
            else if ((n == 2 && k % 2 == 1) || (n == 4 && k % 4 == 2))
                fmpq_sub(s, s, c);
        }
        status = _gr_tower_lazy_set_fmpq(res, s, ctx);
        fmpq_clear(s);
        goto cleanup;
    }

    M = _tan_level(D);

    /* zeta_n = i^a w^b: 2/n = a/2 + 2b/M (mod 2) */
    for (a = 0; a < 4 && b < 0; a++)
    {
        slong num = (4 - a * (slong) n) * (slong) M, den = 4 * (slong) n;
        if (num % den == 0)
        {
            b = num / den;
            b = ((b % (slong) M) + (slong) M) % (slong) M;
            break;
        }
    }
    if (b < 0)
    {
        status = GR_UNABLE;   /* (not expected) */
        goto cleanup;
    }

    /* the minimal polynomial of tau */
    qqbar_tan_pi(z, 1, M);
    fmpq_poly_set_fmpz_poly(m, QQBAR_POLY(z));

    /* g = i^a (1 + i x)^(2b) / (1 + x^2)^b */
    fmpq_poly_one(br);
    fmpq_poly_zero(bi);
    fmpq_poly_set_coeff_si(bi, 1, 1);              /* 1 + i x */
    _gauss_pow(gr, gi, br, bi, 2 * (ulong) b, m);
    if (b > 0)
    {
        fmpq_poly_t G, S, T1;
        fmpq_poly_init(G);
        fmpq_poly_init(S);
        fmpq_poly_init(T1);
        fmpq_poly_one(t);
        fmpq_poly_set_coeff_si(t, 2, 1);           /* 1 + x^2 */
        fmpq_poly_xgcd(G, S, T1, t, m);
        fmpq_poly_zero(T1);
        _gauss_pow(t, G, S, T1, b, m);              /* (S^b, real) */
        fmpq_poly_mul(gr, gr, t);
        fmpq_poly_rem(gr, gr, m);
        fmpq_poly_mul(gi, gi, t);
        fmpq_poly_rem(gi, gi, m);
        fmpq_poly_clear(G);
        fmpq_poly_clear(S);
        fmpq_poly_clear(T1);
    }
    for (k = 0; k < (ulong) a; k++)
    {
        /* times i */
        fmpq_poly_swap(gr, gi);
        fmpq_poly_neg(gr, gr);
    }

    /* E(g) by Horner, over the nonzero terms (the gaps by powering) */
    fmpq_poly_zero(zr);
    fmpq_poly_zero(zi);
    {
        slong prev = -1;
        for (a = fmpq_poly_length(E) - 1; a >= 0; a--)
        {
            if (fmpz_is_zero(E->coeffs + a))
                continue;
            if (prev >= 0)
            {
                _gauss_pow(br, bi, gr, gi, prev - a, m);
                _gauss_mul(zr, zi, zr, zi, br, bi, m);
            }
            fmpq_poly_get_coeff_fmpq(c, E, a);
            fmpq_poly_add_fmpq(zr, zr, c);
            prev = a;
        }
        if (prev > 0)
        {
            _gauss_pow(br, bi, gr, gi, prev, m);
            _gauss_mul(zr, zi, zr, zi, br, bi, m);
        }
    }

    if (!fmpq_poly_is_zero(zi))
    {
        status = GR_DOMAIN;
        goto cleanup;
    }

    /* (a rational value directly; otherwise strictly in the tangent
       normal form, also when the value lies in a quadratic subfield --
       cos(2 pi/5) = (3 - tan(pi/5)^2)/8 -- so that the values at one
       level share one generator) */
    if (fmpq_poly_degree(zr) <= 0)
    {
        fmpq_poly_get_coeff_fmpq(c, zr, 0);
        status = _gr_tower_lazy_set_fmpq(res, c, ctx);
        goto cleanup;
    }

    {
        gr_tower_lazy_elem_struct tau;
        _gr_tower_lazy_init(&tau, ctx);
        status = _gr_tower_lazy_tan_pi_gen(&tau, M, z, ctx);
        if (status == GR_SUCCESS)
            status = _gr_tower_lazy_eval_fmpq_poly(res, zr, &tau, ctx);
        _gr_tower_lazy_clear(&tau, ctx);
    }

cleanup:
    fmpq_poly_clear(E);
    fmpq_poly_clear(m);
    fmpq_poly_clear(gr);
    fmpq_poly_clear(gi);
    fmpq_poly_clear(br);
    fmpq_poly_clear(bi);
    fmpq_poly_clear(zr);
    fmpq_poly_clear(zi);
    fmpq_poly_clear(t);
    fmpq_clear(c);
    qqbar_clear(z);
    return status;
}

static int
_gr_tower_lazy_real_cyclotomic(gr_tower_lazy_elem_t res, const fmpq_poly_t E, ulong n, gr_ctx_t ctx)
{
    return _gr_tower_lazy_real_cyclotomic_ext(res, E, n, 1, ctx);
}

/* sin, cos or tan (which = 0, 1, 2) of r pi in the tangent normal form */
static int
_gr_tower_lazy_trig_pi_real(gr_tower_lazy_elem_t res, const fmpq_t r, int which, gr_ctx_t ctx)
{
    fmpq_poly_t E;
    fmpz_t e, q2;
    int status;

    if (!fmpz_abs_fits_ui(fmpq_denref(r)) || fmpz_cmp_ui(fmpq_denref(r), WORD(1) << 20) > 0)
        return GR_UNABLE;

    if (which == 2)
    {
        /* tan(r pi) = sin(2 r pi) / (1 + cos(2 r pi)), at the level of the
           doubled angle (tan(pi/12) = 2 - sqrt(3), not through tan(pi/24)) */
        gr_tower_lazy_elem_struct s, co;
        fmpq_t r2;
        fmpq_init(r2);
        fmpq_mul_2exp(r2, r, 1);
        _gr_tower_lazy_init(&s, ctx);
        _gr_tower_lazy_init(&co, ctx);
        status = _gr_tower_lazy_trig_pi_real(&s, r2, 0, ctx);
        if (status == GR_SUCCESS)
            status = _gr_tower_lazy_trig_pi_real(&co, r2, 1, ctx);
        if (status == GR_SUCCESS)
            status = _gr_tower_lazy_add_ui(&co, &co, 1, ctx);
        fmpq_clear(r2);
        if (status == GR_SUCCESS)
        {
            truth_t z = _gr_tower_lazy_is_zero(&co, ctx);
            if (z == T_TRUE)
                status = GR_DOMAIN;
            else if (z == T_UNKNOWN)
                status = GR_UNABLE;
            else
                status = _gr_tower_lazy_div(res, &s, &co, ctx);
        }
        _gr_tower_lazy_clear(&s, ctx);
        _gr_tower_lazy_clear(&co, ctx);
        return status;
    }

    /* cos(r pi) = Re zeta_{2q}^p, sin(r pi) = cos(r pi - pi/2) =
       Re zeta_{4q}^(2p - q) */
    fmpq_poly_init(E);
    fmpz_init(e);
    fmpz_init(q2);
    if (which == 1)
    {
        fmpz_mul_2exp(q2, fmpq_denref(r), 1);
        fmpz_mod(e, fmpq_numref(r), q2);
    }
    else
    {
        fmpz_mul_2exp(q2, fmpq_denref(r), 2);
        fmpz_mul_2exp(e, fmpq_numref(r), 1);
        fmpz_sub(e, e, fmpq_denref(r));
        fmpz_mod(e, e, q2);
    }
    /* (the real part: (x^e + x^(n - e))/2 at zeta_n) */
    {
        ulong n = fmpz_get_ui(q2), ee = fmpz_get_ui(e) % n;
        fmpq_poly_set_coeff_si(E, ee, 1);
        fmpq_poly_set_coeff_si(E, (n - ee) % n, (ee == (n - ee) % n) ? 2 : 1);
        fmpq_poly_scalar_div_si(E, E, 2);
        status = _gr_tower_lazy_real_cyclotomic(res, E, n, ctx);
    }
    fmpq_poly_clear(E);
    fmpz_clear(e);
    fmpz_clear(q2);
    return status;
}

int
_gr_tower_lazy_trig_pi_real_locked(gr_tower_lazy_elem_t res, const fmpq_t r, int which, gr_ctx_t ctx)
{
    int status;
    _gr_tower_lazy_lock(ctx);
    status = _gr_tower_lazy_trig_pi_real(res, r, which, ctx);
    _gr_tower_lazy_unlock(ctx);
    return status;
}

int
_gr_tower_lazy_real_cyclotomic_eval(gr_tower_lazy_elem_t res, const fmpq_poly_t E, ulong n, gr_ctx_t ctx)
{
    int status;
    _gr_tower_lazy_lock(ctx);
    status = _gr_tower_lazy_real_cyclotomic(res, E, n, ctx);
    _gr_tower_lazy_unlock(ctx);
    return status;
}

/*
    The real form of a real element x whose representation involves
    roots of unity zeta_j = exp(2 pi i / n_j) (and otherwise only real
    generators): x = Re(x) = sum A cos(2 pi sum_j e_j / n_j) over the
    terms A prod zeta_j^e_j of the numerator (the A being real), a
    denominator involving the roots of unity being cleared first through
    the nested representation. x is left unchanged when this does not
    apply (another nonreal generator, orders above the limit).
*/
#define LAZY_REALIFY_MAX_ROOTS 8

int
_gr_tower_lazy_realify(gr_tower_lazy_elem_t x, gr_ctx_t ctx)
{
    gr_tower_flat_struct * F;
    gr_tower_struct * T;
    fmpz_mpoly_ctx_struct * mctx;
    const fmpz_mpoly_struct * num;
    int * used, * used_den;
    slong d, nz = 0, j, t, nvars, nkeys = 0;
    slong zvar[LAZY_REALIFY_MAX_ROOTS], zord[LAZY_REALIFY_MAX_ROOTS];
    fmpz_mpoly_struct * A;
    fmpq * keys;
    ulong * exps;
    fmpz_t cf;
    fmpq_t ang, u;
    gr_tower_lazy_elem_struct y, e, cs, sum;
    ulong nlevel = 1;
    int status = GR_SUCCESS, ok = 1, den_z = 0, too_large = 0;

    _gr_tower_lazy_update(x);
    F = x->F;
    T = F->T;
    mctx = x->elem.flat.mctx;
    nvars = mctx->minfo->nvars;

    used = flint_calloc(nvars, sizeof(int));
    used_den = flint_calloc(nvars, sizeof(int));
    fmpz_mpoly_q_used_vars(used, &x->elem.flat.data, mctx);
    fmpz_mpoly_q_used_vars_den(used_den, &x->elem.flat.data, mctx);

    for (d = 0; d < T->num_gens && ok; d++)
    {
        slong v = GR_TOWER_FLAT_VAR_D(F, d);
        const gr_tower_gen_struct * g = GR_TOWER_GEN(T, d);

        if (v >= nvars || !used[v])
            continue;

        if ((g->def_kind == GR_TOWER_ROOT_OF_UNITY && g->def_param > 2) || _gr_tower_lazy_gen_is_i(T, d))
        {
            /* (i, a root of x^2 + 1, also when adjoined as a square root) */
            slong o = (g->def_kind == GR_TOWER_ROOT_OF_UNITY) ? g->def_param : 4;
            if (nz == LAZY_REALIFY_MAX_ROOTS || o > LAZY(ctx)->options[GR_TOWER_OPT_REALIFY_ORDER_LIMIT])
                ok = 0;
            else
            {
                den_z |= used_den[v];
                zvar[nz] = v;
                zord[nz] = o;
                nz++;
            }
        }
        else if (!arb_is_zero(acb_imagref(&g->enclosure)))
            ok = 0;
    }

    flint_free(used);
    flint_free(used_den);

    if (!ok || nz == 0)
        return GR_SUCCESS;

    _gr_tower_lazy_init(&y, ctx);
    status = _gr_tower_lazy_set(&y, x, ctx);

    /* a denominator free of the algebraic generators, through the
       nested representation */
    if (den_z && status == GR_SUCCESS)
    {
        slong k = _gr_tower_lazy_alg_level(&y);
        gr_ctx_struct * Fk = gr_tower_field_at(T, k);
        gr_ptr w;
        fmpz_mpoly_q_t r;
        GR_TMP_INIT(w, Fk);
        fmpz_mpoly_q_init(r, F->mctx);
        status = _gr_tower_lazy_get_nested(w, &y);
        if (status == GR_SUCCESS)
            status = gr_tower_flat_set_nested_at(r, w, k, F);
        if (status == GR_SUCCESS)
        {
            _gr_tower_lazy_fresh(&y, F, T->num_gens, ctx);
            _gr_tower_lazy_install(&y, F, r, ctx);
        }
        fmpz_mpoly_q_clear(r, F->mctx);
        GR_TMP_CLEAR(w, Fk);
        mctx = y.elem.flat.mctx;
        if (status == GR_SUCCESS)
        {
            int * ud = flint_calloc(mctx->minfo->nvars, sizeof(int));
            fmpz_mpoly_q_used_vars_den(ud, &y.elem.flat.data, mctx);
            for (j = 0; j < nz; j++)
                if (ud[zvar[j]])
                    status = GR_UNABLE;
            flint_free(ud);
        }
        if (status != GR_SUCCESS)
        {
            _gr_tower_lazy_clear(&y, ctx);
            return GR_SUCCESS;   /* (left unchanged) */
        }
    }

    /* the terms of the numerator grouped by the angle sum_j e_j / n_j
       (modulo 1) */
    num = fmpz_mpoly_q_numref(&y.elem.flat.data);
    nvars = mctx->minfo->nvars;
    A = flint_malloc(sizeof(fmpz_mpoly_struct) * FLINT_MAX(num->length, 1));
    keys = flint_malloc(sizeof(fmpq) * FLINT_MAX(num->length, 1));
    exps = flint_malloc(sizeof(ulong) * nvars);
    fmpz_init(cf);
    fmpq_init(ang);
    fmpq_init(u);

    for (t = 0; t < num->length; t++)
    {
        slong key;
        fmpz_mpoly_get_term_exp_ui(exps, num, t, mctx);
        fmpz_mpoly_get_term_coeff_fmpz(cf, num, t, mctx);
        fmpq_zero(ang);
        for (j = 0; j < nz; j++)
        {
            fmpq_set_si(u, exps[zvar[j]] % zord[j], zord[j]);
            fmpq_add(ang, ang, u);
            exps[zvar[j]] = 0;
        }
        /* modulo 1 */
        fmpz_fdiv_r(fmpq_numref(ang), fmpq_numref(ang), fmpq_denref(ang));
        for (key = 0; key < nkeys; key++)
            if (fmpq_equal(keys + key, ang))
                break;
        if (key == nkeys)
        {
            fmpz_mpoly_init(A + key, mctx);
            fmpq_init(keys + key);
            fmpq_set(keys + key, ang);
            nkeys++;
        }
        fmpz_mpoly_push_term_fmpz_ui(A + key, cf, exps, mctx);
    }

    _gr_tower_lazy_init(&e, ctx);
    _gr_tower_lazy_init(&cs, ctx);
    _gr_tower_lazy_init(&sum, ctx);
    status |= _gr_tower_lazy_zero(&sum, ctx);

    /* the cosines in the tangent normal form, at the common level N
       (the lcm of the orders, which the order limit bounds as well:
       beyond it, the element is left as it is) */
    {
        ulong N = 1, limit = LAZY(ctx)->options[GR_TOWER_OPT_REALIFY_ORDER_LIMIT];
        for (t = 0; t < nkeys; t++)
        {
            ulong o = fmpz_get_ui(fmpq_denref(keys + t)), g = n_gcd(N, o);
            if ((N / g) > limit / o)
            {
                N = 0;
                break;
            }
            N = (N / g) * o;
        }
        nlevel = N;
        too_large = (N == 0 || N > limit);
    }

    for (t = 0; t < nkeys && status == GR_SUCCESS && !too_large; t++)
    {
        fmpz_mpoly_q_t r;

        {
            /* cos(2 pi e/N) = Re zeta_N^e = (x^e + x^(N - e))/2 at zeta_N */
            fmpq_poly_t E;
            ulong ee = fmpz_get_ui(fmpq_numref(keys + t)) * (nlevel / fmpz_get_ui(fmpq_denref(keys + t)));
            fmpq_poly_init(E);
            fmpq_poly_set_coeff_si(E, ee % nlevel, 1);
            fmpq_poly_set_coeff_si(E, (nlevel - ee) % nlevel, (ee % nlevel == (nlevel - ee) % nlevel) ? 2 : 1);
            fmpq_poly_scalar_div_si(E, E, 2);
            status = _gr_tower_lazy_real_cyclotomic_ext(&cs, E, nlevel, 0, ctx);
            fmpq_poly_clear(E);
        }

        fmpz_mpoly_sort_terms(A + t, mctx);
        fmpz_mpoly_combine_like_terms(A + t, mctx);
        fmpz_mpoly_q_init(r, mctx);
        fmpz_mpoly_set(fmpz_mpoly_q_numref(r), A + t, mctx);
        fmpz_mpoly_set(fmpz_mpoly_q_denref(r), fmpz_mpoly_q_denref(&y.elem.flat.data), mctx);
        fmpz_mpoly_q_canonicalise(r, mctx);
        _gr_tower_lazy_fresh(&e, y.F, T->num_gens, ctx);
        _gr_tower_lazy_install(&e, y.F, r, ctx);
        fmpz_mpoly_q_clear(r, mctx);
        status |= _gr_tower_lazy_mul(&e, &e, &cs, ctx);
        status |= _gr_tower_lazy_add(&sum, &sum, &e, ctx);
    }

    if (status == GR_SUCCESS && !too_large)
        status = _gr_tower_lazy_set(x, &sum, ctx);

    for (t = 0; t < nkeys; t++)
    {
        fmpz_mpoly_clear(A + t, mctx);
        fmpq_clear(keys + t);
    }
    flint_free(A);
    flint_free(keys);
    flint_free(exps);
    fmpz_clear(cf);
    fmpq_clear(ang);
    fmpq_clear(u);
    _gr_tower_lazy_clear(&e, ctx);
    _gr_tower_lazy_clear(&cs, ctx);
    _gr_tower_lazy_clear(&sum, ctx);
    _gr_tower_lazy_clear(&y, ctx);
    return status;
}

/* the real form, for the functions of the real fields */
int
_gr_tower_lazy_realify_locked(gr_tower_lazy_elem_t x, gr_ctx_t ctx)
{
    int status;
    _gr_tower_lazy_lock(ctx);
    status = _gr_tower_lazy_realify(x, ctx);
    _gr_tower_lazy_unlock(ctx);
    return status;
}
