/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

#include "ulong_extras.h"
#include "fmpz.h"
#include "fmpz_factor.h"
#include "fmpz_mpoly.h"
#include "fmpz_mpoly_q.h"
#include "nmod.h"
#include "nmod_poly.h"
#include "nmod_poly_factor.h"
#include "fq_nmod.h"
#include "fq_nmod_poly.h"
#include "fq_nmod_poly_factor.h"
#include "gr_tower.h"
#include "gr_tower/impl.h"

/*
    Modular irreducibility proofs.

    Let O = Z[a_1, ..., a_k] be the ring generated by the algebraic
    generators of a tower over QQ (a triangular system of moduli with
    integer coefficients, the leading coefficients being integers c_j),
    and let l be a prime not dividing any c_j. A chain of roots
    alpha_1, ..., alpha_k in a finite field F_q, q = l^m, of the moduli
    (alpha_j a root of m_j(alpha_1, ..., alpha_{j-1}, x)), each root being
    simple, defines a ring homomorphism phi: O -> F_q, a place of the
    tower. Its kernel P is a maximal ideal at which O is regular (the
    Jacobian of the triangular system is nonsingular there), so the local
    ring O_P is a discrete valuation ring, in particular integrally closed
    in the field K of the tower. Consequences:

    - if m_{k+1}(alpha, x) is irreducible over F_q (and of full degree),
      then m_{k+1} is irreducible over K: the coefficients of a monic
      factorization over K are integral over O_P, hence in O_P, and would
      reduce to a factorization over F_q.

    - if an element a of K with phi(a) defined and nonzero is not a p-th
      power in F_q (p | q - 1 and phi(a)^((q-1)/p) != 1), then a is not a
      p-th power in K: a p-th root b of a would be integral over O_P,
      hence in O_P, with phi(b)^p = phi(a). By Capelli's theorem, X^n - a
      is then irreducible over K when this holds for every prime p | n,
      together with a not in -4 K^4 when 4 | n.

    The statements are relative to the moduli of the lower steps being
    irreducible, as the status of a step is.
*/

#define MODULAR_PRIME_BITS 16

typedef struct
{
    ulong l;
    slong m;
    fq_nmod_ctx_t fqctx;
    fq_nmod_struct * alpha;     /* alpha[j - 1] for step j */
    fq_nmod_struct ** pow;      /* pow[j - 1][e] = alpha_j^e, e < d_j */
    slong k;                    /* steps covered by the chain */
    fq_nmod_struct * tval;      /* values of the transcendental generators (NULL: none may occur) */
}
place_struct;

static void
_place_init(place_struct * P, ulong l, slong m, slong k)
{
    slong j;
    P->l = l;
    P->m = m;
    fq_nmod_ctx_init_ui(P->fqctx, l, m, "w");
    P->alpha = flint_malloc(sizeof(fq_nmod_struct) * FLINT_MAX(k, 1));
    P->pow = flint_calloc(FLINT_MAX(k, 1), sizeof(fq_nmod_struct *));
    for (j = 0; j < k; j++)
        fq_nmod_init(P->alpha + j, P->fqctx);
    P->k = 0;
    P->tval = NULL;
}

static void
_place_clear(place_struct * P, slong k, gr_tower_t T)
{
    slong j, e;
    for (j = 0; j < k; j++)
    {
        fq_nmod_clear(P->alpha + j, P->fqctx);
        if (P->pow[j] != NULL)
        {
            for (e = 0; e < gr_tower_step_degree(T, j + 1); e++)
                fq_nmod_clear(P->pow[j] + e, P->fqctx);
            flint_free(P->pow[j]);
        }
    }
    flint_free(P->alpha);
    flint_free(P->pow);
    if (P->tval != NULL)
    {
        for (j = 0; j < T->num_trans; j++)
            fq_nmod_clear(P->tval + j, P->fqctx);
        flint_free(P->tval);
    }
    fq_nmod_ctx_clear(P->fqctx);
}

/* alpha_j^e for e < d_j, once alpha_j is known */
static void
_place_set_root(place_struct * P, slong j, const fq_nmod_t alpha, gr_tower_t T)
{
    slong d = gr_tower_step_degree(T, j), e;
    fq_nmod_set(P->alpha + j - 1, alpha, P->fqctx);
    P->pow[j - 1] = flint_malloc(sizeof(fq_nmod_struct) * d);
    for (e = 0; e < d; e++)
    {
        fq_nmod_init(P->pow[j - 1] + e, P->fqctx);
        if (e == 0)
            fq_nmod_one(P->pow[j - 1] + e, P->fqctx);
        else
            fq_nmod_mul(P->pow[j - 1] + e, P->pow[j - 1] + e - 1, alpha, P->fqctx);
    }
    P->k = j;
}

/*
    Evaluates the polynomial f (in the variables of the flat machinery F)
    at the place: the variables of the steps 1..P->k are replaced by the
    roots, the variable of step j (if j > 0) becomes the variable of res.
    Returns 0 if f involves any other variable, or has too many terms.
*/
static int
_eval_at_place(fq_nmod_poly_t res, const fmpz_mpoly_t f, slong j, const place_struct * P, gr_tower_flat_t F)
{
    gr_tower_struct * T = F->T;
    slong i, t, nvars = F->cap, len = f->length;
    slong * step_of_var;
    ulong * exp;
    fq_nmod_t c, u;
    int ok = 1;

    if (len > GR_TOWER_OPTION(T, GR_TOWER_OPT_MODULAR_TERMS_LIMIT))
        return 0;

    /* (step_of_var: the step of an algebraic variable, or -2 - j for the
       transcendental generator j when the place gives it a value) */
    step_of_var = flint_malloc(sizeof(slong) * nvars);
    for (i = 0; i < nvars; i++)
        step_of_var[i] = -1;
    for (i = 1; i <= T->length; i++)
        step_of_var[GR_TOWER_FLAT_VAR(F, i)] = i;
    if (P->tval != NULL)
        for (i = 1; i <= T->num_trans; i++)
            step_of_var[GR_TOWER_FLAT_TVAR(F, i)] = -1 - i;

    exp = flint_malloc(sizeof(ulong) * nvars);
    fq_nmod_init(c, P->fqctx);
    fq_nmod_init(u, P->fqctx);
    fq_nmod_poly_zero(res, P->fqctx);

    for (t = 0; t < len && ok; t++)
    {
        slong ej = 0;
        fmpz_mpoly_get_term_exp_ui(exp, f, t, F->mctx);
        fq_nmod_set_ui(c, fmpz_fdiv_ui(f->coeffs + t, P->l), P->fqctx);
        for (i = 0; i < nvars && ok; i++)
        {
            slong s = step_of_var[i];
            if (exp[i] == 0)
                continue;
            if (s == j && j > 0)
                ej = exp[i];
            else if (s >= 1 && s <= P->k && (slong) exp[i] < gr_tower_step_degree(T, s))
                fq_nmod_mul(c, c, P->pow[s - 1] + exp[i], P->fqctx);
            else if (s >= 1 && s <= P->k)
            {
                fq_nmod_pow_ui(u, P->alpha + s - 1, exp[i], P->fqctx);
                fq_nmod_mul(c, c, u, P->fqctx);
            }
            else if (s <= -2)
            {
                fq_nmod_pow_ui(u, P->tval + (-2 - s), exp[i], P->fqctx);
                fq_nmod_mul(c, c, u, P->fqctx);
            }
            else
                ok = 0;
        }
        if (ok && !fq_nmod_is_zero(c, P->fqctx))
        {
            fq_nmod_poly_get_coeff(u, res, ej, P->fqctx);
            fq_nmod_add(u, u, c, P->fqctx);
            fq_nmod_poly_set_coeff(res, ej, u, P->fqctx);
        }
    }

    fq_nmod_clear(c, P->fqctx);
    fq_nmod_clear(u, P->fqctx);
    flint_free(exp);
    flint_free(step_of_var);
    return ok;
}

/* The flat ideal element of step j when its size is acceptable. */
static const fmpz_mpoly_struct *
_modulus_flat(gr_tower_flat_t F, slong j)
{
    if (F->ideal[j - 1] == NULL &&
        _gr_tower_nested_num_coeffs(gr_tower_step_minpoly(F->T, j), gr_tower_field_at(F->T, j), GR_TOWER_OPTION(F->T, GR_TOWER_OPT_MODULAR_TERMS_LIMIT)) > GR_TOWER_OPTION(F->T, GR_TOWER_OPT_MODULAR_TERMS_LIMIT))
        return NULL;
    return _gr_tower_flat_ideal_elem(F, j);
}

/*
    Extends the chain of roots of the place to the steps up to k, choosing
    a random simple root of each modulus (when there are several, a
    different chain gives a different place). Returns 1 on success.
*/
static int
_place_extend(place_struct * P, slong k, gr_tower_t T, flint_rand_t state)
{
    gr_tower_flat_struct * F = &T->flat;
    slong j;
    int ok = 1;

    for (j = P->k + 1; j <= k && ok; j++)
    {
        const fmpz_mpoly_struct * m = _modulus_flat(F, j);
        fq_nmod_poly_t f;
        fq_nmod_poly_factor_t r;
        slong i, count = 0, pick;

        if (m == NULL)
            return 0;

        fq_nmod_poly_init(f, P->fqctx);
        ok = _eval_at_place(f, m, j, P, F) &&
             fq_nmod_poly_degree(f, P->fqctx) == gr_tower_step_degree(T, j);

        if (ok && P->m == 1)
        {
            /* prime field: the specialized nmod_poly factorization is
               far faster than root finding in the generic extension */
            nmod_poly_t g;
            nmod_poly_factor_t fac;
            slong e, n = fq_nmod_poly_degree(f, P->fqctx);
            fq_nmod_t c;

            nmod_poly_init(g, P->l);
            fq_nmod_init(c, P->fqctx);
            for (e = 0; e <= n; e++)
            {
                fq_nmod_poly_get_coeff(c, f, e, P->fqctx);
                nmod_poly_set_coeff_ui(g, e, nmod_poly_get_coeff_ui(c, 0));
            }
            nmod_poly_factor_init(fac);
            nmod_poly_factor(fac, g);
            for (i = 0; i < fac->num; i++)
                count += (fac->exp[i] == 1 && nmod_poly_degree(fac->p + i) == 1);
            if (count == 0)
                ok = 0;
            else
            {
                pick = n_randint(state, count);
                for (i = 0; i < fac->num; i++)
                {
                    if (fac->exp[i] == 1 && nmod_poly_degree(fac->p + i) == 1 && pick-- == 0)
                    {
                        /* the root of the monic linear factor x - alpha */
                        ulong a0 = nmod_poly_get_coeff_ui(fac->p + i, 0);
                        fq_nmod_set_ui(c, nmod_neg(a0, g->mod), P->fqctx);
                        _place_set_root(P, j, c, T);
                    }
                }
            }
            nmod_poly_factor_clear(fac);
            fq_nmod_clear(c, P->fqctx);
            nmod_poly_clear(g);
        }
        else if (ok)
        {
            fq_nmod_poly_factor_init(r, P->fqctx);
            fq_nmod_poly_roots(r, f, 1, P->fqctx);
            for (i = 0; i < r->num; i++)
                count += (r->exp[i] == 1);
            if (count == 0)
                ok = 0;
            else
            {
                fq_nmod_t alpha;
                pick = n_randint(state, count);
                fq_nmod_init(alpha, P->fqctx);
                for (i = 0; i < r->num; i++)
                {
                    if (r->exp[i] == 1 && pick-- == 0)
                    {
                        /* the root of the monic linear factor x - alpha */
                        fq_nmod_poly_get_coeff(alpha, r->poly + i, 0, P->fqctx);
                        fq_nmod_neg(alpha, alpha, P->fqctx);
                    }
                }
                _place_set_root(P, j, alpha, T);
                fq_nmod_clear(alpha, P->fqctx);
            }
            fq_nmod_poly_factor_clear(r, P->fqctx);
        }

        fq_nmod_poly_clear(f, P->fqctx);
    }

    return ok;
}

/*
    The degrees m <= MODULAR_MAX_DEG of residue fields F_{l^m} in which
    the first modulus has a root: multiples of the degrees of its
    irreducible factors modulo l (as a bit mask; 0 if l divides the
    leading coefficient or the flat modulus is unavailable).
*/
#define MODULAR_MAX_DEG 4

static ulong
_residue_degrees(gr_tower_t T, ulong l)
{
    gr_tower_flat_struct * F = &T->flat;
    const fmpz_mpoly_struct * m1;
    nmod_poly_t f;
    nmod_poly_factor_t fac;
    slong i, t, d;
    ulong mask = 0;

    if (T->length == 0)
        return (UWORD(1) << (MODULAR_MAX_DEG + 1)) - 2;

    d = gr_tower_step_degree(T, 1);

    m1 = _modulus_flat(F, 1);
    if (m1 == NULL)
        return 0;

    /* the modulus of step 1 must involve its own variable only (not a
       transcendental generator) */
    nmod_poly_init(f, l);
    {
        slong v = GR_TOWER_FLAT_VAR(F, 1);
        ulong * exp = flint_malloc(sizeof(ulong) * F->cap);
        int * used = flint_malloc(sizeof(int) * F->cap);
        int ok = 1;
        fmpz_mpoly_used_vars(used, m1, F->mctx);
        for (i = 0; i < F->cap; i++)
            if (used[i] && i != v)
                ok = 0;
        for (t = 0; t < m1->length && ok; t++)
        {
            fmpz_mpoly_get_term_exp_ui(exp, m1, t, F->mctx);
            nmod_poly_set_coeff_ui(f, exp[v], fmpz_fdiv_ui(m1->coeffs + t, l));
        }
        if (!ok)
        {
            nmod_poly_zero(f);
            /* (a modulus involving transcendental generators: their
               random values at a place decide the residue degrees, so
               every degree is possible a priori; _place_extend decides) */
            if (T->num_trans > 0)
            {
                nmod_poly_clear(f);
                flint_free(exp);
                flint_free(used);
                return (UWORD(1) << (MODULAR_MAX_DEG + 1)) - 2;
            }
        }
        flint_free(exp);
        flint_free(used);
    }

    if (nmod_poly_degree(f) == d)
    {
        nmod_poly_factor_init(fac);
        nmod_poly_factor(fac, f);
        for (i = 0; i < fac->num; i++)
        {
            slong e = nmod_poly_degree(fac->p + i);
            slong k;
            if (fac->exp[i] == 1)
                for (k = e; k <= MODULAR_MAX_DEG; k += e)
                    mask |= UWORD(1) << k;
        }
        nmod_poly_factor_clear(fac);
    }

    nmod_poly_clear(f);
    return mask;
}

/* the algebraic generators of a tower over QQ are all the generators */
static int
_modular_applicable(gr_tower_t T)
{
    /* with transcendental generators, the places are places of the
       algebraic subtower: a modulus or element involving a
       transcendental variable fails to evaluate (and the tower, being
       purely transcendental over the algebraic subtower, does not
       change irreducibility over it) */
    return GR_TOWER_HAS_CAP(T, GR_TOWER_CAP_PLACES);
}

static ulong _progression_modulus(gr_tower_t T, slong len, ulong extra);

static void
_seed(flint_rand_t state, gr_tower_t T, slong k, slong attempt)
{
    flint_rand_init(state);
    flint_rand_set_seed(state, UWORD(0x9e3779b9) * (ulong) (k + 1) + (ulong) attempt, T->moduli_version + 12345);
}

/*
    Eisenstein's criterion at a transcendental generator t: the modulus of
    step k is c X^n + u with c and u free of X, c free of t, t || u (u
    has t-adic valuation 1), and t occurring in no modulus below step k.
    Then the steps below generate a field K(t) with K free of t, over
    which the modulus is irreducible (X^2 - pi, X^3 - 2 pi t over a
    tower of radicals and roots of unity).
*/
static int
_eisenstein_transcendental(gr_tower_t T, slong k)
{
    gr_tower_flat_struct * F = &T->flat;
    const fmpz_mpoly_struct * m = _modulus_flat(F, k);
    slong vx, j, t, i, nvars, n = gr_tower_step_degree(T, k);
    ulong * exp;
    int found = 0;

    if (m == NULL || T->num_trans == 0 || n < 2)
        return 0;

    nvars = F->mctx->minfo->nvars;
    vx = GR_TOWER_FLAT_VAR(F, k);
    exp = flint_malloc(sizeof(ulong) * nvars);

    for (t = 1; t <= T->num_trans && !found; t++)
    {
        slong vt = GR_TOWER_FLAT_VAR_D(F, T->trans[t - 1]);
        slong minval = WORD_MAX;
        int ok = 1;

        for (i = 0; i < m->length && ok; i++)
        {
            fmpz_mpoly_get_term_exp_ui(exp, m, i, F->mctx);
            if (exp[vx] == (ulong) n)
            {
                if (exp[vt] != 0)
                    ok = 0;
            }
            else if (exp[vx] == 0)
                minval = FLINT_MIN(minval, (slong) exp[vt]);
            else
                ok = 0;
        }

        if (!ok || minval != 1)
            continue;

        for (j = 1; j < k && ok; j++)
        {
            const fmpz_mpoly_struct * mj = _modulus_flat(F, j);
            if (mj == NULL || fmpz_mpoly_degree_si(mj, vt, F->mctx) > 0)
                ok = 0;
        }

        found = ok;
    }

    flint_free(exp);
    return found;
}

/*
    The modulus L for primes l = 1 mod L: the lcm of extra and of the
    orders of the roots of unity among the first len steps (at such
    primes the cyclotomic moduli split completely), or 0 if it is large.
*/
static ulong
_progression_modulus(gr_tower_t T, slong len, ulong extra)
{
    ulong L = FLINT_MAX(extra, 1);
    slong i;

    for (i = 1; i <= len && L != 0; i++)
    {
        const gr_tower_gen_struct * g = GR_TOWER_STEP(T, i - 1);
        if (g->def_kind == GR_TOWER_ROOT_OF_UNITY && g->def_param > 0)
        {
            ulong o = g->def_param;
            L = (L / n_gcd(L, o)) * o;
            if (L > (UWORD(1) << 24))
                L = 0;
        }
    }

    return L;
}

/* a random prime l = 1 mod L (L <= 2^24) of at most about 40 bits:
   about 16 bits more than L, so that the progression has primes */
static ulong
_progression_prime(flint_rand_t state, ulong L)
{
    ulong bits = FLINT_MIN(FLINT_BIT_COUNT(L) + 16, 40);
    return n_randprime_mod(state, bits, 1 % L, L, 1);
}

/*
    The schedule of places tried by the proofs: for a budget of `tries`,
    MODULAR_PRIME_FIELD_FACTOR * tries places over prime fields (cheap:
    nmod_poly arithmetic), then tries / MODULAR_EXT_FIELD_DIVISOR primes
    at which places over extension fields of degree up to MODULAR_MAX_DEG
    are tried (root finding there is much slower). Every other prime is
    taken in the progression 1 mod L when L > 1 (the cyclotomic moduli
    then split completely). At every place found (a chain of simple
    roots of the first k moduli), the transcendental generators get
    random values. The iterator initializes P, which the caller clears
    with _place_clear(P, k, T) after use.
*/
#define MODULAR_PRIME_FIELD_FACTOR 3
#define MODULAR_EXT_FIELD_DIVISOR 6

typedef struct
{
    gr_tower_struct * T;
    slong k;                /* steps the places cover */
    ulong prog_L;
    slong tries;
    slong attempt, m;       /* position in the schedule */
    ulong l, degrees;       /* the current prime and its residue degrees */
    flint_rand_struct * state;
}
place_iter_struct;

static void
_place_iter_init(place_iter_struct * it, gr_tower_t T, slong k, ulong prog_L, slong tries, flint_rand_t state)
{
    it->T = T;
    it->k = k;
    it->prog_L = prog_L;
    it->tries = tries;
    it->attempt = -1;
    it->m = MODULAR_MAX_DEG + 1;   /* (forces a new prime) */
    it->l = 0;
    it->degrees = 0;
    it->state = state;
}

static int
_place_iter_next(place_struct * P, place_iter_struct * it)
{
    gr_tower_struct * T = it->T;
    slong total = MODULAR_PRIME_FIELD_FACTOR * it->tries + it->tries / MODULAR_EXT_FIELD_DIVISOR;

    for (;;)
    {
        slong mhi;

        /* the next degree for the current prime, or the next prime */
        it->m++;
        mhi = (it->attempt < MODULAR_PRIME_FIELD_FACTOR * it->tries) ? 1 : MODULAR_MAX_DEG;
        if (it->attempt < 0 || it->m > mhi)
        {
            it->attempt++;
            if (it->attempt >= total)
                return 0;
            it->l = (it->prog_L > 1 && it->attempt % 2 == 0) ? _progression_prime(it->state, it->prog_L)
                                                              : n_randprime(it->state, MODULAR_PRIME_BITS, 1);
            it->degrees = _residue_degrees(T, it->l);
            it->m = (it->attempt < MODULAR_PRIME_FIELD_FACTOR * it->tries) ? 1 : 2;
            mhi = (it->attempt < MODULAR_PRIME_FIELD_FACTOR * it->tries) ? 1 : MODULAR_MAX_DEG;
        }
        if (it->m > mhi || !(it->degrees & (UWORD(1) << it->m)))
            continue;

        _place_init(P, it->l, it->m, it->k);

        /* transcendental generators: random values (a place of the tower
           over the function field at which the moduli below are
           separable is a regular point, with an integrally closed local
           ring, so that the arguments above apply) */
        if (T->num_trans > 0)
        {
            slong jt;
            P->tval = flint_malloc(sizeof(fq_nmod_struct) * T->num_trans);
            for (jt = 0; jt < T->num_trans; jt++)
            {
                fq_nmod_init(P->tval + jt, P->fqctx);
                fq_nmod_set_ui(P->tval + jt, n_randint(it->state, it->l), P->fqctx);
            }
        }

        if (_place_extend(P, it->k, T, it->state))
            return 1;

        _place_clear(P, it->k, T);
    }
}

/*
    Tries to prove that the modulus of step k is irreducible over the
    field of the steps below it, at up to `tries` places. Sets the status
    of the step to PROVEN and returns 1 on success.

    The steps below must be proven: over a quotient ring which is not a
    field (a product of fields), a place sees one of the factors only,
    and irreducibility over that factor says nothing about the factor
    which the tower is refined to later (sqrt(c) with c a square for
    one choice of root_3(3) in a field containing the others).
*/
int
gr_tower_prove_step_modular(gr_tower_t T, slong k, slong tries)
{
    gr_tower_flat_struct * F = &T->flat;
    gr_tower_gen_struct * g = GR_TOWER_STEP(T, k - 1);
    flint_rand_t state;
    slong attempt, d = gr_tower_step_degree(T, k);
    int proved = 0;
    ulong prog_L;

    if (g->status == GR_TOWER_STATUS_PROVEN)
        return 1;
    if (!_modular_applicable(T))
        return 0;
    if (d <= 1)
    {
        _gr_tower_gen_set_status(g, GR_TOWER_STATUS_PROVEN);
        return 1;
    }

    gr_tower_flat_ensure(F);
    if (_modulus_flat(F, k) == NULL)
        return 0;

    /* (the steps below must form a field: the modular argument, and
       Eisenstein's criterion, need the coefficients to be nonzero in the
       field, not only as reduced polynomials) */
    for (attempt = 1; attempt < k; attempt++)
        if (GR_TOWER_STEP(T, attempt - 1)->status != GR_TOWER_STATUS_PROVEN)
            return 0;

    /* (Eisenstein in a transcendental generator: in every factor) */
    if (_eisenstein_transcendental(T, k))
    {
        _gr_tower_gen_set_status(g, GR_TOWER_STATUS_PROVEN);
        return 1;
    }

    _seed(state, T, k, 0);

    /* every other attempt at a prime l = 1 mod L (cyclotomic steps below
       split; for a radical X^n - a, l = 1 mod n is needed for the
       reduction to be irreducible) */
    prog_L = _progression_modulus(T, k - 1, (g->def_kind == GR_TOWER_ROOT && g->def_param > 0) ? (ulong) g->def_param : 1);

    /* a monic modulus whose reduction at a place is irreducible of the
       same degree is irreducible (the valuation ring is integrally
       closed) */
    {
        place_iter_struct it;
        place_struct P;
        _place_iter_init(&it, T, k - 1, prog_L, tries, state);
        while (!proved && _place_iter_next(&P, &it))
        {
            fq_nmod_poly_t f;
            fq_nmod_poly_init(f, P.fqctx);
            if (_eval_at_place(f, _modulus_flat(F, k), k, &P, F) &&
                fq_nmod_poly_degree(f, P.fqctx) == d &&
                fq_nmod_poly_is_irreducible(f, P.fqctx))
                proved = 1;
            fq_nmod_poly_clear(f, P.fqctx);
            _place_clear(&P, k - 1, T);
        }
    }

    flint_rand_clear(state);

    if (proved)
        _gr_tower_gen_set_status(g, GR_TOWER_STATUS_PROVEN);

    return proved;
}

/*
    Attempts a modular proof for every dynamic step of the tower which has
    not been tried with the current moduli. Returns 1 if all steps are
    proven afterwards.
*/
int
gr_tower_prove_modular(gr_tower_t T, slong tries)
{
    slong k;
    int all = 1, all_below = 1;

    /* structural rules first (no computation) */
    for (k = 1; k <= T->length; k++)
    {
        gr_tower_gen_struct * g = GR_TOWER_STEP(T, k - 1);
        if (g->status != GR_TOWER_STATUS_PROVEN && _gr_tower_structural_step_proven(T, k))
            _gr_tower_gen_set_status(g, GR_TOWER_STATUS_PROVEN);
    }

    if (!_modular_applicable(T))
    {
        for (k = 0; k < T->num_gens; k++)
            if (T->gens[k].status != GR_TOWER_STATUS_PROVEN)
                return 0;
        return 1;
    }

    /* (transcendental generators have no proofs) */
    for (k = 0; k < T->num_gens; k++)
        if (T->gens[k].kind != GR_TOWER_ALGEBRAIC && T->gens[k].status != GR_TOWER_STATUS_PROVEN)
            all = 0;

    for (k = 1; k <= T->length; k++)
    {
        gr_tower_gen_struct * g = GR_TOWER_STEP(T, k - 1);

        if (g->status == GR_TOWER_STATUS_PROVEN)
            continue;

        /* (the steps below are proven first: see above; the attempt is
           repeated when they are) */
        if (!all_below)
        {
            gr_tower_prove_step_modular(T, k, tries);
            if (g->status != GR_TOWER_STATUS_PROVEN)
                all = 0;
            continue;
        }

        if (g->proof_version != T->moduli_version + 1)
        {
            g->proof_version = T->moduli_version + 1;

            gr_tower_prove_step_modular(T, k, tries);

            /* the complete method for what the places do not reach
               (moduli reducible modulo every prime, say), while the
               norms stay small (over QQ: with transcendental
               generators, the norms are multivariate and the zero test
               relies on the inversions instead) */
            if (g->status != GR_TOWER_STATUS_PROVEN && T->num_trans == 0)
                gr_tower_prove_step_trager(T, k, GR_TOWER_OPTION(T, GR_TOWER_OPT_TRAGER_DEGREE_LIMIT));
        }

        if (g->status != GR_TOWER_STATUS_PROVEN)
            all = 0, all_below = 0;
    }

    return all;
}

/* phi(a)^((q-1)/p) != 1 for phi(a) != 0, where p | q - 1: a is not a p-th
   power in the residue field */
static int
_not_pth_power(const fq_nmod_t a, ulong p, const place_struct * P)
{
    fmpz_t e;
    fq_nmod_t t;
    int res;

    if (fq_nmod_is_zero(a, P->fqctx))
        return 0;

    fmpz_init(e);
    fmpz_set_ui(e, P->l);
    fmpz_pow_ui(e, e, P->m);
    fmpz_sub_ui(e, e, 1);
    if (!fmpz_divisible_ui(e, p))
    {
        fmpz_clear(e);
        return 0;
    }
    fmpz_divexact_ui(e, e, p);
    fq_nmod_init(t, P->fqctx);
    fq_nmod_pow(t, a, e, P->fqctx);
    res = !fq_nmod_is_one(t, P->fqctx);
    fq_nmod_clear(t, P->fqctx);
    fmpz_clear(e);
    return res;
}

/*
    Proves that X^n - a is irreducible over the field of the tower, for
    the element a given in the flat representation, by Capelli's theorem
    with the modular test of p-th powers. Returns 1 on success.
*/
int
gr_tower_binomial_irreducible_modular(gr_tower_t T, const fmpz_mpoly_q_t a, const fmpz_mpoly_ctx_t actx, ulong n, slong tries)
{
    gr_tower_flat_struct * F = &T->flat;
    fmpz_mpoly_q_t x;
    n_factor_t fac;
    slong i, num_conditions, done;
    int * settled;
    flint_rand_t state;
    int res = 0;
    ulong prog_L;

    if (n <= 1 || !_modular_applicable(T))
        return n == 1;

    /* (over a quotient ring which is not a field, a place sees one of
       its factors only: see gr_tower_prove_step_modular) */
    for (i = 1; i <= T->length; i++)
        if (GR_TOWER_STEP(T, i - 1)->status != GR_TOWER_STATUS_PROVEN)
            return 0;

    gr_tower_flat_ensure(F);
    for (i = 1; i <= T->length; i++)
        if (_modulus_flat(F, i) == NULL)
            return 0;

    fmpz_mpoly_q_init(x, F->mctx);
    if (actx == F->mctx)
        fmpz_mpoly_q_set(x, a, F->mctx);
    else
        gr_tower_flat_convert(x, a, actx, F);
    GR_MUST_SUCCEED(gr_tower_flat_reduce(x, F));

    /* the conditions: a not a p-th power for each prime p | n, and
       -a/4 not a fourth power when 4 | n */
    n_factor_init(&fac);
    n_factor(&fac, n, 1);
    num_conditions = fac.num + ((n % 4 == 0) ? 1 : 0);
    settled = flint_calloc(num_conditions, sizeof(int));
    done = 0;

    _seed(state, T, T->length, (slong) n);

    /* every other attempt uses a prime l = 1 mod L, with L the lcm of n
       and of the orders of the roots of unity of the tower: the
       cyclotomic moduli split completely, and p-th powers are a proper
       subgroup of the residue field for the primes p | n (otherwise
       places of degree one are rare when the orders are large: root_53(2)
       over Q(zeta_53)) */
    prog_L = _progression_modulus(T, T->length, n);

    {
        place_iter_struct it;
        place_struct P;
        _place_iter_init(&it, T, T->length, prog_L, tries, state);
        while (done < num_conditions && _place_iter_next(&P, &it))
        {
            fq_nmod_poly_t num, den;
            fq_nmod_t va, t;

            fq_nmod_poly_init(num, P.fqctx);
            fq_nmod_poly_init(den, P.fqctx);
            fq_nmod_init(va, P.fqctx);
            fq_nmod_init(t, P.fqctx);

            /* (Capelli's test is valid at any place at which a is a unit) */
            if (_eval_at_place(num, fmpz_mpoly_q_numref(x), 0, &P, F) &&
                _eval_at_place(den, fmpz_mpoly_q_denref(x), 0, &P, F) &&
                !fq_nmod_poly_is_zero(den, P.fqctx) && !fq_nmod_poly_is_zero(num, P.fqctx))
            {
                fq_nmod_poly_get_coeff(va, num, 0, P.fqctx);
                fq_nmod_poly_get_coeff(t, den, 0, P.fqctx);
                fq_nmod_inv(t, t, P.fqctx);
                fq_nmod_mul(va, va, t, P.fqctx);

                for (i = 0; i < fac.num; i++)
                    if (!settled[i] && _not_pth_power(va, fac.p[i], &P))
                        settled[i] = 1, done++;

                if (n % 4 == 0 && !settled[fac.num] && P.l != 2)
                {
                    /* -a/4 */
                    fq_nmod_set_ui(t, 4, P.fqctx);
                    fq_nmod_inv(t, t, P.fqctx);
                    fq_nmod_mul(t, t, va, P.fqctx);
                    fq_nmod_neg(t, t, P.fqctx);
                    if (_not_pth_power(t, 4, &P))
                        settled[fac.num] = 1, done++;
                }
            }

            fq_nmod_clear(va, P.fqctx);
            fq_nmod_clear(t, P.fqctx);
            fq_nmod_poly_clear(num, P.fqctx);
            fq_nmod_poly_clear(den, P.fqctx);
            _place_clear(&P, T->length, T);
        }
    }

    res = (done == num_conditions);

    flint_rand_clear(state);
    flint_free(settled);
    fmpz_mpoly_q_clear(x, F->mctx);
    return res;
}

/*
    Whether the polynomial g over the top field of T (nested coefficients,
    monic) is shown to have no root in the field, at one of up to `tries`
    places: if g had a root r in K, the reduction of g at a place where
    its coefficients are integral (their denominators not vanishing)
    would have the root phi(r), r being integral over the local ring O_P,
    which is integrally closed. Transcendental generators are given
    random values at the place (a place of the tower over Q(t) in which
    the moduli have simple roots is a regular point, so that the local
    ring is again integrally closed). The polynomial need not be monic
    if its leading coefficient does not vanish at the place. Returns 1
    when a place without a root of the reduction is found, 0 otherwise
    (nothing is known).
*/
int
gr_tower_poly_no_roots_modular(const gr_poly_t g, gr_tower_t T, slong tries)
{
    gr_tower_flat_struct * F = &T->flat;
    gr_ctx_struct * top = gr_tower_field(T);
    slong i, n = g->length - 1;
    fmpz_mpoly_q_struct * c;
    flint_rand_t state;
    int res = 0, ok = 1;

    if (n < 1 || !_modular_applicable(T))
        return 0;

    gr_tower_flat_ensure(F);
    for (i = 1; i <= T->length; i++)
        if (_modulus_flat(F, i) == NULL)
            return 0;

    c = flint_malloc(sizeof(fmpz_mpoly_q_struct) * (n + 1));
    for (i = 0; i <= n; i++)
    {
        fmpz_mpoly_q_init(c + i, F->mctx);
        if (ok && gr_tower_flat_set_nested_at(c + i, gr_poly_coeff_srcptr(g, i, top), T->length, F) != GR_SUCCESS)
            ok = 0;
        if (ok && (fmpz_mpoly_length(fmpz_mpoly_q_numref(c + i), F->mctx) > GR_TOWER_OPTION(T, GR_TOWER_OPT_MODULAR_TERMS_LIMIT) ||
                   fmpz_mpoly_length(fmpz_mpoly_q_denref(c + i), F->mctx) > GR_TOWER_OPTION(T, GR_TOWER_OPT_MODULAR_TERMS_LIMIT)))
            ok = 0;
    }

    _seed(state, T, T->length, n + 1000);

    /* (places over prime fields only: the root test is a gcd with x^l - x) */
    if (ok)
    {
        place_iter_struct it;
        place_struct P;
        _place_iter_init(&it, T, T->length, 1, tries / MODULAR_PRIME_FIELD_FACTOR + 1, state);
        while (!res && _place_iter_next(&P, &it))
        {
            fq_nmod_poly_t num, den, G;
            fq_nmod_t a, b;
            int good = 1;

            if (P.m != 1)
            {
                _place_clear(&P, T->length, T);
                continue;
            }

            fq_nmod_poly_init(num, P.fqctx);
            fq_nmod_poly_init(den, P.fqctx);
            fq_nmod_poly_init(G, P.fqctx);
            fq_nmod_init(a, P.fqctx);
            fq_nmod_init(b, P.fqctx);

            for (i = 0; i <= n && good; i++)
            {
                good = _eval_at_place(num, fmpz_mpoly_q_numref(c + i), 0, &P, F) &&
                       _eval_at_place(den, fmpz_mpoly_q_denref(c + i), 0, &P, F) &&
                       !fq_nmod_poly_is_zero(den, P.fqctx);
                if (good)
                {
                    fq_nmod_poly_get_coeff(a, num, 0, P.fqctx);
                    fq_nmod_poly_get_coeff(b, den, 0, P.fqctx);
                    fq_nmod_div(a, a, b, P.fqctx);
                    fq_nmod_poly_set_coeff(G, i, a, P.fqctx);
                }
            }

            if (good && fq_nmod_poly_degree(G, P.fqctx) == n)
            {
                /* no root in F_l: gcd(G, x^l - x) = 1 */
                nmod_poly_t h, xp, t;
                nmod_poly_init(h, P.l);
                nmod_poly_init(xp, P.l);
                nmod_poly_init(t, P.l);
                for (i = 0; i <= n; i++)
                {
                    fq_nmod_poly_get_coeff(a, G, i, P.fqctx);
                    nmod_poly_set_coeff_ui(h, i, nmod_poly_get_coeff_ui(a, 0));
                }
                nmod_poly_set_coeff_ui(t, 1, 1);
                nmod_poly_powmod_ui_binexp(xp, t, P.l, h);
                nmod_poly_sub(xp, xp, t);
                nmod_poly_gcd(t, xp, h);
                if (nmod_poly_degree(t) == 0)
                    res = 1;
                nmod_poly_clear(h);
                nmod_poly_clear(xp);
                nmod_poly_clear(t);
            }

            fq_nmod_clear(a, P.fqctx);
            fq_nmod_clear(b, P.fqctx);
            fq_nmod_poly_clear(num, P.fqctx);
            fq_nmod_poly_clear(den, P.fqctx);
            fq_nmod_poly_clear(G, P.fqctx);
            _place_clear(&P, T->length, T);
        }
    }

    flint_rand_clear(state);
    for (i = 0; i <= n; i++)
        fmpz_mpoly_q_clear(c + i, F->mctx);
    flint_free(c);
    return res;
}
