pdf:
	pdflatex flint-logo-day-opaque
	pdflatex flint-logo-day-transparent
	pdflatex flint-logo-night-opaque
	pdflatex flint-logo-night-transparent
	rm *.aux
	rm *.log

svg:
	pdf2svg flint-logo-day-opaque.pdf flint-logo-day-opaque.svg
	pdf2svg flint-logo-day-transparent.pdf flint-logo-day-transparent.svg
	pdf2svg flint-logo-night-opaque.pdf flint-logo-night-opaque.svg
	pdf2svg flint-logo-night-transparent.pdf flint-logo-night-transparent.svg

