/*
    Copyright (C) 2024, 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/* This file is generated by dev/gen_mpn_dot_rev.py. Do not edit by hand. */

#include "longlong.h"
#include "mpn_extras.h"


static void _flint_mpn_dot_strided_1x1_1(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, B0;
    ulong p0;
    ulong c0_0;
    ulong r0;
    slong k;

    c0_0 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        B0 = b[0];

        p0 = A0 * B0;
        c0_0 += p0;

        a += astride;
        b += bstride;
    }

    r0 = c0_0;

    res[0] = r0;
}

static void _flint_mpn_dot_1x1_1(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, B0;
    ulong p0;
    ulong c0_0;
    ulong r0;
    nn_srcptr aend;

    c0_0 = 0;

    aend = a + len * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        B0 = b[0];

        p0 = A0 * B0;
        c0_0 += p0;

        a += 1;
        b += 1;
    }

    r0 = c0_0;

    res[0] = r0;
}

static void _flint_mpn_dot_rev_1x1_1(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, B0;
    ulong p0;
    ulong c0_0;
    ulong r0;
    nn_srcptr aend;

    c0_0 = 0;

    aend = a + len * 1;
    b += (len - 1) * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        B0 = b[0];

        p0 = A0 * B0;
        c0_0 += p0;

        a += 1;
        b -= 1;
    }

    r0 = c0_0;

    res[0] = r0;
}

static void _flint_mpn_dot_strided_1x1_2(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, B0;
    ulong p0, p1;
    ulong c0_0, c0_1;
    ulong r0, r1;
    slong k;

    c0_0 = c0_1 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_ssaaaa(c0_1, c0_0, c0_1, c0_0, p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;

    res[0] = r0;
    res[1] = r1;
}

static void _flint_mpn_dot_1x1_2(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, B0;
    ulong p0, p1;
    ulong c0_0, c0_1;
    ulong r0, r1;
    nn_srcptr aend;

    c0_0 = c0_1 = 0;

    aend = a + len * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_ssaaaa(c0_1, c0_0, c0_1, c0_0, p1, p0);

        a += 1;
        b += 1;
    }

    r0 = c0_0;
    r1 = c0_1;

    res[0] = r0;
    res[1] = r1;
}

static void _flint_mpn_dot_rev_1x1_2(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, B0;
    ulong p0, p1;
    ulong c0_0, c0_1;
    ulong r0, r1;
    nn_srcptr aend;

    c0_0 = c0_1 = 0;

    aend = a + len * 1;
    b += (len - 1) * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_ssaaaa(c0_1, c0_0, c0_1, c0_0, p1, p0);

        a += 1;
        b -= 1;
    }

    r0 = c0_0;
    r1 = c0_1;

    res[0] = r0;
    res[1] = r1;
}

static void _flint_mpn_dot_strided_1x1_3(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong r0, r1, r2;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_1x1_3(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong r0, r1, r2;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;

    aend = a + len * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);

        a += 1;
        b += 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_rev_1x1_3(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong r0, r1, r2;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;

    aend = a + len * 1;
    b += (len - 1) * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);

        a += 1;
        b -= 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_strided_2x1_2(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1;
    ulong r0, r1;
    slong k;

    c0_0 = c0_1 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_ssaaaa(c0_1, c0_0, c0_1, c0_0, p1, p0);
        p0 = A1 * B0;
        c0_1 += p0;

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;

    res[0] = r0;
    res[1] = r1;
}

static void _flint_mpn_dot_2x1_2(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1;
    ulong r0, r1;
    nn_srcptr aend;

    c0_0 = c0_1 = 0;

    aend = a + len * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_ssaaaa(c0_1, c0_0, c0_1, c0_0, p1, p0);
        p0 = A1 * B0;
        c0_1 += p0;

        a += 2;
        b += 1;
    }

    r0 = c0_0;
    r1 = c0_1;

    res[0] = r0;
    res[1] = r1;
}

static void _flint_mpn_dot_rev_2x1_2(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1;
    ulong r0, r1;
    nn_srcptr aend;

    c0_0 = c0_1 = 0;

    aend = a + len * 2;
    b += (len - 1) * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_ssaaaa(c0_1, c0_0, c0_1, c0_0, p1, p0);
        p0 = A1 * B0;
        c0_1 += p0;

        a += 2;
        b -= 1;
    }

    r0 = c0_0;
    r1 = c0_1;

    res[0] = r0;
    res[1] = r1;
}

static void _flint_mpn_dot_strided_2x1_3(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong r0, r1, r2;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_2x1_3(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong r0, r1, r2;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;

    aend = a + len * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);

        a += 2;
        b += 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_rev_2x1_3(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong r0, r1, r2;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;

    aend = a + len * 2;
    b += (len - 1) * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);

        a += 2;
        b -= 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_strided_2x1_4(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong r0, r1, r2, r3;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_2x1_4(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong r0, r1, r2, r3;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    aend = a + len * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);

        a += 2;
        b += 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_rev_2x1_4(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong r0, r1, r2, r3;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    aend = a + len * 2;
    b += (len - 1) * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);

        a += 2;
        b -= 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_strided_2x2_3(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong r0, r1, r2;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        p0 = A1 * B1;
        c0_2 += p0;

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_2x2_3(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong r0, r1, r2;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;

    aend = a + len * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        p0 = A1 * B1;
        c0_2 += p0;

        a += 2;
        b += 2;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_rev_2x2_3(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong r0, r1, r2;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;

    aend = a + len * 2;
    b += (len - 1) * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        p0 = A1 * B1;
        c0_2 += p0;

        a += 2;
        b -= 2;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_strided_2x2_4(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong r0, r1, r2, r3;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_ssaaaa(c1_2, c1_1, c1_2, c1_1, p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_2x2_4(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong r0, r1, r2, r3;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    aend = a + len * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_ssaaaa(c1_2, c1_1, c1_2, c1_1, p1, p0);

        a += 2;
        b += 2;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_rev_2x2_4(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong r0, r1, r2, r3;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    aend = a + len * 2;
    b += (len - 1) * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_ssaaaa(c1_2, c1_1, c1_2, c1_1, p1, p0);

        a += 2;
        b -= 2;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_strided_2x2_5(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong r0, r1, r2, r3, r4;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    add_ssssaaaaaaaa(r4, r3, r2, r1, r4, r3, r2, r1, UWORD(0), c1_2, c1_1, c1_0);
    add_sssaaaaaa(r4, r3, r2, r4, r3, r2, c2_2, c2_1, c2_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_2x2_5(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong r0, r1, r2, r3, r4;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;

    aend = a + len * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);

        a += 2;
        b += 2;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    add_ssssaaaaaaaa(r4, r3, r2, r1, r4, r3, r2, r1, UWORD(0), c1_2, c1_1, c1_0);
    add_sssaaaaaa(r4, r3, r2, r4, r3, r2, c2_2, c2_1, c2_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_rev_2x2_5(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong r0, r1, r2, r3, r4;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;

    aend = a + len * 2;
    b += (len - 1) * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);

        a += 2;
        b -= 2;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    add_ssssaaaaaaaa(r4, r3, r2, r1, r4, r3, r2, r1, UWORD(0), c1_2, c1_1, c1_0);
    add_sssaaaaaa(r4, r3, r2, r4, r3, r2, c2_2, c2_1, c2_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_strided_3x1_3(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong r0, r1, r2;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        p0 = A2 * B0;
        c0_2 += p0;

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_strided_3x1_4(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong r0, r1, r2, r3;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_ssaaaa(c1_2, c1_1, c1_2, c1_1, p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_strided_3x1_5(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong r0, r1, r2, r3, r4;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    add_ssssaaaaaaaa(r4, r3, r2, r1, r4, r3, r2, r1, UWORD(0), c1_2, c1_1, c1_0);
    add_sssaaaaaa(r4, r3, r2, r4, r3, r2, c2_2, c2_1, c2_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_strided_3x2_4(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong r0, r1, r2, r3;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        B1 = b[1];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_ssaaaa(c1_2, c1_1, c1_2, c1_1, p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_ssaaaa(c1_2, c1_1, c1_2, c1_1, p1, p0);
        p0 = A2 * B1;
        c1_2 += p0;

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_strided_3x2_5(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong r0, r1, r2, r3, r4;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        B1 = b[1];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B1);
        add_ssaaaa(c2_2, c2_1, c2_2, c2_1, p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    add_ssssaaaaaaaa(r4, r3, r2, r1, r4, r3, r2, r1, UWORD(0), c1_2, c1_1, c1_0);
    add_sssaaaaaa(r4, r3, r2, r4, r3, r2, c2_2, c2_1, c2_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_strided_3x2_6(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong c3_0, c3_1, c3_2;
    ulong r0, r1, r2, r3, r4, r5;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;
    c3_0 = c3_1 = c3_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        B1 = b[1];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B1);
        add_sssaaaaaa(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    r5 = UWORD(0);
    add_sssssaaaaaaaaaa(r5, r4, r3, r2, r1, r5, r4, r3, r2, r1, UWORD(0), UWORD(0), c1_2, c1_1, c1_0);
    add_ssssaaaaaaaa(r5, r4, r3, r2, r5, r4, r3, r2, UWORD(0), c2_2, c2_1, c2_0);
    add_sssaaaaaa(r5, r4, r3, r5, r4, r3, c3_2, c3_1, c3_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
}

static void _flint_mpn_dot_strided_3x3_5(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0, B1, B2;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong r0, r1, r2, r3, r4;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        B1 = b[1];
        B2 = b[2];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B2);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B2);
        add_ssaaaa(c2_2, c2_1, c2_2, c2_1, p1, p0);
        umul_ppmm(p1, p0, A2, B1);
        add_ssaaaa(c2_2, c2_1, c2_2, c2_1, p1, p0);
        p0 = A2 * B2;
        c2_2 += p0;

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    add_ssssaaaaaaaa(r4, r3, r2, r1, r4, r3, r2, r1, UWORD(0), c1_2, c1_1, c1_0);
    add_sssaaaaaa(r4, r3, r2, r4, r3, r2, c2_2, c2_1, c2_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_strided_3x3_6(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0, B1, B2;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong c3_0, c3_1, c3_2;
    ulong r0, r1, r2, r3, r4, r5;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;
    c3_0 = c3_1 = c3_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        B1 = b[1];
        B2 = b[2];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B2);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B2);
        add_sssaaaaaa(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B1);
        add_sssaaaaaa(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B2);
        add_ssaaaa(c3_2, c3_1, c3_2, c3_1, p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    r5 = UWORD(0);
    add_sssssaaaaaaaaaa(r5, r4, r3, r2, r1, r5, r4, r3, r2, r1, UWORD(0), UWORD(0), c1_2, c1_1, c1_0);
    add_ssssaaaaaaaa(r5, r4, r3, r2, r5, r4, r3, r2, UWORD(0), c2_2, c2_1, c2_0);
    add_sssaaaaaa(r5, r4, r3, r5, r4, r3, c3_2, c3_1, c3_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
}

static void _flint_mpn_dot_strided_3x3_7(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0, B1, B2;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong c3_0, c3_1, c3_2;
    ulong c4_0, c4_1, c4_2;
    ulong r0, r1, r2, r3, r4, r5, r6;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;
    c3_0 = c3_1 = c3_2 = 0;
    c4_0 = c4_1 = c4_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        B1 = b[1];
        B2 = b[2];

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B2);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B2);
        add_sssaaaaaa(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B2);
        add_sssaaaaaa(c4_2, c4_1, c4_0, c4_2, c4_1, c4_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B1);
        add_sssaaaaaa(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    r5 = UWORD(0);
    r6 = UWORD(0);
    add_ssssssaaaaaaaaaaaa(r6, r5, r4, r3, r2, r1, r6, r5, r4, r3, r2, r1, UWORD(0), UWORD(0), UWORD(0), c1_2, c1_1, c1_0);
    add_sssssaaaaaaaaaa(r6, r5, r4, r3, r2, r6, r5, r4, r3, r2, UWORD(0), UWORD(0), c2_2, c2_1, c2_0);
    add_ssssaaaaaaaa(r6, r5, r4, r3, r6, r5, r4, r3, UWORD(0), c3_2, c3_1, c3_0);
    add_sssaaaaaa(r6, r5, r4, r6, r5, r4, c4_2, c4_1, c4_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
    res[6] = r6;
}

static void _flint_mpn_dot_strided_4x1_4(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong r0, r1, r2, r3;
    ulong t[5];
    slong k;

    r0 = r1 = r2 = r3 = 0;

    for (k = 0; k < len; k++)
    {
        flint_mpn_mul(t, a, 4, b, 1);
        add_ssssaaaaaaaa(r3, r2, r1, r0, r3, r2, r1, r0, t[3], t[2], t[1], t[0]);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_strided_4x1_5(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong r0, r1, r2, r3, r4;
    ulong t[5];
    slong k;

    r0 = r1 = r2 = r3 = r4 = 0;

    for (k = 0; k < len; k++)
    {
        flint_mpn_mul(t, a, 4, b, 1);
        add_sssssaaaaaaaaaa(r4, r3, r2, r1, r0, r4, r3, r2, r1, r0, t[4], t[3], t[2], t[1], t[0]);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_strided_4x1_6(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong r0, r1, r2, r3, r4, r5;
    ulong t[5];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = 0;

    for (k = 0; k < len; k++)
    {
        flint_mpn_mul(t, a, 4, b, 1);
        add_ssssssaaaaaaaaaaaa(r5, r4, r3, r2, r1, r0, r5, r4, r3, r2, r1, r0, UWORD(0), t[4], t[3], t[2], t[1], t[0]);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
}

static void _flint_mpn_dot_strided_4x2_5(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong r0, r1, r2, r3, r4;
    ulong t[6];
    slong k;

    r0 = r1 = r2 = r3 = r4 = 0;

    for (k = 0; k < len; k++)
    {
        flint_mpn_mul(t, a, 4, b, 2);
        add_sssssaaaaaaaaaa(r4, r3, r2, r1, r0, r4, r3, r2, r1, r0, t[4], t[3], t[2], t[1], t[0]);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_strided_4x2_6(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong r0, r1, r2, r3, r4, r5;
    ulong t[6];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = 0;

    for (k = 0; k < len; k++)
    {
        flint_mpn_mul(t, a, 4, b, 2);
        add_ssssssaaaaaaaaaaaa(r5, r4, r3, r2, r1, r0, r5, r4, r3, r2, r1, r0, t[5], t[4], t[3], t[2], t[1], t[0]);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
}

static void _flint_mpn_dot_strided_4x2_7(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong r0, r1, r2, r3, r4, r5, r6;
    ulong t[6];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = r6 = 0;

    for (k = 0; k < len; k++)
    {
        flint_mpn_mul(t, a, 4, b, 2);
        add_sssssssaaaaaaaaaaaaaa(r6, r5, r4, r3, r2, r1, r0, r6, r5, r4, r3, r2, r1, r0, UWORD(0), t[5], t[4], t[3], t[2], t[1], t[0]);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
    res[6] = r6;
}

static void _flint_mpn_dot_strided_4x3_6(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong r0, r1, r2, r3, r4, r5;
    ulong t[7];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = 0;

    for (k = 0; k < len; k++)
    {
        flint_mpn_mul(t, a, 4, b, 3);
        add_ssssssaaaaaaaaaaaa(r5, r4, r3, r2, r1, r0, r5, r4, r3, r2, r1, r0, t[5], t[4], t[3], t[2], t[1], t[0]);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
}

static void _flint_mpn_dot_strided_4x3_7(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong r0, r1, r2, r3, r4, r5, r6;
    ulong t[7];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = r6 = 0;

    for (k = 0; k < len; k++)
    {
        flint_mpn_mul(t, a, 4, b, 3);
        add_sssssssaaaaaaaaaaaaaa(r6, r5, r4, r3, r2, r1, r0, r6, r5, r4, r3, r2, r1, r0, t[6], t[5], t[4], t[3], t[2], t[1], t[0]);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
    res[6] = r6;
}

static void _flint_mpn_dot_strided_4x3_8(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong r0, r1, r2, r3, r4, r5, r6, r7;
    ulong t[7];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = r6 = r7 = 0;

    for (k = 0; k < len; k++)
    {
        flint_mpn_mul(t, a, 4, b, 3);
        add_ssssssssaaaaaaaaaaaaaaaa(r7, r6, r5, r4, r3, r2, r1, r0, r7, r6, r5, r4, r3, r2, r1, r0, UWORD(0), t[6], t[5], t[4], t[3], t[2], t[1], t[0]);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
    res[6] = r6;
    res[7] = r7;
}

static void _flint_mpn_dot_strided_4x4_7(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong r0, r1, r2, r3, r4, r5, r6;
    ulong t[8];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = r6 = 0;

    for (k = 0; k < len; k++)
    {
        flint_mpn_mul_n(t, a, b, 4);
        add_sssssssaaaaaaaaaaaaaa(r6, r5, r4, r3, r2, r1, r0, r6, r5, r4, r3, r2, r1, r0, t[6], t[5], t[4], t[3], t[2], t[1], t[0]);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
    res[6] = r6;
}

static void _flint_mpn_dot_strided_4x4_8(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong r0, r1, r2, r3, r4, r5, r6, r7;
    ulong t[8];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = r6 = r7 = 0;

    for (k = 0; k < len; k++)
    {
        flint_mpn_mul_n(t, a, b, 4);
        add_ssssssssaaaaaaaaaaaaaaaa(r7, r6, r5, r4, r3, r2, r1, r0, r7, r6, r5, r4, r3, r2, r1, r0, t[7], t[6], t[5], t[4], t[3], t[2], t[1], t[0]);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
    res[6] = r6;
    res[7] = r7;
}

static void _flint_mpn_dot_strided_1x1_1_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, B0;
    ulong p0;
    ulong c0_0;
    ulong r0;
    slong k;

    c0_0 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        B0 = b[0];

        p0 = A0 * B0;
        c0_0 += p0;

        a += astride;
        b += bstride;
    }

    r0 = c0_0;

    res[0] = r0;
}

static void _flint_mpn_dot_1x1_1_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, B0;
    ulong p0;
    ulong c0_0;
    ulong r0;
    nn_srcptr aend;

    c0_0 = 0;

    aend = a + len * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        B0 = b[0];

        p0 = A0 * B0;
        c0_0 += p0;

        a += 1;
        b += 1;
    }

    r0 = c0_0;

    res[0] = r0;
}

static void _flint_mpn_dot_rev_1x1_1_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, B0;
    ulong p0;
    ulong c0_0;
    ulong r0;
    nn_srcptr aend;

    c0_0 = 0;

    aend = a + len * 1;
    b += (len - 1) * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        B0 = b[0];

        p0 = A0 * B0;
        c0_0 += p0;

        a += 1;
        b -= 1;
    }

    r0 = c0_0;

    res[0] = r0;
}

static void _flint_mpn_dot_strided_1x1_2_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, B0;
    ulong p0, p1;
    ulong c0_0, c0_1;
    ulong r0, r1;
    slong k;

    c0_0 = c0_1 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        B0 = b[0];

        smul_ppmm(p1, p0, A0, B0);
        add_ssaaaa(c0_1, c0_0, c0_1, c0_0, p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;

    res[0] = r0;
    res[1] = r1;
}

static void _flint_mpn_dot_1x1_2_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, B0;
    ulong p0, p1;
    ulong c0_0, c0_1;
    ulong r0, r1;
    nn_srcptr aend;

    c0_0 = c0_1 = 0;

    aend = a + len * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        B0 = b[0];

        smul_ppmm(p1, p0, A0, B0);
        add_ssaaaa(c0_1, c0_0, c0_1, c0_0, p1, p0);

        a += 1;
        b += 1;
    }

    r0 = c0_0;
    r1 = c0_1;

    res[0] = r0;
    res[1] = r1;
}

static void _flint_mpn_dot_rev_1x1_2_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, B0;
    ulong p0, p1;
    ulong c0_0, c0_1;
    ulong r0, r1;
    nn_srcptr aend;

    c0_0 = c0_1 = 0;

    aend = a + len * 1;
    b += (len - 1) * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        B0 = b[0];

        smul_ppmm(p1, p0, A0, B0);
        add_ssaaaa(c0_1, c0_0, c0_1, c0_0, p1, p0);

        a += 1;
        b -= 1;
    }

    r0 = c0_0;
    r1 = c0_1;

    res[0] = r0;
    res[1] = r1;
}

static void _flint_mpn_dot_strided_1x1_3_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong sx;
    ulong r0, r1, r2;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        B0 = b[0];

        smul_ppmm(p1, p0, A0, B0);
        sx = FLINT_SIGN_EXT(p1);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, sx, p1, p0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_1x1_3_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong sx;
    ulong r0, r1, r2;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;

    aend = a + len * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        B0 = b[0];

        smul_ppmm(p1, p0, A0, B0);
        sx = FLINT_SIGN_EXT(p1);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, sx, p1, p0);

        a += 1;
        b += 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_rev_1x1_3_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong sx;
    ulong r0, r1, r2;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;

    aend = a + len * 1;
    b += (len - 1) * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        B0 = b[0];

        smul_ppmm(p1, p0, A0, B0);
        sx = FLINT_SIGN_EXT(p1);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, sx, p1, p0);

        a += 1;
        b -= 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_strided_2x1_2_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1;
    ulong cb0;
    ulong mb;
    ulong r0, r1;
    slong k;

    c0_0 = c0_1 = 0;
    cb0 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        mb = FLINT_SIGN_EXT(B0);

        umul_ppmm(p1, p0, A0, B0);
        add_ssaaaa(c0_1, c0_0, c0_1, c0_0, p1, p0);
        p0 = A1 * B0;
        c0_1 += p0;
        cb0 += (mb & A0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r1 -= cb0;

    res[0] = r0;
    res[1] = r1;
}

static void _flint_mpn_dot_2x1_2_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1;
    ulong cb0;
    ulong mb;
    ulong r0, r1;
    nn_srcptr aend;

    c0_0 = c0_1 = 0;
    cb0 = 0;

    aend = a + len * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        mb = FLINT_SIGN_EXT(B0);

        umul_ppmm(p1, p0, A0, B0);
        add_ssaaaa(c0_1, c0_0, c0_1, c0_0, p1, p0);
        p0 = A1 * B0;
        c0_1 += p0;
        cb0 += (mb & A0);

        a += 2;
        b += 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r1 -= cb0;

    res[0] = r0;
    res[1] = r1;
}

static void _flint_mpn_dot_rev_2x1_2_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1;
    ulong cb0;
    ulong mb;
    ulong r0, r1;
    nn_srcptr aend;

    c0_0 = c0_1 = 0;
    cb0 = 0;

    aend = a + len * 2;
    b += (len - 1) * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        mb = FLINT_SIGN_EXT(B0);

        umul_ppmm(p1, p0, A0, B0);
        add_ssaaaa(c0_1, c0_0, c0_1, c0_0, p1, p0);
        p0 = A1 * B0;
        c0_1 += p0;
        cb0 += (mb & A0);

        a += 2;
        b -= 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r1 -= cb0;

    res[0] = r0;
    res[1] = r1;
}

static void _flint_mpn_dot_strided_2x1_3_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong mb;
    ulong r0, r1, r2;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        mb = FLINT_SIGN_EXT(B0);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        sub_ddmmss(c0_2, c0_1, c0_2, c0_1, UWORD(0), (mb & A0));

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_2x1_3_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong mb;
    ulong r0, r1, r2;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;

    aend = a + len * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        mb = FLINT_SIGN_EXT(B0);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        sub_ddmmss(c0_2, c0_1, c0_2, c0_1, UWORD(0), (mb & A0));

        a += 2;
        b += 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_rev_2x1_3_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong mb;
    ulong r0, r1, r2;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;

    aend = a + len * 2;
    b += (len - 1) * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        mb = FLINT_SIGN_EXT(B0);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        sub_ddmmss(c0_2, c0_1, c0_2, c0_1, UWORD(0), (mb & A0));

        a += 2;
        b -= 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_strided_2x1_4_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong mb;
    ulong sx;
    ulong r0, r1, r2, r3;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        mb = FLINT_SIGN_EXT(B0);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A1, B0);
        sx = FLINT_SIGN_EXT(p1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, sx, p1, p0);
        sub_dddmmmsss(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), UWORD(0), (mb & A0));

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_2x1_4_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong mb;
    ulong sx;
    ulong r0, r1, r2, r3;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    aend = a + len * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        mb = FLINT_SIGN_EXT(B0);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A1, B0);
        sx = FLINT_SIGN_EXT(p1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, sx, p1, p0);
        sub_dddmmmsss(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), UWORD(0), (mb & A0));

        a += 2;
        b += 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_rev_2x1_4_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong mb;
    ulong sx;
    ulong r0, r1, r2, r3;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    aend = a + len * 2;
    b += (len - 1) * 1;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        mb = FLINT_SIGN_EXT(B0);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A1, B0);
        sx = FLINT_SIGN_EXT(p1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, sx, p1, p0);
        sub_dddmmmsss(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), UWORD(0), (mb & A0));

        a += 2;
        b -= 1;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_strided_2x2_3_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong ca0;
    ulong cb0;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    ca0 = 0;
    cb0 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A1);
        mb = FLINT_SIGN_EXT(B1);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        p0 = A1 * B1;
        c0_2 += p0;
        ca0 += (ma & B0);
        cb0 += (mb & A0);

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r2 -= ca0;
    r2 -= cb0;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_2x2_3_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong ca0;
    ulong cb0;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    ca0 = 0;
    cb0 = 0;

    aend = a + len * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A1);
        mb = FLINT_SIGN_EXT(B1);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        p0 = A1 * B1;
        c0_2 += p0;
        ca0 += (ma & B0);
        cb0 += (mb & A0);

        a += 2;
        b += 2;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r2 -= ca0;
    r2 -= cb0;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_rev_2x2_3_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong ca0;
    ulong cb0;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    ca0 = 0;
    cb0 = 0;

    aend = a + len * 2;
    b += (len - 1) * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A1);
        mb = FLINT_SIGN_EXT(B1);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        p0 = A1 * B1;
        c0_2 += p0;
        ca0 += (ma & B0);
        cb0 += (mb & A0);

        a += 2;
        b -= 2;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r2 -= ca0;
    r2 -= cb0;

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_strided_2x2_4_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A1);
        mb = FLINT_SIGN_EXT(B1);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A1, B1);
        add_ssaaaa(c1_2, c1_1, c1_2, c1_1, p1, p0);
        sub_ddmmss(c1_2, c1_1, c1_2, c1_1, UWORD(0), (ma & B0));
        sub_ddmmss(c1_2, c1_1, c1_2, c1_1, UWORD(0), (mb & A0));

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_2x2_4_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    aend = a + len * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A1);
        mb = FLINT_SIGN_EXT(B1);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A1, B1);
        add_ssaaaa(c1_2, c1_1, c1_2, c1_1, p1, p0);
        sub_ddmmss(c1_2, c1_1, c1_2, c1_1, UWORD(0), (ma & B0));
        sub_ddmmss(c1_2, c1_1, c1_2, c1_1, UWORD(0), (mb & A0));

        a += 2;
        b += 2;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_rev_2x2_4_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    aend = a + len * 2;
    b += (len - 1) * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A1);
        mb = FLINT_SIGN_EXT(B1);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A1, B1);
        add_ssaaaa(c1_2, c1_1, c1_2, c1_1, p1, p0);
        sub_ddmmss(c1_2, c1_1, c1_2, c1_1, UWORD(0), (ma & B0));
        sub_ddmmss(c1_2, c1_1, c1_2, c1_1, UWORD(0), (mb & A0));

        a += 2;
        b -= 2;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_strided_2x2_5_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong ma;
    ulong mb;
    ulong sx;
    ulong r0, r1, r2, r3, r4;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A1);
        mb = FLINT_SIGN_EXT(B1);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A1, B1);
        sx = FLINT_SIGN_EXT(p1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, sx, p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        sub_dddmmmsss(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), UWORD(0), (ma & B0));
        sub_dddmmmsss(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), UWORD(0), (mb & A0));

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    add_ssssaaaaaaaa(r4, r3, r2, r1, r4, r3, r2, r1, UWORD(0), c1_2, c1_1, c1_0);
    add_sssaaaaaa(r4, r3, r2, r4, r3, r2, c2_2, c2_1, c2_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_2x2_5_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong ma;
    ulong mb;
    ulong sx;
    ulong r0, r1, r2, r3, r4;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;

    aend = a + len * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A1);
        mb = FLINT_SIGN_EXT(B1);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A1, B1);
        sx = FLINT_SIGN_EXT(p1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, sx, p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        sub_dddmmmsss(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), UWORD(0), (ma & B0));
        sub_dddmmmsss(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), UWORD(0), (mb & A0));

        a += 2;
        b += 2;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    add_ssssaaaaaaaa(r4, r3, r2, r1, r4, r3, r2, r1, UWORD(0), c1_2, c1_1, c1_0);
    add_sssaaaaaa(r4, r3, r2, r4, r3, r2, c2_2, c2_1, c2_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_rev_2x2_5_signed(nn_ptr res, nn_srcptr a, nn_srcptr b, slong len)
{
    ulong A0, A1, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong ma;
    ulong mb;
    ulong sx;
    ulong r0, r1, r2, r3, r4;
    nn_srcptr aend;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;

    aend = a + len * 2;
    b += (len - 1) * 2;

    for ( ; a != aend; )
    {
        A0 = a[0];
        A1 = a[1];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A1);
        mb = FLINT_SIGN_EXT(B1);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A1, B1);
        sx = FLINT_SIGN_EXT(p1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, sx, p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        sub_dddmmmsss(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), UWORD(0), (ma & B0));
        sub_dddmmmsss(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), UWORD(0), (mb & A0));

        a += 2;
        b -= 2;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    add_ssssaaaaaaaa(r4, r3, r2, r1, r4, r3, r2, r1, UWORD(0), c1_2, c1_1, c1_0);
    add_sssaaaaaa(r4, r3, r2, r4, r3, r2, c2_2, c2_1, c2_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_strided_3x1_3_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong cb0, cb1;
    ulong mb;
    ulong r0, r1, r2;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    cb0 = cb1 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        mb = FLINT_SIGN_EXT(B0);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_ssaaaa(c0_2, c0_1, c0_2, c0_1, p1, p0);
        p0 = A2 * B0;
        c0_2 += p0;
        add_ssaaaa(cb1, cb0, cb1, cb0, (mb & A1), (mb & A0));

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    sub_ddmmss(r2, r1, r2, r1, cb1, cb0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
}

static void _flint_mpn_dot_strided_3x1_4_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong mb;
    ulong r0, r1, r2, r3;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        mb = FLINT_SIGN_EXT(B0);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A2, B0);
        add_ssaaaa(c1_2, c1_1, c1_2, c1_1, p1, p0);
        sub_dddmmmsss(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), UWORD(0), (mb & A0));
        sub_ddmmss(c1_2, c1_1, c1_2, c1_1, UWORD(0), (mb & A1));

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_strided_3x1_5_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong mb;
    ulong sx;
    ulong r0, r1, r2, r3, r4;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        mb = FLINT_SIGN_EXT(B0);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A2, B0);
        sx = FLINT_SIGN_EXT(p1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, sx, p1, p0);
        sub_dddmmmsss(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), UWORD(0), (mb & A0));
        sub_dddmmmsss(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), UWORD(0), (mb & A1));

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    sx = FLINT_SIGN_EXT(c1_2);
    add_ssssaaaaaaaa(r4, r3, r2, r1, r4, r3, r2, r1, sx, c1_2, c1_1, c1_0);
    add_sssaaaaaa(r4, r3, r2, r4, r3, r2, c2_2, c2_1, c2_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_strided_3x2_4_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong ca0;
    ulong cb0, cb1;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    ca0 = 0;
    cb0 = cb1 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A2);
        mb = FLINT_SIGN_EXT(B1);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_ssaaaa(c1_2, c1_1, c1_2, c1_1, p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_ssaaaa(c1_2, c1_1, c1_2, c1_1, p1, p0);
        p0 = A2 * B1;
        c1_2 += p0;
        ca0 += (ma & B0);
        add_ssaaaa(cb1, cb0, cb1, cb0, (mb & A1), (mb & A0));

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    add_sssaaaaaa(r3, r2, r1, r3, r2, r1, c1_2, c1_1, c1_0);
    r3 -= ca0;
    sub_ddmmss(r3, r2, r3, r2, cb1, cb0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_strided_3x2_5_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3, r4;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A2);
        mb = FLINT_SIGN_EXT(B1);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A2, B1);
        add_ssaaaa(c2_2, c2_1, c2_2, c2_1, p1, p0);
        sub_ddmmss(c2_2, c2_1, c2_2, c2_1, UWORD(0), (ma & B0));
        sub_dddmmmsss(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), UWORD(0), (mb & A0));
        sub_ddmmss(c2_2, c2_1, c2_2, c2_1, UWORD(0), (mb & A1));

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    add_ssssaaaaaaaa(r4, r3, r2, r1, r4, r3, r2, r1, UWORD(0), c1_2, c1_1, c1_0);
    add_sssaaaaaa(r4, r3, r2, r4, r3, r2, c2_2, c2_1, c2_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_strided_3x2_6_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0, B1;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong c3_0, c3_1, c3_2;
    ulong ma;
    ulong mb;
    ulong sx;
    ulong r0, r1, r2, r3, r4, r5;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;
    c3_0 = c3_1 = c3_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A2);
        mb = FLINT_SIGN_EXT(B1);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A2, B1);
        sx = FLINT_SIGN_EXT(p1);
        add_sssaaaaaa(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, sx, p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        sub_dddmmmsss(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), UWORD(0), (ma & B0));
        sub_dddmmmsss(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), UWORD(0), (mb & A0));
        sub_dddmmmsss(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), UWORD(0), (mb & A1));

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    r5 = UWORD(0);
    add_sssssaaaaaaaaaa(r5, r4, r3, r2, r1, r5, r4, r3, r2, r1, UWORD(0), UWORD(0), c1_2, c1_1, c1_0);
    sx = FLINT_SIGN_EXT(c2_2);
    add_ssssaaaaaaaa(r5, r4, r3, r2, r5, r4, r3, r2, sx, c2_2, c2_1, c2_0);
    add_sssaaaaaa(r5, r4, r3, r5, r4, r3, c3_2, c3_1, c3_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
}

static void _flint_mpn_dot_strided_3x3_5_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0, B1, B2;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong ca0, ca1;
    ulong cb0, cb1;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3, r4;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;
    ca0 = ca1 = 0;
    cb0 = cb1 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        B1 = b[1];
        B2 = b[2];
        ma = FLINT_SIGN_EXT(A2);
        mb = FLINT_SIGN_EXT(B2);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B2);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B2);
        add_ssaaaa(c2_2, c2_1, c2_2, c2_1, p1, p0);
        umul_ppmm(p1, p0, A2, B1);
        add_ssaaaa(c2_2, c2_1, c2_2, c2_1, p1, p0);
        p0 = A2 * B2;
        c2_2 += p0;
        add_ssaaaa(ca1, ca0, ca1, ca0, (ma & B1), (ma & B0));
        add_ssaaaa(cb1, cb0, cb1, cb0, (mb & A1), (mb & A0));

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    add_ssssaaaaaaaa(r4, r3, r2, r1, r4, r3, r2, r1, UWORD(0), c1_2, c1_1, c1_0);
    add_sssaaaaaa(r4, r3, r2, r4, r3, r2, c2_2, c2_1, c2_0);
    sub_ddmmss(r4, r3, r4, r3, ca1, ca0);
    sub_ddmmss(r4, r3, r4, r3, cb1, cb0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_strided_3x3_6_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0, B1, B2;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong c3_0, c3_1, c3_2;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3, r4, r5;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;
    c3_0 = c3_1 = c3_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        B1 = b[1];
        B2 = b[2];
        ma = FLINT_SIGN_EXT(A2);
        mb = FLINT_SIGN_EXT(B2);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B2);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B2);
        add_sssaaaaaa(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B1);
        add_sssaaaaaa(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A2, B2);
        add_ssaaaa(c3_2, c3_1, c3_2, c3_1, p1, p0);
        sub_dddmmmsss(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), UWORD(0), (ma & B0));
        sub_ddmmss(c3_2, c3_1, c3_2, c3_1, UWORD(0), (ma & B1));
        sub_dddmmmsss(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), UWORD(0), (mb & A0));
        sub_ddmmss(c3_2, c3_1, c3_2, c3_1, UWORD(0), (mb & A1));

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    r5 = UWORD(0);
    add_sssssaaaaaaaaaa(r5, r4, r3, r2, r1, r5, r4, r3, r2, r1, UWORD(0), UWORD(0), c1_2, c1_1, c1_0);
    add_ssssaaaaaaaa(r5, r4, r3, r2, r5, r4, r3, r2, UWORD(0), c2_2, c2_1, c2_0);
    add_sssaaaaaa(r5, r4, r3, r5, r4, r3, c3_2, c3_1, c3_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
}

static void _flint_mpn_dot_strided_3x3_7_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0, B1, B2;
    ulong p0, p1;
    ulong c0_0, c0_1, c0_2;
    ulong c1_0, c1_1, c1_2;
    ulong c2_0, c2_1, c2_2;
    ulong c3_0, c3_1, c3_2;
    ulong c4_0, c4_1, c4_2;
    ulong ma;
    ulong mb;
    ulong sx;
    ulong r0, r1, r2, r3, r4, r5, r6;
    slong k;

    c0_0 = c0_1 = c0_2 = 0;
    c1_0 = c1_1 = c1_2 = 0;
    c2_0 = c2_1 = c2_2 = 0;
    c3_0 = c3_1 = c3_2 = 0;
    c4_0 = c4_1 = c4_2 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        B1 = b[1];
        B2 = b[2];
        ma = FLINT_SIGN_EXT(A2);
        mb = FLINT_SIGN_EXT(B2);

        umul_ppmm(p1, p0, A0, B0);
        add_sssaaaaaa(c0_2, c0_1, c0_0, c0_2, c0_1, c0_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B1);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A0, B2);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B2);
        add_sssaaaaaa(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), p1, p0);
        smul_ppmm(p1, p0, A2, B2);
        sx = FLINT_SIGN_EXT(p1);
        add_sssaaaaaa(c4_2, c4_1, c4_0, c4_2, c4_1, c4_0, sx, p1, p0);
        umul_ppmm(p1, p0, A1, B0);
        add_sssaaaaaa(c1_2, c1_1, c1_0, c1_2, c1_1, c1_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A1, B1);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B1);
        add_sssaaaaaa(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), p1, p0);
        umul_ppmm(p1, p0, A2, B0);
        add_sssaaaaaa(c2_2, c2_1, c2_0, c2_2, c2_1, c2_0, UWORD(0), p1, p0);
        sub_dddmmmsss(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), UWORD(0), (ma & B0));
        sub_dddmmmsss(c4_2, c4_1, c4_0, c4_2, c4_1, c4_0, UWORD(0), UWORD(0), (ma & B1));
        sub_dddmmmsss(c3_2, c3_1, c3_0, c3_2, c3_1, c3_0, UWORD(0), UWORD(0), (mb & A0));
        sub_dddmmmsss(c4_2, c4_1, c4_0, c4_2, c4_1, c4_0, UWORD(0), UWORD(0), (mb & A1));

        a += astride;
        b += bstride;
    }

    r0 = c0_0;
    r1 = c0_1;
    r2 = c0_2;
    r3 = UWORD(0);
    r4 = UWORD(0);
    r5 = UWORD(0);
    r6 = UWORD(0);
    add_ssssssaaaaaaaaaaaa(r6, r5, r4, r3, r2, r1, r6, r5, r4, r3, r2, r1, UWORD(0), UWORD(0), UWORD(0), c1_2, c1_1, c1_0);
    add_sssssaaaaaaaaaa(r6, r5, r4, r3, r2, r6, r5, r4, r3, r2, UWORD(0), UWORD(0), c2_2, c2_1, c2_0);
    sx = FLINT_SIGN_EXT(c3_2);
    add_ssssaaaaaaaa(r6, r5, r4, r3, r6, r5, r4, r3, sx, c3_2, c3_1, c3_0);
    add_sssaaaaaa(r6, r5, r4, r6, r5, r4, c4_2, c4_1, c4_0);

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
    res[6] = r6;
}

static void _flint_mpn_dot_strided_4x1_4_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, B0;
    ulong mb;
    ulong r0, r1, r2, r3;
    ulong t[5];
    slong k;

    r0 = r1 = r2 = r3 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        B0 = b[0];
        mb = FLINT_SIGN_EXT(B0);

        flint_mpn_mul(t, a, 4, b, 1);
        add_ssssaaaaaaaa(r3, r2, r1, r0, r3, r2, r1, r0, t[3], t[2], t[1], t[0]);
        sub_dddmmmsss(r3, r2, r1, r3, r2, r1, (mb & A2), (mb & A1), (mb & A0));

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
}

static void _flint_mpn_dot_strided_4x1_5_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, A3, B0;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3, r4;
    ulong t[5];
    slong k;

    r0 = r1 = r2 = r3 = r4 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        A3 = a[3];
        B0 = b[0];
        ma = FLINT_SIGN_EXT(A3);
        mb = FLINT_SIGN_EXT(B0);

        flint_mpn_mul(t, a, 4, b, 1);
        add_sssssaaaaaaaaaa(r4, r3, r2, r1, r0, r4, r3, r2, r1, r0, t[4], t[3], t[2], t[1], t[0]);
        r4 -= (ma & B0);
        sub_ddddmmmmssss(r4, r3, r2, r1, r4, r3, r2, r1, (mb & A3), (mb & A2), (mb & A1), (mb & A0));

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_strided_4x1_6_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, A3, B0;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3, r4, r5;
    ulong t[5];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        A3 = a[3];
        B0 = b[0];
        ma = FLINT_SIGN_EXT(A3);
        mb = FLINT_SIGN_EXT(B0);

        flint_mpn_mul(t, a, 4, b, 1);
        add_ssssssaaaaaaaaaaaa(r5, r4, r3, r2, r1, r0, r5, r4, r3, r2, r1, r0, UWORD(0), t[4], t[3], t[2], t[1], t[0]);
        sub_ddmmss(r5, r4, r5, r4, UWORD(0), (ma & B0));
        sub_dddddmmmmmsssss(r5, r4, r3, r2, r1, r5, r4, r3, r2, r1, UWORD(0), (mb & A3), (mb & A2), (mb & A1), (mb & A0));
        r5 -= (ma & mb);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
}

static void _flint_mpn_dot_strided_4x2_5_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, A3, B0, B1;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3, r4;
    ulong t[6];
    slong k;

    r0 = r1 = r2 = r3 = r4 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        A3 = a[3];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A3);
        mb = FLINT_SIGN_EXT(B1);

        flint_mpn_mul(t, a, 4, b, 2);
        add_sssssaaaaaaaaaa(r4, r3, r2, r1, r0, r4, r3, r2, r1, r0, t[4], t[3], t[2], t[1], t[0]);
        r4 -= (ma & B0);
        sub_dddmmmsss(r4, r3, r2, r4, r3, r2, (mb & A2), (mb & A1), (mb & A0));

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
}

static void _flint_mpn_dot_strided_4x2_6_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, A3, B0, B1;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3, r4, r5;
    ulong t[6];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        A3 = a[3];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A3);
        mb = FLINT_SIGN_EXT(B1);

        flint_mpn_mul(t, a, 4, b, 2);
        add_ssssssaaaaaaaaaaaa(r5, r4, r3, r2, r1, r0, r5, r4, r3, r2, r1, r0, t[5], t[4], t[3], t[2], t[1], t[0]);
        sub_ddmmss(r5, r4, r5, r4, (ma & B1), (ma & B0));
        sub_ddddmmmmssss(r5, r4, r3, r2, r5, r4, r3, r2, (mb & A3), (mb & A2), (mb & A1), (mb & A0));

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
}

static void _flint_mpn_dot_strided_4x2_7_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, A3, B0, B1;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3, r4, r5, r6;
    ulong t[6];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = r6 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        A3 = a[3];
        B0 = b[0];
        B1 = b[1];
        ma = FLINT_SIGN_EXT(A3);
        mb = FLINT_SIGN_EXT(B1);

        flint_mpn_mul(t, a, 4, b, 2);
        add_sssssssaaaaaaaaaaaaaa(r6, r5, r4, r3, r2, r1, r0, r6, r5, r4, r3, r2, r1, r0, UWORD(0), t[5], t[4], t[3], t[2], t[1], t[0]);
        sub_dddmmmsss(r6, r5, r4, r6, r5, r4, UWORD(0), (ma & B1), (ma & B0));
        sub_dddddmmmmmsssss(r6, r5, r4, r3, r2, r6, r5, r4, r3, r2, UWORD(0), (mb & A3), (mb & A2), (mb & A1), (mb & A0));
        r6 -= (ma & mb);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
    res[6] = r6;
}

static void _flint_mpn_dot_strided_4x3_6_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, A3, B0, B1, B2;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3, r4, r5;
    ulong t[7];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        A3 = a[3];
        B0 = b[0];
        B1 = b[1];
        B2 = b[2];
        ma = FLINT_SIGN_EXT(A3);
        mb = FLINT_SIGN_EXT(B2);

        flint_mpn_mul(t, a, 4, b, 3);
        add_ssssssaaaaaaaaaaaa(r5, r4, r3, r2, r1, r0, r5, r4, r3, r2, r1, r0, t[5], t[4], t[3], t[2], t[1], t[0]);
        sub_ddmmss(r5, r4, r5, r4, (ma & B1), (ma & B0));
        sub_dddmmmsss(r5, r4, r3, r5, r4, r3, (mb & A2), (mb & A1), (mb & A0));

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
}

static void _flint_mpn_dot_strided_4x3_7_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, A3, B0, B1, B2;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3, r4, r5, r6;
    ulong t[7];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = r6 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        A3 = a[3];
        B0 = b[0];
        B1 = b[1];
        B2 = b[2];
        ma = FLINT_SIGN_EXT(A3);
        mb = FLINT_SIGN_EXT(B2);

        flint_mpn_mul(t, a, 4, b, 3);
        add_sssssssaaaaaaaaaaaaaa(r6, r5, r4, r3, r2, r1, r0, r6, r5, r4, r3, r2, r1, r0, t[6], t[5], t[4], t[3], t[2], t[1], t[0]);
        sub_dddmmmsss(r6, r5, r4, r6, r5, r4, (ma & B2), (ma & B1), (ma & B0));
        sub_ddddmmmmssss(r6, r5, r4, r3, r6, r5, r4, r3, (mb & A3), (mb & A2), (mb & A1), (mb & A0));

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
    res[6] = r6;
}

static void _flint_mpn_dot_strided_4x3_8_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, A3, B0, B1, B2;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3, r4, r5, r6, r7;
    ulong t[7];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = r6 = r7 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        A3 = a[3];
        B0 = b[0];
        B1 = b[1];
        B2 = b[2];
        ma = FLINT_SIGN_EXT(A3);
        mb = FLINT_SIGN_EXT(B2);

        flint_mpn_mul(t, a, 4, b, 3);
        add_ssssssssaaaaaaaaaaaaaaaa(r7, r6, r5, r4, r3, r2, r1, r0, r7, r6, r5, r4, r3, r2, r1, r0, UWORD(0), t[6], t[5], t[4], t[3], t[2], t[1], t[0]);
        sub_ddddmmmmssss(r7, r6, r5, r4, r7, r6, r5, r4, UWORD(0), (ma & B2), (ma & B1), (ma & B0));
        sub_dddddmmmmmsssss(r7, r6, r5, r4, r3, r7, r6, r5, r4, r3, UWORD(0), (mb & A3), (mb & A2), (mb & A1), (mb & A0));
        r7 -= (ma & mb);

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
    res[6] = r6;
    res[7] = r7;
}

static void _flint_mpn_dot_strided_4x4_7_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, A3, B0, B1, B2, B3;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3, r4, r5, r6;
    ulong t[8];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = r6 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        A3 = a[3];
        B0 = b[0];
        B1 = b[1];
        B2 = b[2];
        B3 = b[3];
        ma = FLINT_SIGN_EXT(A3);
        mb = FLINT_SIGN_EXT(B3);

        flint_mpn_mul_n(t, a, b, 4);
        add_sssssssaaaaaaaaaaaaaa(r6, r5, r4, r3, r2, r1, r0, r6, r5, r4, r3, r2, r1, r0, t[6], t[5], t[4], t[3], t[2], t[1], t[0]);
        sub_dddmmmsss(r6, r5, r4, r6, r5, r4, (ma & B2), (ma & B1), (ma & B0));
        sub_dddmmmsss(r6, r5, r4, r6, r5, r4, (mb & A2), (mb & A1), (mb & A0));

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
    res[6] = r6;
}

static void _flint_mpn_dot_strided_4x4_8_signed(nn_ptr res, nn_srcptr a, slong astride, nn_srcptr b, slong bstride, slong len)
{
    ulong A0, A1, A2, A3, B0, B1, B2, B3;
    ulong ma;
    ulong mb;
    ulong r0, r1, r2, r3, r4, r5, r6, r7;
    ulong t[8];
    slong k;

    r0 = r1 = r2 = r3 = r4 = r5 = r6 = r7 = 0;

    for (k = 0; k < len; k++)
    {
        A0 = a[0];
        A1 = a[1];
        A2 = a[2];
        A3 = a[3];
        B0 = b[0];
        B1 = b[1];
        B2 = b[2];
        B3 = b[3];
        ma = FLINT_SIGN_EXT(A3);
        mb = FLINT_SIGN_EXT(B3);

        flint_mpn_mul_n(t, a, b, 4);
        add_ssssssssaaaaaaaaaaaaaaaa(r7, r6, r5, r4, r3, r2, r1, r0, r7, r6, r5, r4, r3, r2, r1, r0, t[7], t[6], t[5], t[4], t[3], t[2], t[1], t[0]);
        sub_ddddmmmmssss(r7, r6, r5, r4, r7, r6, r5, r4, (ma & B3), (ma & B2), (ma & B1), (ma & B0));
        sub_ddddmmmmssss(r7, r6, r5, r4, r7, r6, r5, r4, (mb & A3), (mb & A2), (mb & A1), (mb & A0));

        a += astride;
        b += bstride;
    }

    res[0] = r0;
    res[1] = r1;
    res[2] = r2;
    res[3] = r3;
    res[4] = r4;
    res[5] = r5;
    res[6] = r6;
    res[7] = r7;
}

const flint_mpn_dot_strided_func_t flint_mpn_dot_strided_tab[2][5][5][3] = {
    {
        {
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_strided_1x1_1, _flint_mpn_dot_strided_1x1_2, _flint_mpn_dot_strided_1x1_3 },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_strided_2x1_2, _flint_mpn_dot_strided_2x1_3, _flint_mpn_dot_strided_2x1_4 },
            { _flint_mpn_dot_strided_2x2_3, _flint_mpn_dot_strided_2x2_4, _flint_mpn_dot_strided_2x2_5 },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_strided_3x1_3, _flint_mpn_dot_strided_3x1_4, _flint_mpn_dot_strided_3x1_5 },
            { _flint_mpn_dot_strided_3x2_4, _flint_mpn_dot_strided_3x2_5, _flint_mpn_dot_strided_3x2_6 },
            { _flint_mpn_dot_strided_3x3_5, _flint_mpn_dot_strided_3x3_6, _flint_mpn_dot_strided_3x3_7 },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_strided_4x1_4, _flint_mpn_dot_strided_4x1_5, _flint_mpn_dot_strided_4x1_6 },
            { _flint_mpn_dot_strided_4x2_5, _flint_mpn_dot_strided_4x2_6, _flint_mpn_dot_strided_4x2_7 },
            { _flint_mpn_dot_strided_4x3_6, _flint_mpn_dot_strided_4x3_7, _flint_mpn_dot_strided_4x3_8 },
            { _flint_mpn_dot_strided_4x4_7, _flint_mpn_dot_strided_4x4_8, NULL },
        },
    },
    {
        {
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_strided_1x1_1_signed, _flint_mpn_dot_strided_1x1_2_signed, _flint_mpn_dot_strided_1x1_3_signed },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_strided_2x1_2_signed, _flint_mpn_dot_strided_2x1_3_signed, _flint_mpn_dot_strided_2x1_4_signed },
            { _flint_mpn_dot_strided_2x2_3_signed, _flint_mpn_dot_strided_2x2_4_signed, _flint_mpn_dot_strided_2x2_5_signed },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_strided_3x1_3_signed, _flint_mpn_dot_strided_3x1_4_signed, _flint_mpn_dot_strided_3x1_5_signed },
            { _flint_mpn_dot_strided_3x2_4_signed, _flint_mpn_dot_strided_3x2_5_signed, _flint_mpn_dot_strided_3x2_6_signed },
            { _flint_mpn_dot_strided_3x3_5_signed, _flint_mpn_dot_strided_3x3_6_signed, _flint_mpn_dot_strided_3x3_7_signed },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_strided_4x1_4_signed, _flint_mpn_dot_strided_4x1_5_signed, _flint_mpn_dot_strided_4x1_6_signed },
            { _flint_mpn_dot_strided_4x2_5_signed, _flint_mpn_dot_strided_4x2_6_signed, _flint_mpn_dot_strided_4x2_7_signed },
            { _flint_mpn_dot_strided_4x3_6_signed, _flint_mpn_dot_strided_4x3_7_signed, _flint_mpn_dot_strided_4x3_8_signed },
            { _flint_mpn_dot_strided_4x4_7_signed, _flint_mpn_dot_strided_4x4_8_signed, NULL },
        },
    },
};

const flint_mpn_dot_func_t flint_mpn_dot_tab[2][3][3][3] = {
    {
        {
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_1x1_1, _flint_mpn_dot_1x1_2, _flint_mpn_dot_1x1_3 },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_2x1_2, _flint_mpn_dot_2x1_3, _flint_mpn_dot_2x1_4 },
            { _flint_mpn_dot_2x2_3, _flint_mpn_dot_2x2_4, _flint_mpn_dot_2x2_5 },
        },
    },
    {
        {
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_1x1_1_signed, _flint_mpn_dot_1x1_2_signed, _flint_mpn_dot_1x1_3_signed },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_2x1_2_signed, _flint_mpn_dot_2x1_3_signed, _flint_mpn_dot_2x1_4_signed },
            { _flint_mpn_dot_2x2_3_signed, _flint_mpn_dot_2x2_4_signed, _flint_mpn_dot_2x2_5_signed },
        },
    },
};

const flint_mpn_dot_func_t flint_mpn_dot_rev_tab[2][3][3][3] = {
    {
        {
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_rev_1x1_1, _flint_mpn_dot_rev_1x1_2, _flint_mpn_dot_rev_1x1_3 },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_rev_2x1_2, _flint_mpn_dot_rev_2x1_3, _flint_mpn_dot_rev_2x1_4 },
            { _flint_mpn_dot_rev_2x2_3, _flint_mpn_dot_rev_2x2_4, _flint_mpn_dot_rev_2x2_5 },
        },
    },
    {
        {
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_rev_1x1_1_signed, _flint_mpn_dot_rev_1x1_2_signed, _flint_mpn_dot_rev_1x1_3_signed },
            { NULL, NULL, NULL },
        },
        {
            { NULL, NULL, NULL },
            { _flint_mpn_dot_rev_2x1_2_signed, _flint_mpn_dot_rev_2x1_3_signed, _flint_mpn_dot_rev_2x1_4_signed },
            { _flint_mpn_dot_rev_2x2_3_signed, _flint_mpn_dot_rev_2x2_4_signed, _flint_mpn_dot_rev_2x2_5_signed },
        },
    },
};
