/*
    Copyright (C) 2026 Maël Hostettler

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

/*
    The elliptic curve group seen from the generic interface. The module's
    own test suite covers the point arithmetic; what is checked here is
    that the gr domain behaves like an abelian group with the integers
    acting on it, using only gr_* calls on a gr_ctx_t.
*/

#include "test_helpers.h"
#include "fmpq.h"
#include "gr.h"
#include "gr_ec.h"

/* #E(F_p), counted by trying every pair (x, y) */
static ulong
curve_order(gr_ec_ctx_t E, gr_ctx_t R, ulong p)
{
    gr_ec_aff_point_t P;
    gr_ptr x, y;
    ulong i, j, N;

    gr_ec_aff_point_init(P, E);
    GR_TMP_INIT2(x, y, R);

    N = 1;      /* the point at infinity */

    for (i = 0; i < p; i++)
    {
        GR_MUST_SUCCEED(gr_set_ui(x, i, R));

        for (j = 0; j < p; j++)
        {
            GR_MUST_SUCCEED(gr_set_ui(y, j, R));

            if (gr_ec_aff_point_set_affine(P, x, y, E) == GR_SUCCESS)
                N++;
        }
    }

    GR_TMP_CLEAR2(x, y, R);
    gr_ec_aff_point_clear(P, E);

    return N;
}

/*
    Lagrange, through the generic interface: N P is the identity for every
    point of E(F_p), where N is the order of the group. This is the one
    check here that would notice a scalar multiplication which is
    self-consistent but wrong.
*/
static void
check_group_order_annihilates(flint_rand_t state)
{
    ulong p = 101;
    slong a6;

    for (a6 = 1; a6 <= 3; a6++)
    {
        gr_ctx_t R;
        gr_ec_ctx_t E;
        gr_ec_repr_t repr;

        GR_MUST_SUCCEED(gr_ctx_init_nmod(R, p));

        if (gr_ec_ctx_init_short_weierstrass_si(E, R, 1, a6) != GR_SUCCESS)
        {
            gr_ctx_clear(R);
            continue;
        }

        {
            ulong N = curve_order(E, R, p);
            fmpz_t n;

            fmpz_init_set_ui(n, N);

            for (repr = 0; repr < GR_EC_NUM_REPRS; repr++)
            {
                gr_ptr P, res;
                slong iter;

                FLINT_TEST(gr_ec_ctx_set_repr(E, repr) == GR_SUCCESS);

                GR_TMP_INIT2(P, res, E);

                for (iter = 0; iter < 20; iter++)
                {
                    FLINT_TEST(gr_randtest(P, state, E) == GR_SUCCESS);

                    FLINT_TEST(gr_mul_ui(res, P, N, E) == GR_SUCCESS);
                    FLINT_TEST(gr_is_zero(res, E) == T_TRUE);

                    FLINT_TEST(gr_mul_fmpz(res, P, n, E) == GR_SUCCESS);
                    FLINT_TEST(gr_is_zero(res, E) == T_TRUE);

                    FLINT_TEST(gr_mul_si(res, P, -(slong) N, E) == GR_SUCCESS);
                    FLINT_TEST(gr_is_zero(res, E) == T_TRUE);
                }

                GR_TMP_CLEAR2(P, res, E);
            }

            fmpz_clear(n);
        }

        gr_ctx_clear(E);
        gr_ctx_clear(R);
    }
}

/*
    The 2-torsion of y^2 = x^3 - x over Q is generated by (0, 0), (1, 0)
    and (-1, 0). Each is killed by doubling, so every operation that ought
    to be a power-of-two multiplication can be pinned to a known answer.
*/
static void
check_two_torsion_over_q(void)
{
    gr_ctx_t R;
    gr_ec_ctx_t E;
    gr_ec_repr_t repr;
    slong which;

    gr_ctx_init_fmpq(R);
    FLINT_TEST(gr_ec_ctx_init_short_weierstrass_si(E, R, -1, 0) == GR_SUCCESS);

    for (repr = 0; repr < GR_EC_NUM_REPRS; repr++)
    {
        FLINT_TEST(gr_ec_ctx_set_repr(E, repr) == GR_SUCCESS);

        for (which = -1; which <= 1; which++)
        {
            gr_ptr P, res;
            gr_ptr x, y;
            fmpz_t e;
            slong k;

            GR_TMP_INIT2(P, res, E);
            GR_TMP_INIT2(x, y, R);
            fmpz_init(e);

            GR_MUST_SUCCEED(gr_set_si(x, which, R));
            GR_MUST_SUCCEED(gr_zero(y, R));

            /* building a point needs the module: no integer is a point */
            switch (repr)
            {
                case GR_EC_REPR_PROJECTIVE:
                    FLINT_TEST(gr_ec_point_set_affine(P, x, y, E) == GR_SUCCESS);
                    break;
                case GR_EC_REPR_AFFINE:
                    FLINT_TEST(gr_ec_aff_point_set_affine(P, x, y, E) == GR_SUCCESS);
                    break;
                default:
                    FLINT_TEST(gr_ec_jac_point_set_affine(P, x, y, E) == GR_SUCCESS);
                    break;
            }

            FLINT_TEST(gr_is_zero(P, E) == T_FALSE);

            /* 2 P = O, however it is spelled */
            FLINT_TEST(gr_mul_two(res, P, E) == GR_SUCCESS);
            FLINT_TEST(gr_is_zero(res, E) == T_TRUE);

            FLINT_TEST(gr_mul_ui(res, P, 2, E) == GR_SUCCESS);
            FLINT_TEST(gr_is_zero(res, E) == T_TRUE);

            FLINT_TEST(gr_mul_si(res, P, -2, E) == GR_SUCCESS);
            FLINT_TEST(gr_is_zero(res, E) == T_TRUE);

            /* 2^k P = O for every k >= 1, and 2^0 P = P */
            FLINT_TEST(gr_mul_2exp_si(res, P, 0, E) == GR_SUCCESS);
            FLINT_TEST(gr_equal(res, P, E) == T_TRUE);

            for (k = 1; k <= 8; k++)
            {
                FLINT_TEST(gr_mul_2exp_si(res, P, k, E) == GR_SUCCESS);
                FLINT_TEST(gr_is_zero(res, E) == T_TRUE);

                fmpz_set_si(e, k);
                FLINT_TEST(gr_mul_2exp_fmpz(res, P, e, E) == GR_SUCCESS);
                FLINT_TEST(gr_is_zero(res, E) == T_TRUE);
            }

            /* odd multiples of a 2-torsion point are the point itself */
            FLINT_TEST(gr_mul_ui(res, P, 7, E) == GR_SUCCESS);
            FLINT_TEST(gr_equal(res, P, E) == T_TRUE);

            /* an exponent too large to iterate over is not an answer,
               but it is one for the identity */
            fmpz_one(e);
            fmpz_mul_2exp(e, e, 200);
            FLINT_TEST(gr_mul_2exp_fmpz(res, P, e, E) == GR_UNABLE);

            FLINT_TEST(gr_zero(res, E) == GR_SUCCESS);
            FLINT_TEST(gr_mul_2exp_fmpz(res, res, e, E) == GR_SUCCESS);
            FLINT_TEST(gr_is_zero(res, E) == T_TRUE);

            /* halving a point is not a single valued operation */
            FLINT_TEST(gr_mul_2exp_si(res, P, -1, E) == GR_DOMAIN);
            fmpz_set_si(e, -1);
            FLINT_TEST(gr_mul_2exp_fmpz(res, P, e, E) == GR_DOMAIN);

            fmpz_clear(e);
            GR_TMP_CLEAR2(x, y, R);
            GR_TMP_CLEAR2(P, res, E);
        }
    }

    gr_ctx_clear(E);
    gr_ctx_clear(R);
}

/* the group axioms and the Z-action, over a range of base rings */
static void
check_additive_group(flint_rand_t state)
{
    slong which;

    for (which = 0; which < 6; which++)
    {
        gr_ctx_t R;
        gr_ec_ctx_t E;
        gr_ec_repr_t repr;
        fmpz_t p;
        int exact_field = 1;

        switch (which)
        {
            case 0:
                GR_MUST_SUCCEED(gr_ctx_init_nmod(R, 65537));
                break;

            case 1:
                fmpz_init(p);
                fmpz_set_str(p, "1000000000000000000000000000057", 10);
                gr_ctx_init_fmpz_mod(R, p);
                fmpz_clear(p);
                break;

            case 2:
                gr_ctx_init_fq_nmod(R, 7, 3, "a");
                break;

            case 3:
                /* characteristic 2, so the long Weierstrass path */
                gr_ctx_init_fq_nmod(R, 2, 5, "a");
                break;

            case 4:
                /* characteristic 3 */
                gr_ctx_init_fq_nmod(R, 3, 3, "a");
                break;

            default:
                /* an integral domain that is not a field: affine is
                   refused, and being infinite the scalars stay small */
                gr_ctx_init_fmpz(R);
                exact_field = 0;
                break;
        }

        {
            gr_ptr a1, a2, a3, a4, a6;

            GR_TMP_INIT5(a1, a2, a3, a4, a6, R);

            GR_MUST_SUCCEED(gr_zero(a2, R));
            GR_MUST_SUCCEED(gr_zero(a3, R));
            GR_MUST_SUCCEED(gr_one(a6, R));

            /*
                Long Weierstrass in characteristic 2 and 3, where it is
                the model that matters: y^2 + x y = x^3 + 1 is nonsingular
                in characteristic 2, and y^2 + x y = x^3 + x + 1 in
                characteristic 3. Short Weierstrass y^2 = x^3 + x + 1
                elsewhere.
            */
            if (which == 3 || which == 4)
                GR_MUST_SUCCEED(gr_one(a1, R));
            else
                GR_MUST_SUCCEED(gr_zero(a1, R));

            if (which == 3)
                GR_MUST_SUCCEED(gr_zero(a4, R));
            else
                GR_MUST_SUCCEED(gr_one(a4, R));

            FLINT_TEST(gr_ctx_init_gr_ec(E, R, a1, a2, a3, a4, a6,
                        GR_EC_REPR_PROJECTIVE) == GR_SUCCESS);

            GR_TMP_CLEAR5(a1, a2, a3, a4, a6, R);
        }

        /* the characteristic 2 and 3 curves really are on the long model */
        FLINT_TEST(gr_ec_ctx_model(E) == ((which == 3 || which == 4)
                    ? GR_EC_LONG_WEIERSTRASS : GR_EC_SHORT_WEIERSTRASS));

        FLINT_TEST(gr_ctx_is_ring(E) == T_FALSE);
        FLINT_TEST(gr_ec_ctx_repr(E) == GR_EC_REPR_PROJECTIVE);

        for (repr = 0; repr < GR_EC_NUM_REPRS; repr++)
        {
            int flags = 0;

            if (repr == GR_EC_REPR_AFFINE && !exact_field)
            {
                FLINT_TEST(gr_ec_ctx_set_repr(E, repr) == GR_DOMAIN);
                continue;
            }

            FLINT_TEST(gr_ec_ctx_set_repr(E, repr) == GR_SUCCESS);

            if (exact_field)
                flags = GR_TEST_ALWAYS_ABLE;

            gr_test_additive_group(E, exact_field ? 30 : 10, flags);
        }

        gr_ctx_clear(E);
        gr_ctx_clear(R);
    }
}

/*
    Over a base ring with zero divisors, E is not a group and the group
    axioms must not be asserted. Adding two honest points can produce a
    projective triple whose Z is a zero divisor, which is neither an affine
    point nor the point at infinity; from there the chord and tangent
    formulas have nothing to say. That is not a defect to be fixed -- it is
    what elliptic curve factorization exploits -- so the operations stay
    available and only their meaning is restricted.

    What is checked here is that the domain is still usable: nothing
    crashes, and a representation needing inversion is refused up front.
*/
static void
check_ring_with_zero_divisors(flint_rand_t state)
{
    gr_ctx_t R;
    gr_ec_ctx_t E;
    gr_ptr P, Q, res;
    slong iter;

    GR_MUST_SUCCEED(gr_ctx_init_nmod(R, 35));
    FLINT_TEST(gr_ctx_is_field(R) == T_FALSE);
    FLINT_TEST(gr_ec_ctx_init_short_weierstrass_si(E, R, 1, 1) == GR_SUCCESS);

    /* affine arithmetic would have to invert */
    FLINT_TEST(gr_ec_ctx_set_repr(E, GR_EC_REPR_AFFINE) == GR_DOMAIN);
    FLINT_TEST(gr_ec_ctx_repr(E) == GR_EC_REPR_PROJECTIVE);

    GR_TMP_INIT3(P, Q, res, E);

    for (iter = 0; iter < 100; iter++)
    {
        int status;

        FLINT_TEST(gr_randtest(P, state, E) == GR_SUCCESS);
        FLINT_TEST(gr_randtest(Q, state, E) == GR_SUCCESS);

        status = gr_add(res, P, Q, E);
        FLINT_TEST(status == GR_SUCCESS || status == GR_UNABLE);

        status = gr_mul_two(res, P, E);
        FLINT_TEST(status == GR_SUCCESS || status == GR_UNABLE);

        status = gr_mul_ui(res, P, n_randtest(state), E);
        FLINT_TEST(status == GR_SUCCESS || status == GR_UNABLE);
    }

    GR_TMP_CLEAR3(P, Q, res, E);

    gr_ctx_clear(E);
    gr_ctx_clear(R);
}

/* a curve over Q: exact, but infinite, so the scalars have to stay small */
static void
check_additive_group_over_q(void)
{
    gr_ctx_t R;
    gr_ec_ctx_t E;
    gr_ec_repr_t repr;

    gr_ctx_init_fmpq(R);
    FLINT_TEST(gr_ec_ctx_init_si(E, R, 0, -1, 1, -10, -20) == GR_SUCCESS);

    for (repr = 0; repr < GR_EC_NUM_REPRS; repr++)
    {
        FLINT_TEST(gr_ec_ctx_set_repr(E, repr) == GR_SUCCESS);
        gr_test_additive_group(E, 10, 0);
    }

    gr_ctx_clear(E);
    gr_ctx_clear(R);
}

TEST_FUNCTION_START(gr_ec, state)
{
    check_additive_group(state);
    check_additive_group_over_q();
    check_ring_with_zero_divisors(state);
    check_two_torsion_over_q();
    check_group_order_annihilates(state);

    TEST_FUNCTION_END(state);
}
