#!/bin/bash
set -e
export LDFLAGS="-Wl,-rpath,${NB_PYTHON_PREFIX}/lib -L${NB_PYTHON_PREFIX}/lib"
./configure \
    --prefix=${NB_PYTHON_PREFIX} \
    --with-gmp=${NB_PYTHON_PREFIX} \
    --with-mpfr=${NB_PYTHON_PREFIX} \
    --with-flint=${NB_PYTHON_PREFIX} \
    --with-arb=${NB_PYTHON_PREFIX} \
    --with-antic=${NB_PYTHON_PREFIX}
make -j4
make install
