/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

#include "flint.h"
#include "mpn_extras.h"
#include "mp_real.h"
#include "impl.h"

/* Odd and even series of a reduced argument t < 2^-r at any size: the
   generic form of the per-size series of the generated kernels
   (dev/gen_mp_real_trig_hand_mixed.py).  With z = t^2:

       tan t     = t + t^3 V_0,   V_j = T_(j+2)/(2j+3)! + z V_(j+1)
       atan t    = t - t^3 V_0,   V_j = 1/(2j+3)        - z V_(j+1)
       atanh t   = t + t^3 V_0,   V_j = 1/(2j+3)        + z V_(j+1)
       sin t     = t - t^3 V_0,   V_j = 1/(2j+3)!       - z V_(j+1)
       1 - cos t =     z V_0,     V_j = 1/(2j+2)!       - z V_(j+1)

   (T_m the tangent numbers).  All coefficients are positive, at most
   1/2 and decreasing, and every V_j is positive (in the alternating
   cases z V_(j+1) < 2^-2r c_j), so the recurrences need no sign
   handling.  Horner's rule runs over TAPERED widths: level j enters the
   result multiplied by t^(e_j), e_j = 2j + 3 (resp. 2j + 2 for the
   cosine), below 2^(-r e_j), so it needs only

       L_j = ceil((64 n + g - r e_j) / 64)

   limbs (and never fewer than the next level: the chain only widens),
   g = bits(N) + 1 guard bits for N levels.  Each level costs one
   flint_mpn_mulhigh_n at its width, reading the top L_j limbs of z and
   of the coefficient; the cost falls with r, i.e. with the argument's
   leading zero bits.

   Error (in ulps 2^(-64 n)): at level j the coefficient floor, the
   truncation of z to L_j limbs (times V_(j+1) <= 1/2) and the mulhigh
   (a lower bound within 2 L_j - 3 ulps of the limb below its output)
   are each below one unit 2^(-64 L_j), so V_j gains under 2.5 units,
   which t^(e_j) scales to at most 2.5 2^-g ulps; over N levels this is
   below 1.3 ulps.  The omitted tail (terms with ratio below 2^-2r, of
   one sign or alternating) is below one ulp; the squaring z =
   sqrhigh(t), t^3 = mulhigh(z, t) and the final mulhigh add at most
   three.  So |res - f(t)| < 6 ulps, (res, n) without a units limb.

   The coefficients are static (elem_tables.c, generated by
   dev/gen_mp_real_elem_tables.py): floor(c_j B^W_j) with W_j the widest
   L_j over the supported range n <= NMAX, r >= RMIN of each series,
   whose top L limbs are floor(c_j B^L) (floors nest), together with an
   upper bound for log2 c_j. */

typedef struct
{
    const ulong * c;
    const short * off;
    const short * w;
    const short * lg;
    slong K;
}
series_tab_struct;

static const series_tab_struct _series_tab[5] = {
    { _mp_real_series_tan_c, _mp_real_series_tan_off, _mp_real_series_tan_w,
      _mp_real_series_tan_lg, MP_REAL_SERIES_TAN_K },
    { _mp_real_series_atan_c, _mp_real_series_atan_off, _mp_real_series_atan_w,
      _mp_real_series_atan_lg, MP_REAL_SERIES_ATAN_K },
    { _mp_real_series_atan_c, _mp_real_series_atan_off, _mp_real_series_atan_w,
      _mp_real_series_atan_lg, MP_REAL_SERIES_ATAN_K },
    { _mp_real_series_sin_c, _mp_real_series_sin_off, _mp_real_series_sin_w,
      _mp_real_series_sin_lg, MP_REAL_SERIES_SIN_K },
    { _mp_real_series_cos_c, _mp_real_series_cos_off, _mp_real_series_cos_w,
      _mp_real_series_cos_lg, MP_REAL_SERIES_COS_K },
};

/* the Horner chain from level N - 1 down to level j0: (V, return value)
   = the top L_(j0) limbs of V_(j0), level j at the width
   L_j = min(n, ceil((64 n + g - r e_j) / 64)) (at least 1, and never
   narrower than the next level), z the n-limb fraction t^2 */
slong
_mp_real_series_tapered_horner(nn_ptr V, nn_srcptr z, slong n,
    flint_bitcnt_t r, int func, slong j0, slong N, slong g)
{
    const series_tab_struct * S = _series_tab + func;
    slong j, cur, prev, e0;
    slong * L;
    nn_ptr T, P;
    nn_srcptr c;
    int alt = (func == MP_REAL_SERIES_ATAN || func == MP_REAL_SERIES_SIN
        || func == MP_REAL_SERIES_COS);
    TMP_INIT;

    FLINT_ASSERT(0 <= j0 && j0 < N && N <= S->K);

    e0 = (func == MP_REAL_SERIES_COS) ? 2 : 3;

    TMP_START;
    L = TMP_ALLOC(N * sizeof(slong));
    T = TMP_ALLOC(2 * n * sizeof(ulong));
    P = T + n;

    for (j = j0; j < N; j++)
    {
        slong bits = FLINT_BITS * n + g - (slong) r * (e0 + 2 * j);
        L[j] = (bits <= 0) ? 1 : FLINT_MIN(n, (bits + FLINT_BITS - 1) / FLINT_BITS);
    }
    for (j = N - 1; j > j0; j--)
        L[j - 1] = FLINT_MAX(L[j - 1], L[j]);

    /* coefficient j: (S->c + S->off[j], S->w[j]), read at its top L_j
       <= S->w[j] limbs */
    c = S->c + S->off[N - 1];
    cur = L[N - 1];
    flint_mpn_copyi(V, c + S->w[N - 1] - cur, cur);

    for (j = N - 2; j >= j0; j--)
    {
        prev = cur;
        cur = L[j];
        c = S->c + S->off[j] + S->w[j] - cur;
        flint_mpn_zero(P, cur - prev);
        flint_mpn_copyi(P + cur - prev, V, prev);
        flint_mpn_mulhigh_n(T, z + n - cur, P, cur);
        if (alt)
            mpn_sub_n(V, c, T, cur);
        else
            mpn_add_n(V, c, T, cur);
    }

    TMP_END;
    return cur;
}

/* the number of levels: the first omitted term below 2^(-64 n - 2); at
   most K within the supported range */
slong
_mp_real_series_tapered_levels(slong n, flint_bitcnt_t r, int func)
{
    const series_tab_struct * S = _series_tab + func;
    slong N, e0 = (func == MP_REAL_SERIES_COS) ? 2 : 3;

    for (N = 0; N < S->K; N++)
        if (S->lg[N] - (slong) r * (e0 + 2 * N) < -FLINT_BITS * n - 2)
            break;
    FLINT_ASSERT(N < S->K || S->lg[S->K - 1] - (slong) r * (e0 + 2 * S->K) < -FLINT_BITS * n - 2);
    return FLINT_MAX(N, 1);
}

void
_mp_real_series_tapered(nn_ptr res, nn_srcptr x, slong n,
    flint_bitcnt_t r, int func)
{
    slong N, g, cur;
    nn_ptr z, V, T, P;
    int alt = (func == MP_REAL_SERIES_ATAN || func == MP_REAL_SERIES_SIN
        || func == MP_REAL_SERIES_COS);
    TMP_INIT;

    FLINT_ASSERT(n >= 1);
    FLINT_ASSERT(n <= _mp_real_series_tapered_nmax(func));
    FLINT_ASSERT((slong) r >= _mp_real_series_tapered_rmin(func));

    N = _mp_real_series_tapered_levels(n, r, func);

    TMP_START;
    z = TMP_ALLOC(4 * n * sizeof(ulong));
    V = z + n;
    T = V + n;
    P = T + n;

    g = FLINT_BIT_COUNT(N) + 1;
    flint_mpn_sqrhigh(z, x, n);
    cur = _mp_real_series_tapered_horner(V, z, n, r, func, 0, N, g);

    flint_mpn_zero(P, n - cur);
    flint_mpn_copyi(P + n - cur, V, cur);

    if (func == MP_REAL_SERIES_COS)
    {
        /* 1 - cos t = z V_0 */
        flint_mpn_mulhigh_n(res, z, P, n);
    }
    else
    {
        /* t -+ t^3 V_0 */
        flint_mpn_mulhigh_n(T, z, x, n);
        flint_mpn_mulhigh_n(V, T, P, n);
        if (alt)
            mpn_sub_n(res, x, V, n);
        else
            mpn_add_n(res, x, V, n);
    }

    TMP_END;
}
