/*
    Copyright (C) 2026 Fredrik Johansson

    This file is part of FLINT.

    FLINT is free software: you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License (LGPL) as published
    by the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
*/

#include "test_helpers.h"
#include "fmpz.h"
#include "arb.h"
#include "mp_real.h"
#include "ball_helpers.h"

/* mp_real_tan_bits: when the status is 1, the output contains tan of a
   random point of the input ball; for exact arguments it has a relative
   accuracy of about prec bits, including near the zeros and poles of
   the tangent (whose arguments are generated by rounding k pi/2 to many
   more bits than prec) and the status is 1 (below the size limit of the
   reduction); a status 0 only occurs for inexact arguments whose ball,
   widened three times, contains a pole; the output may alias the input. */

/* x = m exactly (an exact arf, nonzero or zero) */
static void
tan_test_set_arf(mp_real_t x, const arf_t m)
{
    fmpz_t man, e;
    slong sz;
    nn_ptr d;
    int neg;

    if (arf_is_zero(m))
    {
        mp_real_zero(x);
        return;
    }

    fmpz_init(man);
    fmpz_init(e);
    arf_get_fmpz_2exp(man, e, m);
    neg = (fmpz_sgn(man) < 0);
    fmpz_abs(man, man);
    sz = fmpz_size(man);
    d = flint_malloc(sz * sizeof(ulong));
    fmpz_get_ui_array(d, sz, man);
    _mp_real_set_mpn_2exp(x, d, sz, fmpz_get_si(e));
    if (neg)
        mp_real_neg(x, x);
    flint_free(d);
    fmpz_clear(man);
    fmpz_clear(e);
}

TEST_FUNCTION_START(mp_real_tan_bits, state)
{
    slong iter;

    for (iter = 0; iter < 2000 * flint_test_multiplier(); iter++)
    {
        slong prec, wp, big;
        int kind, inexact, alias, ok;
        mp_real_t x, y;
        arb_t xa, ya, ref, t;
        arf_t m, pt;

        if (iter % 100 == 0)
            prec = 2 + n_randint(state, 12000);
        else if (iter % 10 == 0)
            prec = 2 + n_randint(state, 2500);
        else
            prec = 2 + n_randint(state, 300);

        kind = n_randint(state, 6);
        inexact = (n_randint(state, 3) == 0);
        alias = n_randint(state, 2);

        mp_real_init(x);
        mp_real_init(y);
        arb_init(xa);
        arb_init(ya);
        arb_init(ref);
        arb_init(t);
        arf_init(m);
        arf_init(pt);

        switch (kind)
        {
            case 0:     /* tiny */
                arf_randtest(m, state, prec + 10, 8);
                arf_mul_2exp_si(m, m, -(slong) n_randint(state, 3 * prec + 50));
                break;
            case 1:     /* unit */
                arf_randtest(m, state, prec + 10, 1);
                break;
            case 2:     /* one integral limb or so */
                arf_randtest(m, state, prec + 10, 6);
                break;
            case 3:     /* many limbs */
                arf_randtest(m, state, prec + 10, 12);
                break;
            default:    /* near k pi/2: 2^-d away, or rounded there */
            {
                slong k = (slong) n_randint(state, 1000) - 500;
                slong d = n_randint(state, 2 * prec + 100);

                arb_const_pi(t, prec + d + 200);
                arb_mul_si(t, t, k, prec + d + 200);
                arb_mul_2exp_si(t, t, -1);
                arf_set_round(m, arb_midref(t), prec + d + 20, ARF_RND_DOWN);
                if (kind == 5)
                {
                    arf_t u;
                    arf_init(u);
                    arf_set_ui_2exp_si(u, 1, -d);
                    arf_add(m, m, u, ARF_PREC_EXACT, ARF_RND_DOWN);
                    arf_clear(u);
                }
                break;
            }
        }

        tan_test_set_arf(x, m);
        if (inexact)
        {
            slong e = arf_is_zero(m) ? 0 : arf_abs_bound_lt_2exp_si(m);
            mp_real_add_error_2exp_si(x, e - (slong) n_randint(state, prec + 20));
        }
        mp_real_get_arb(xa, x);

        if (alias)
        {
            mp_real_set(y, x);
            ok = mp_real_tan_bits(y, y, prec);
        }
        else
            ok = mp_real_tan_bits(y, x, prec);
        mp_real_get_arb(ya, y);

        /* a point of the ball, at enough precision for its reference */
        mp_real_random_point(pt, x, state);
        wp = 2 * prec + FLINT_BITS * (x->size + 8) + 200;
        arb_set_arf(t, pt);
        arb_tan(ref, t, wp);

        big = (FLINT_BITS * (x->exp - 1) >= FLINT_MAX(65536, 4 * prec));

        if (ok)
        {
            if (!arb_overlaps(ya, ref))
            {
                flint_printf("FAIL: containment, kind %d, prec %wd, inexact %d\n", kind, prec, inexact);
                flint_printf("x = "); arb_printd(xa, 30);
                flint_printf("\ny = "); arb_printd(ya, 30);
                flint_printf("\n    "); arb_printd(ref, 30);
                flint_printf("\n");
                flint_abort();
            }

            if (!inexact && !arf_is_zero(m) && arb_rel_accuracy_bits(ya) < prec - 4)
            {
                flint_printf("FAIL: accuracy, kind %d, prec %wd, acc %wd\n", kind, prec,
                    arb_rel_accuracy_bits(ya));
                flint_printf("x = "); arb_printd(xa, 30);
                flint_printf("\ny = "); arb_printd(ya, 30);
                flint_printf("\n");
                flint_abort();
            }
        }
        else
        {
            arb_t w;
            int pole;

            arb_init(w);
            arb_set(w, xa);
            mag_mul_ui(arb_radref(w), arb_radref(w), 3);
            arb_cos(t, w, prec + FLINT_BITS * (x->size + 8) + 100);
            pole = arb_contains_zero(t);
            arb_clear(w);

            if (!big && (!inexact || !pole))
            {
                flint_printf("FAIL: status 0, kind %d, prec %wd, inexact %d\n", kind, prec, inexact);
                flint_printf("x = "); arb_printd(xa, 30); flint_printf("\n");
                flint_abort();
            }

            if (!mp_real_is_zero(y))
                TEST_FUNCTION_FAIL("status 0 without res = 0\n");
        }

        mp_real_clear(x);
        mp_real_clear(y);
        arb_clear(xa);
        arb_clear(ya);
        arb_clear(ref);
        arb_clear(t);
        arf_clear(m);
        arf_clear(pt);
    }

    /* special values */
    {
        mp_real_t x, y;
        arb_t a;

        mp_real_init(x);
        mp_real_init(y);
        arb_init(a);

        mp_real_zero(x);
        if (!mp_real_tan_bits(y, x, 64) || !mp_real_is_zero(y))
            TEST_FUNCTION_FAIL("zero\n");

        /* [11/7 +- 1/64] contains pi/2; [11/7 +- 2^-30] does not, 11/7 -
           pi/2 ~ 2^-10.7, and tan is known there to about 19 bits */
        mp_real_set_ui(x, 11);
        mp_real_div_ui(x, x, 7, 3);
        x->err = 0;
        mp_real_add_error_2exp_si(x, -6);
        if (mp_real_tan_bits(y, x, 64))
            TEST_FUNCTION_FAIL("pole not detected\n");
        mp_real_set_ui(x, 11);
        mp_real_div_ui(x, x, 7, 3);
        x->err = 0;
        mp_real_add_error_2exp_si(x, -30);
        if (!mp_real_tan_bits(y, x, 64))
            TEST_FUNCTION_FAIL("spurious pole\n");
        mp_real_get_arb(a, y);
        if (arb_rel_accuracy_bits(a) < 15)
            TEST_FUNCTION_FAIL("accuracy near a pole\n");

        mp_real_clear(x);
        mp_real_clear(y);
        arb_clear(a);
    }

    TEST_FUNCTION_END(state);
}
